
# International organizations, treaties, conventions and agreements

## United Nations and International Organizations

\begin{questions}

\question World conference on Women, 1975

\begin{solution}

The conference was held between 19 June and 2 July 1975 in Mexico City, Mexico. It was the first international conference held by the United Nations to focus solely on women's issues and marked a turning point in policy directives. After this meeting, women were viewed as part of the process to develop and implement policy, rather than recipients of assistance. The conference was one of the events established for International Women's Year and led to the creation of both the United Nations Decade for Women and follow-up conferences to evaluate the progress that had been made in eliminating discrimination against women and their equality. Two documents were adopted from the conference proceedings, the World Plan of Action which had specific targets for nations to implement for women's improvement and the Declaration of Mexico on the Equality of Women and Their Contribution to Development and Peace, which discussed how nations foreign policy actions impacted women. It also led to the establishment of the International Research and Training Institute for the Advancement of Women to track improvements and continuing issues and the United Nations Development Fund for Women to provide funding for developmental programs. The conference marked the first time that the parallel Tribune meeting was successful in submitting input to the official meeting and became a catalyst for women's groups to form throughout the world.

\end{solution}

\question United Nations Commission on Status of Women

\begin{solution}

The Commission on the Status of Women (CSW or UNCSW) is a functional commission of the United Nations Economic and Social Council (ECOSOC), one of the main UN organs within the United Nations. CSW has been described as the UN organ promoting gender equality and the empowerment of women. Every year, representatives of Member States gather at United Nations Headquarters in New York to evaluate progress on gender equality, identify challenges, set global standards and formulate concrete policies to promote gender equality and advancement of women worldwide. In April 2017, ECOSOC elected 13 new members to CSW for a four-year term 2018–2022. One of the new members is Saudi Arabia, which has been criticised for its treatment of women.

The commission was formed on 21 June 1946 and is headquartered in NY, USA.

\end{solution}

\end{questions}

## Rio convention (UN Conference on Environment and Development, UNCED) 

- Relates to three conventions, which are results of the Earth Summit held in Rio de Janeiro in 1992 (June 3rd to 14th).
- The convention documented the following:
  - Agenda 21 (a non-binding action plan of the UN promoting sustainable development),
  - The statement of Forest Principles,
  - The Rio Declaration on Environment and Development
  62. Following conventions were formed:
  - UNFCCC, UN Framework Convention on Climate Change
  - CBD, Convention on Biological Diversity
  - UNCCD, UN Convention to Combat Desertification

## The CBD

With 196 ratified parties, the CBD aims to conserve and protect biodiversity, biological resources and safeguard life on Earth, as an integral part of economic and social development. Considering biological diversity as a global asset to current and future generations and populations across the planet, the Convention works to prevent species extinction and maintain protected habitats. As well, the CBD promotes the sustainable use of components of biological diversity, and works to maintain the environmental and sustainable process of access and benefit sharing, derived from genetic resource use.

The convention was established on December 29th, 1993. It has following objectives:
  1. The conservation of biological diversity
  2. The sustainable use of components of biological diversity
  3. The fair and equitable sharing of benefits arising out of the utilization of genetic resources.
	
The CBD currently follows the Strategic Plan for Biodiversity 2011-2020 and its Aichi Biodiversity Targets, used as a vehicle to maintain synergies at National levels. Its mission is to "take effective and urgent action to halt the loss of biodiversity to ensure that by 2020, ecosystems are resilient and continue to provide essential services, thereby securing the planet's variety of life, and contributing to human well-being, and poverty eradication.

## The UNFCCC

With 197 ratified parties, the United Nations Framework Convention on Climate Change is committed to the objective of "[stabilizing] greenhouse gas concentrations in the atmosphere at a level that would prevent dangerous anthropogenic interference with the climate system. Such a level should be achieved within a time frame sufficient to allow ecosystems to adapt naturally to climate change, to ensure that food production is not threatened and to enable economic development to proceed in a sustainable manner." Following the adoption of the Paris Agreement in 2015 and previously the Kyoto Protocol in 1997, the UNFCCC Secretariat works to maintain the goals and objectives of the Convention, as the primary United Nations body whose role functions to address the threat of climate change.

- The Paris Agreement, 2015:

## The UNCCD

An international agreement that ties the sustainability of land management and the issues of land degradation to the environment. Among the areas of consideration, the Convention focuses on restoring degraded ecosystems found in dryland areas. The United Nations Convention to Combat Desertification (UNCCD), consisting of 197 parties works towards creating 'a future that avoids, minimizes, and reverses desertification/land degradation and mitigates the effects of drought in affected areas at all levels.'

Legislatively, the UNCCD is committed to achieving Land Degradation Neutrality (LDN) and combat pressing environmental issues of Desertification, land degradation and drought (DLDD) through a newly created 2018-2030 Strategic Framework, consistent with the 2030 Agenda for Sustainable Development. This framework follows the 10-year strategic plan and framework for 2008-2018 that aimed to establish global partnerships in working toward the reversal and prevention of desertification and land degradation. The UNCCD aims to restore the productivity of degraded land, while improving livelihoods and aiding populations that are vulnerable because of environmental destruction. "The Convention's 197 parties work together to improve the living conditions for people in drylands, to maintain and restore land and soil productivity, and to mitigate the effects of drought."

## Rio +20 Summit (Rio Earth Summit, 2012; June 13th-June 22nd)

The issues addressed included:

	- systematic scrutiny of patterns of production -- particularly the production of toxic components, such as lead in gasoline, or poisonous waste including radioactive chemicals
	- alternative sources of energy to replace the use of fossil fuels which delegates linked to global climate change
	- new reliance on public transportation systems in order to reduce vehicle emissions, congestion in cities and the health problems caused by polluted air and smoke
	- the growing usage and limited supply of water
- UNFCCC led to Kyoto Protocol and the Paris Agreement.

## Nagoya Protocol

The Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits Arising from their Utilization to the Convention on Biological Diversity, also known as the Nagoya Protocol on Access and Benefit Sharing (ABS) is a 2010 supplementary agreement to the 1992 Convention on Biological Diversity (CBD). Its aim is the implementation of one of the three objectives of the CBD: the fair and equitable sharing of benefits arising out of the utilization of genetic resources, thereby contributing to the conservation and sustainable use of biodiversity. However, there are concerns that the added bureaucracy and legislation will, overall, be damaging to the monitoring and collection of biodiversity, to conservation, to the international response to infectious diseases, and to research.

The protocol was adopted on 29 October 2010 in Nagoya, Japan, and entered into force on 12 October 2014. It has been ratified by 114 parties, which includes 113 UN member states and the European Union. It is the second protocol to the CBD; the first is the 2000 Cartagena Protocol on Biosafety. 

The Nagoya protocol applies to genetic resources that are covered by the CBD, and to the benefits arising from their utilization. The Nagoya Protocol sets out obligations for its contracting parties to take measures in relation to access to genetic resources, benefit-sharing and compliance. Implementation of the protocol deals with follwing major points:

  - The Nagoya Protocol's success will require effective implementation at the domestic level. A range of tools and mechanisms provided by the Nagoya Protocol will assist contracting parties including: 
  1. Establishing national focal points (NFPs) and competent national authorities (CNAs) to serve as contact points for information, grant access, or cooperate on issues of compliance 
  2. An Access and Benefit-sharing Clearing-House to share information, such as domestic regulatory ABS requirements or information on NFPs and CNAs 
  3. Capacity-building to support key aspects of implementation.

## The Ramsar Convention 

Abbreviated form for "The Ramsar Convention on Wetlands of International Importance especially as Waterfowl Habitat"; a.k.a. Convention on Wetlands)

It is an international treaty for conservation and sustainable use of wetlands. It is named after the city of Ramsar, Iran where convention was signed in 1971.

Every three years, representatives of the Contracting Parties meet as the conference of the Contracting Parties (COP), the policy-making organ of the Convention which adopts decisions (Resolutions and Recommendations) to administer the work of the Convention and improve the way in which the Parties are able to implement its objectives. COP12 was held in Punta del Este, Uruguay, in 2015. COP13 was held in Dubai, United Arab Emirates, in October 2018. 

List of Wetlands of International Importance include 2331 Ramsar sites in May 2018 covering over 2.1 million sqkm. The country with highest number of Sites is the UK with 170, and the country with the greatest area of listed wetlands is Bolivia, with over 140, 000 sqkm.

The Ramsar Convention works closely with six other organisations known as International Organization Partners (IOPs). These are:
  - Birdlife International
  - International Union for Conservation of Nature (IUCN)
  - International Water Management Institute (IWMI)
  - Wetlands International
  - WWF International
  - Wildfowl & Wetlands Trust (WWT)

These organizations support the work of the Convention by providing expert technical advice, helping implement field studies, and providing financial support. The IOPs also participate regularly as observers in all meetings of the Conference of the Parties and as full members of the Scientific and Technical Review Panel. 

Following bodies are established by the Convention: 1. Conference of contracting parties (COP), 2. The Standing Committee, 3. The Scientific and Technical Review Panel (STRP), 4. The Secretariat.

The secretariat is based at the headquarters of the IUCN, Gland, Switzerland. Martha Rojas Urrego is the sixth secretary of the Ramsar Convention on wetlands.

The 2nd of February each year is World Wetlands Day, marking the date of the adoption of the Convention on Wetlands on 2 February 1971. WWD was celebrated for the first time in 1997 and has grown remarkably since then. In 2015 World Wetlands Day was celebrated in 59 countries. 

## Cartagena Protocol on Biosafety to the Convention on Biological Diversity

Drafted: 29 Jan, 2000; Signed: 15 May, 2000; Location: Montreal, Quebec; Effective: 11 September, 2003; Signatories 103; Parties: 171; Depositary: Secretary-General of the United Nations – Record retrieved: September, 2019

It is supplement to the Convention on Biological Diversity effective since 2003. The Biosafety Protocol seeks to protect biological diversity from the potential risks posed by genetically modified organisms resulting from modern biotechnology.

The Biosafety Protocol makes clear that products from new technologies must be based on the precautionary principle and allow developing nations to balance public health against economic benefits. It will for example let countries ban imports of genetically modified organisms if they feel there is not enough scientific evidence that the product is safe and requires exporters to label shipments containing genetically altered commodities such as corn or cotton.

The required number of 50 instruments of ratification/accession/approval/acceptance by countries was reached in May 2003. In accordance with the provisions of its Article 37, the Protocol entered into force on 11 September 2003. As of February 2018, the Protocol had 171 parties, which includes 168 United Nations member states, the State of Palestine, Niue, and the European Union.
The precautionary approach is contained in Principle 15 of the Rio Declaration on Environment and Development.

The main features of the Cartagena Protocol on Biosafety are:
  1. Promotes biosafety by establishing rules and procedures for the safe transfer, handling, and use of LMOs, with specific focus on transboundary movements of LMOs.
  2. It features a set of procedures including one for LMOs that are to be intentionally introduced into the environment called the advance informed agreement procedure (AIA), and one for LMOs that are intended to be used directly as food or feed or for processing.
  3. Parties to the Protocol must ensure that LMOs are handled, packaged and transported under conditions of safety.
  4. The shipment of LMOs subject to transboundary movement must be accompanied by appropriate documentation specifying, among other things, identity of LMOs and contact point for further information.
  These procedures and requirements are designed to provide importing Parties with the necessary information needed for making informed decisions about whether or not to accept LMO imports and for handling them in a safe manner.

The Party of import makes its decisions in accordance with scientifically sound risk assessments. The Protocol sets out principles and methodologies on how to conduct a risk assessment. In case of insufficient relevant scientific information and knowledge, the Party of import may use precaution in making their decisions on import. Parties may also take into account, consistent with their international obligations, socio-economic considerations in reaching decisions on import of LMOs.

Parties must also adopt measures for managing any risks identified by the risk assessment, and they must take necessary steps in the event of accidental release of LMOs.

To facilitate its implementation, the Protocol establishes a Biosafety Clearing-House for Parties to exchange information, and contains a number of important provisions, including capacity-building, a financial mechanism, compliance procedures, and requirements for public awareness and participation. (Article 20 of the Protocol, SCBD 2000). The Biosafety Clearing-House was established in a phased manner, and the first meeting of the Parties approved the transition from the pilot phase to the fully operational phase, and adopted modalities for its operations (Decision BS-I/3, SCBD 2004). 

## The Kyoto Protocol 

Signed: 11 December, 1997; Location: Kyoto, Japan; Effective: 16 February, 2005, Condition: Ratificaiton by at least 55 states to the convention; Expiration: In force (first commitment period expired 31 December, 2012; Signatories: 84; Parties: 192)

This Protocol extends the 1992 UNFCCC that commits state parties to reduce GHG emissions, based on the scientific consensus that global warming is occurring and it extremely likely that human-made CO2 emissions have predominantly caused it. 

The Kyoto Protocol applies to the six greenhouse gases listed in Annex A: Carbon dioxide (CO2), Methane (CH4), Nitrous oxide (N2O), Hydrofluorocarbons (HFCs), Perfluorocarbons (PFCs), and Sulphur hexafluoride (SF6).

Canada withdrew from the Protocol in December, 2012. The protocol's second commitment period was agreed in 2012, known as Doha Amendment to the Kyoto Protocol, in which 37 countries have binding targets. As of September 2019, 132 states have accepted the Doha Amendment, while entry into force requires the acceptance of 144 states. Of the 37 countries with binding commitments, 7 have ratified.

Negotiations were held in the framework of the yearly UNFCCC Climate Change Conferences on measures to be taken after the second commitment period ends in 2020. This resulted in the 2015 adoption of the Paris Agreement, which is a separate instrument under the UNFCCC rather than an amendment of the Kyoto Protocol. 

On 8 December 2012, at the end of the 2012 United Nations Climate Change Conference, an agreement was reached to extend the Protocol to 2020 and to set a date of 2015 for the development of a successor document, to be implemented from 2020. The outcome of the Doha talks has received a mixed response, with small island states critical of the overall package. The Kyoto second commitment period applies to about 11% of annual global emissions of greenhouse gases. Other results of the conference include a timetable for a global agreement to be adopted by 2015 which includes all countries. At the Doha meeting of the parties to the UNFCCC on 8 December 2012, the European Union chief climate negotiator, Artur Runge-Metzger, pledged to extend the treaty, binding on the 27 European Member States, up to the year 2020 pending an internal ratification procedure.

Ban Ki Moon, Secretary General of the United Nations, called on world leaders to come to an agreement on halting global warming during the 69th Session of the UN General Assembly on 23 September 2014 in New York. UN member states have been negotiating a future climate deal over the last five years. A preliminary calendar was adopted to confirm "national contributions" to the reduction of CO2 emissions by 2015 before the UN climate summit which was held in Paris at the 2015 United Nations Climate Change Conference. 

## WTO

The WTO agreements cover a wide range of activities such as agriculture, textiles and clothing, banking, telecommunications, government purchases, industrial standards and product safety, food and sanitation regulations and intellectual property. GATT is now the WTO's principal rule-book for trade in goods. The Uruguay Round also created new rules for dealing with trade in services, relevant aspects of intellectual property, dispute settlement, and trade policy reviews. The complete set runs to some 30,000 pages consisting of about 30 agreements and separate commitments (called schedules) made by individual members in specific areas such as lower customs duty rates and services market-opening (WTO, 2008).

Agreement related to Agriculture Sector in WTO

Agreement on Agriculture (AOA)

The AOA was the outcome of the Uruguay Round (UR) negotiations that started in 1986 and concluded in 1994. The long-term objectives set by the AOA are to establish a fair and market oriented agricultural trading system through substantial reductions in agricultural support and protection.

AOA deals all the matters of tariff, domestic support and export subsidies. It is rightly identified that the root cause of distortion of international trade in agriculture is the massive domestic subsidies given by industrialized countries over the decades (WTO, 1995). In order to minimize such dumped exports and to keep their markets open for efficient agricultural producers of the world, the starting point has to be the reduction of the domestic production subsidies given by the industrialized countries, followed by reduction of export subsidies and the volume of subsidized exports, and minimum market access opportunity for foreign agricultural producers".

Domestic Support

Domestic support provides commitments to reduce agricultural subsidies and other programmes including those raise or guarantee farm gate prices and farmers' incomes. These supports are divided by the AOA into different boxes in tricky way.

Implications of AOA Domestic measures to Nepal

The agricultural businesses are linked to trade and hence to WTO in several ways. The agribusiness needs imported inputs, machineries and technology from abroad. The major inputs imported by Nepal are chemical fertilizers, pesticides, hormones, veterinary medicines, seeds and packaging materials. As the market is liberalized and imports are not restricted, the agribusiness also needs to compete in domestic markets with imported goods. Some agribusinesses generate exportable goods. The export can be done either under bilateral agreements (such as with India), regional agreements (like with Bangladesh and Pakistan) and multilateral agreements (like with the countries not involved in bilateral and regional agreements such as USA, European Union, Japan). All such activities of agribusiness like import of inputs, export of outputs and competition in domestic markets are affected Agreement on Agriculture (AOA), Application of Sanitary and Phytosanitary (SPS) measures, Agreement on Technical Barriers to Trade (TBT) and Agreement on Trade Related Aspects of Intellectual Property Rights (TRIPS) primarily.

Market Access

Market access is one of the three main pillars of the AOA – the other two being domestic support measures and export competition. It deals with rules and commitments related to import of goods. Its purpose is to expand trade by preventing various non-tariff barriers and by binding and reducing tariffs. Besides tariffs, other trade policy instruments covered by the market access pillar include Tariff Rate Quotas (TRQs) and Special Safeguard (SSG) as a trade remedy measure (Sharma and Karki, 2004).

In the WTO context, market access is about both obligations and rights. Nepal's obligation is to provide market access to other Members in return for her right of access to others' markets for Nepalese goods on multilaterally agreed terms. Thus, a balanced analysis of market access provisions would cover both obligations and rights.

The AoA provisions on market access
  - Prohibition of quantitative restrictions on imports
  - Tariff binding and reduction
  - Bound versus applied tariffs
  - Tariff Rate Quota
  - Special Safeguard Measures
  - Export subsidies and export restrictions

In common with all least developed countries (LDCs) and a majority of the developing countries, Nepal does not subsidize exports. At the time of the WTO accession, it committed not to subsidize exports in future also. One of the conclusions of the study is that this commitment is unlikely to have any negative implications for the Nepalese agriculture for two reasons. First, export subsidization is not a sound economic policy. Second, Nepal could not afford export subsidies at its low level of economic development. On the other hand, there were several instances in the past when export subsidization by other countries had some negative effects on the Nepalese agriculture. Therefore, it is in Nepal's interest to tighten WTO rules on export subsidy (Tiwari et al, 2004).

Implication on Nepalese Agriculture:
  - Nepal can promote exports through various incentive measures of the WTO Subsidies Agreement.
  - Limited implications of the WTO rules on export restriction and taxation policies.
  - Nepal is occasionally affected negatively by export subsidization by others
  - Domestic policy issues and analytical needs

Sanitory and Phyto Sanitory (SPS)

Food quality and safety issues have entered into a new era of evolution as it involves integrated effort linking production to consumption in the entire food chain. The traditional domain of inspecting and analysing the end product does not necessarily meet the requirement of emerging trade regime of WTO and related agreements such as the SPS.

The main objectives of the SPS Agreement are the following (Karki et al, 2004).
  - Protect and improve the current human health, animal health, and phytosanitary situation of all Member countries; and
  - The entry, establishment or spread of pests, disease, disease-carrying organisms or disease-causing organisms;
  - Additives, contaminants, toxins or disease-causing organisms in foods, beverages or feedstuffs;
  - Carried by animals, plants or products thereof, or from the entry, establishment or spread of pests; or
  - Prevent or limit other damage within the territory of the Member from the entry, establishment or spread of pests.

The following are the main elements of the SPS Agreement (Karki et al, 2004).
  1. Harmonization
  2. Equivalence
  3. Risk assessment
  4. Transparency
  5. Consultation and dispute settlement:
  6. Technical cooperation and Special and Differential Treatment

The SPS Agreement and Trade In Live Animals and Animal Products

The SPS Agreement recognizes the International Office of Epizootics (OIE) as the relevant international organisation responsible for the development and promotion of international animal health standards, guidelines, and recommendations affecting trade in live animals and animal products. Similarly, the official (Public) Veterinary Services of a country are recognized as the relevant authority with ultimate responsibility for animal health matters involving international trade in live animals and animal products.

The OIE provides detailed Guidelines for the Evaluation of Veterinary Services (Chapter 1.3.4. of the Terrestrial Animal Health Code). According to these guidelines, the national Veterinary Services should be able to demonstrate capacity, supported by appropriate legislation, in the following areas (Mahato et al, 2004).
- Exercise control over all animal health matters
- Prescribe methods for control and to exercise systematic control over the import and export processes of animals and animal products in so far as this control relates to sanitary and zoo-sanitary matters.
- Control imports and transit of animals, animal products and other materials that may introduce animal diseases.
- Present a functional animal disease reporting system which covers all regions of the country
- Provide accurate and valid certification for exports of animals and animal products.

The SPS Agreement: Trade in Plants and Plant Products

With increasing trade in plant and plant products, the risk of the spread of harmful pests and diseases has also increased. The negative impact on plant health and plant products could be substantial, e.g. an imported harmful pest could destroy entire orange production in a country or a region, or could result into reduced yield, quality deterioration and environmental pollution.

In the case of Nepal, export and import of agricultural and forest-based products through the long and porous borders had been taking place almost without any phytosanitary considerations until recently. To a large extent the practice continues even now. As the potential negative effects are being increasingly recognized and as WTO Members started to implement the SPS Agreement since 1995 the situation is changing. Nepal also had its share of the deleterious effects of the harmful pests that came with imported plants and the difficulties in exporting plants and products, particularly to India in recent years. In view of this, and her commitment to implement provisions of the SPS agreement by 1 January 2007 timely action in this direction has become necessary ( KC et al, 2004).

Agreement on Technical Barriers to Trade

Agreement on Technical Barriers to Trade (TBT) establishes disciplines on technical regulations, standards and conformity assessment procedures for agricultural and well as non-agricultural products. Technical regulations and standards deal with product characteristics, processes and production methods related to a product, and may also bear upon terminology, symbols, packaging, marking or labelling. Conformity assessment procedures, such as testing, inspection, evaluation and approval, are employed to determine compliance with technical regulations and standards.

The TBT agreement encourages members to give positive consideration to accepting as equivalent technical regulations of other members, even if those regulations differ from their own, provided they are satisfied that these regulations adequately fulfil the objectives of their own regulations. Under this provision, members retain the discretion to determine whether equivalence will adequately satisfy their legitimate regulatory objectives. This will lead to smoother trade of goods produced by the agribusiness as well (Pant, 2004).

Trade-related Aspects of Intellectual Property Rights

Agreement on Trade-related Aspects of Intellectual Property Rights (TRIPS) protects and enforces the rights of inventors. Its main objectives are promoting, transferring and disseminating the technological innovations for the advantages of both producers and users. In agriculture sector, it includes definition of specific genes and modifications of genes. Such genes modified organisms are commonly called genetically modified organisms (GMO). The major concern in TRIPS concerning to agriculture is the exploitation of plant genetic resources and claiming rights for gene spliced plants and animals. Therefore, seed related the TRIPS would affect businesses and seed using businesses in one or the other way (Pant, 2007).

Lastly, the TRIPS agreement provides that geographical indications, hitherto used for alcoholic products, can be used in agribusiness as well. This will be helpful to create and protect agricultural products having geographical reputations like Ilam tea, Sindhuli junar, Marpha apple, Nepal honey, etc. Such reputations of the names of the place will be protected by the law and produce of other geographic areas and foreign countries cannot use such indications.

General Agreement on Trade in services (GAT)

This Agreement opens the door for foreign investment in different sectors while accessing the membership of WTO by Nepal, had agreed on 74 different sectors and sub-sectors for trade out of which only 2 sectors are related to agriculture. They include
1. Animal medical services
2. Technical Experiment and investigation services

WTO and Emerging Issues in Nepalese Agriculture

Keeping eyes on the benefits that can arise from the agreements of WTO, we need to address major issues in agricultural sector. The issues at hand include scale sensitivity, trade restriction at disguise, resource mobility and technology transfer (Pant, 2004 & 2007).

1. Scale Sensitivity of WTO Provisions

It is usually believed that the WTO Agreement on Agriculture (AOA) does not focus on addressing the development needs and concerns of the small-scale subsistence farmers in developing countries. It rather tends to emphasize on commercial agriculture and trade. For example, rules under WTO say that the fees and charges on the services from the public sector should match the amount of the service provided and not be based on the volume of transactions.

2. Disguised Protection in the Name of Quality Standard

The AOA commits reductions in protection measures and trade distorting subsidies. The experience shows that the agricultural trade has become more protected in the developed countries after the establishment of WTO. In Nepal the agriculture is exposed to market forces in the name of economic liberalization.

3. Competitiveness

The major problem in international competition is our small scale and high cost of production. Low technology production makes our product less competitive in terms of quality. In addition, our trading partners may prevent entry of our products in the name of protecting animal, plant and human health and life in their country. We have competitiveness in the products with low capital and high labour inputs. Some of such products are, for example, hybrid vegetable seeds, flower seeds, medicinal herbs, silk, honey, dry fruits and cottage cheese.

4. Labour Mobility

Nepal's agriculture sector is labour surplus. As the surplus labour comes out of it, farms will experience labour shortage. This will have two effects. First, wage rate in the farm will increase. That will not only make agriculture workers better of but also make technological interventions like mechanization financially viable to adopt. Second, some farms will not be able to afford for higher wage or mechanization. Such financially non-viable farms need to go for enterprise transformation for increasing productivity. This will increase the efficiency of the farm sector.

5. Land Mobility

There are two issues in land mobility. First, moving land from low productive enterprises to high productive enterprises is experienced for centuries. The speed is gaining in recent years. Some examples of such movements of land (generally referred as change in cropping pattern) are as follows.
  - maize/millet farming upland is getting shifted to summer vegetables, ginger and cardamom
  - fallow lands during winter is moved to winter vegetables
  - pasture lands in hills are shifter to tea, coffee and fruits

6. Technology Transfer in Agribusiness

The TRIPS measure is expected to accelerate the pace of generation of agricultural technology. However, the royalty rights of the inventors will make the technology costlier to the users. On the other hand, the agribusiness can make better choice of technology for adoption and it will increase the productive efficiency and net gain of the agribusiness.

Increase in the price of agricultural products due to reduction in the farm subsidies in developed countries will increase the demand of agricultural products from developing countries and is expected to facilitate investment in agriculture in LDCs. It ultimately will help in the modernization of agriculture sector.

7. Service Sector Openings

Nepal has opened some services to foreign investment with some conditions like compulsory incorporation of certain portion of equity to domestic investors, and employment of local staff except a certain fraction of high level experts and managers. Among the services opened, those directly concerned with the agribusiness are (a) veterinary services, (b) research and development services and (c) technical testing and analysis services. Opening of these services is expected to attract foreign direct investment in such agribusiness. In addition, availability of the better services will help domestic agribusinesses to expand. It will also help promote the product quality for export.

8. Effects of Policy Changes Abroad

Reductions in the domestic and export subsidies on agriculture in developed and developing counties is expected to increase the international prices of food items. In fact the increase in food prices will encourage the private investment in agricultural sector to increase its productivity.

Conclusions

The major provisions of WTO relating to the agribusiness are in the Agreement on Agriculture, SPS/TBT agreements and TRIPS agreements. Other agreements of WTO affect the agribusiness indirectly. Several provisions of these agreements can be used to support agricultural production, marketing and trade. For this purpose, we need to revise our domestic policies in standards setting and certification, increasing the production scale and making our resources mobile.

Nepal is concerned with the food security and safeguarding rural employment, for which we need some flexibility under the provisions for domestic support. We are also questioning the extremely high subsidies and tariff walls even now being maintained by the developed countries, although they are committed to reduction of both under the Uruguay round. We are seeking better market access for our agricultural products for integration to multilateral trading system.

Because of the large dependency on agriculture for employment, even minor changes in agricultural employment opportunities, commonly prices or trade conditions can have major socio-economic ramifications in Nepal. To comply with the principles of WTO without compromising our development needs and livelihood of the farmers we need some additional facilities like
  - Maximum improvement of opportunities and terms of access (like duty free quota free access to the markets in developed countries) for agricultural products of our production potential
  - Meaningful and practical special and differential treatment to LDCs to enable them to take appropriate domestic policy measures to address growth and development needs in agriculture; and
  - In the meantime, it is absolutely necessary to protect the resource poor subsistence farmers from surges of cheap subsidized imports.

## Trade agreements

The Nagoya protocol relates to Preferential Trade Agreements (PTAs), which include provisions relating to access to genetic resources or to the sharing of the benefits that arise out of their utilization.

- PTA is a trading bloc that gives preferential access to certain products from the participating countries. This is done by reducing tariff but not by abolishing them completely. A PTA can be established through a trade pact. It is the first stage of economic integration. The line between a PTA and a FTA may be blurred, as almost any PTA has a main goal of becoming a FTA in accordance with the General Agreement on Tariffs and Trade.
- These tariff preference have created numerous departures from the normal trade relations principle, that WTO members should apply the same tariff to imports from other WTO members.
- With the recent multiplication of bilateral PTAs and the emergence of Mega-PTAs (wide regional trade agreements such as the Transatlantic Trade and Investment Partnership; TTIP) or Trans Pacific Partnership (TPP)), a global trade system exclusively managed within the framework of the WTO now seems unrealistic and the interactions between trade systems have to be taken into account. The increased complexity of the international trade system generated by the multiplication of PTAs should be taken into account in the study of the choice of for a used by countries or regions to promote their trade relations and environmental agenda.

- A free trade area is basically a preferential trade area with increased depth and scope of tariffs reduction. All free trade areas, customs unions, common markets, economic unions, customs and monetary unions and economic and monetary unions are considered advanced forms of a PTA, but these are not listed below. 

Multilateral

- Economic Cooperation Organization (ECO) (1992)
- Generalized System of Preferences
- Global System of Trade Preferences among Developing Countries (GSTP) (1989)
- Latin American Integration Association (LAIA/ALADI) (1981)[3]
- Melanesian Spearhead Group (MSG) (1994)
- Protocol on Trade Negotiations (PTN) (1973)
- South Pacific Regional Trade and Economic Cooperation Agreement (SPARTECA) (1981)[4]

Bilateral

Several hundred bilateral PTAs have been signed since the early 20th century. The TREND project of the Canada Research Chair in International Political Economy lists around 700 trade agreements, the vast majority of which are bilateral.

- European Union – ACP countries, formerly via the trade aspects of the Cotonou Agreement, later via Everything But Arms (EBA) agreements
- India – Afghanistan (2003)
- India – Mauritius
- India – Nepal (2009)
- India – Chile (2007)
- India – MERCOSUR (2009)
- ASEAN – PR China (2005)
- Laos – Thailand (1991)

## Most favoured nation (MFN) 

It is a status or level of treatment accorded by one state to another in international trade. The term means the country which is the recipient of this treatment must nominally receive equal trade advantages as the "most favoured nation" by the country granting such treatment (trade advantages include low tariffs or high import quotas). In effect, a country that has been accorded MFN status may not be treated less advantageously than any other country with MFN status by the promising country. There is a debate in legal circles whether MFN clauses in bilateral investment treaties include only substantive rules or also procedural protections. The members of the World Trade Organization (WTO) agree to accord MFN status to each other. Exceptions allow for preferential treatment of developing countries, regional free trade areas and customs unions.

Trade experts consider MFN clauses to have the following benefits:

- Increases trade creation and decreases trade diversion. A country that grants MFN on imports will have its imports provided by the most efficient supplier if the most efficient supplier is within the group of MFN. Otherwise, that is, if the most efficient producer is outside the group of MFN and additionally, is charged higher rates of tariffs, then it is possible that trade would merely be diverted from this most efficient producer to a less efficient producer within the group of MFN (or with a tariff rate of 0). This leads to economic costs for the importing country, which can outweigh the gains from free trade.
- MFN allows smaller countries, in particular, to participate in the advantages that larger countries often grant to each other, whereas on their own, smaller countries would often not be powerful enough to negotiate such advantages by themselves.
- Granting MFN has domestic benefits: having one set of tariffs for all countries simplifies the rules and makes them more transparent. Theoretically, if all countries in the world confer MFN status to each other, there will be no need to establish complex and administratively costly rules of origin to determine which country a product (that may contain parts from all over the world) must be attributed to for customs purposes. However, if at least one nation lies outside the MFN alliance, then customs cannot be done away with.
- MFN restrains domestic special interests from obtaining protectionist measures. For example, butter producers in country A may not be able to lobby for high tariffs on butter to prevent cheap imports from developing country B, because, as the higher tariffs would apply to every country, the interests of A's principal ally C might get impaired.
- As MFN clauses promote non-discrimination among countries, they also tend to promote the objective of free trade in general. 

MFN: A case of India
  
As per the obligation under the World Trade Organization (WTO), the member countries of WTO shall extend Most Favored Nation (MFN) status to each other automatically, unless otherwise specified in the agreement or schedule notified to the WTO by the member country. Pursuant to this Provision, in case of goods, India has extended MFN status to member countries of WTO. As regards SAARC countries, Bangladesh, Maldives, Nepal, Pakistan and Sri Lanka are members of WTO and except the Islamic Republic of Pakistan, these countries have extended MFN status to India. India has extended MFN status to all these SAARC countries including Pakistan. So far as exception to MFN status, if any, in services is concerned, each member country has indicated the same in the schedule of commitments in services notified to WTO. The mfn status was finally withdrawn for pakistan on 15 February 2019 in response to the Pulwama attack.

## BIMSTEC

## Sustainable development goals: Policy background, challanges and progress in Nepal

Nepal's social and political progress has been highly progressive. Economic growth remained sluggish but picking up now. Nepal's natural vulnerabilities, from earthquakes to climate change, lie unmitigated. Building on the gains so far, the challenge for Nepal is to swiftly complete the unfinished agenda of the Millennium Development Goals (MDGs), and embrace a much more ambitious aspiration of fulfilling the SDGs. Furthermore, Nepal expects to become a vibrant middle income country by 2030. However, the country is resource constrained, and it needs to forge a diverse alliance for SDGs. 

Policy and Institutional Context

The goal of leaving no one behind fits well with the inclusive political order that Nepal has been building. The new Constitution (2015) aspires to create a prosperous, egalitarian and pluralistic society, and serves as the overarching guide to all development policies, plans and programs. The current (14th) periodic plan (2016/17-2018/19), and other sectoral plans, policies and their targets are being aligned with SDGs. specific SDGs codes are assigned for all national programs in the national budget. Three high-level committees have been formed to help implement SDGs. A steering committee is chaired by the Prime Minister; a coordination committee is chaired by the Vice Chairman of the National Planning Commission (NPC) and nine thematic committees are headed by NPC Members. The membership of the coordination and working committees is broadly representative of the public and private sectors, as well as civil society and development partners. 

National Targets and Progress of Selected SDGs

Nepal was probably one of the first countries to produce a SDG baseline study in 2015, before the formal adoption of the SDGs. Nepal has halved extreme poverty (SDG 1) in the past 15 years, and is on track to bring it d0wn to less than 5 percent by 2030. SDG 2 targets include the reduction in the prevalence of undernourishment to 3 percent and prevalence of underweight children under five years of age to 5 percent by 2030. Similarly, SDG 3 targets include reducing the maternal mortality rate to less than 70 per 100,000 live births by 2030. Other targets include the virtual elimination of the prevalence of HIV, TB, Malaria, other tropical diseases, and water borne diseases. In Nepal today, there is gender parity at all levels of education. The targets for SDG 5 includes the elimination of wage discrimination, physical/sexual violence, and all harmful social practices, such as child marriages. Nepal expects women to fill 40 percent of all elected seats in local governments, and at least one-third of the seats in the national parliament. In the civil service, women in public decision-making positions will have increased four-fold of total employees by 2030.

The targets for SDG 9 are to increase road density to 1.5 km per square km and paved road density to 0.25 km per square km, and to connect all districts, municipalities and village councils to the national road network. In industries, the target by 2030 is to increase the share of employment to 25 percent; within the subset of manufacturing, employment is to reach 13 percent. SDG 17, on the means of implementation, expects adherence by all stakeholders, from resource mobilization and capacity development to shared responsibility and accountability. Nepal's progress in revenue mobilization is impressive, but also vulnerable to likely swings in the large volumes of inward remittances which bolster import-based taxation. The aim is to increase the share of revenue from about 22 percent today to 30 percent of Gross Domestic Product (GDP) by 2030. Domestic expenditures financed by revenue is estimated to reach 80 percent. For meeting the private sector investment financing gap, foreign direct investment (inward stock) is expected to increase to 20 percent of GDP in 2030 from less than 3 percent in 2015.

Challenges in SDGs Implementation

SDGs are interlinked, indivisible, and ambitious posing major implementation challenges in a low-income country like Nepal, which has limited resources. As the country embarks on implementing a new federal structure of governance, a prominent challenge will be to quickly mainstream SDGs into the provincial and local level planning and budgeting systems. Weak database and lack of availability of disaggregated data by sex, age, social groups, disability status, geography, income and sub-national level will hinder monitoring of progress. In addition to the realignment of policies, financing challenges will loom large, particularly to trigger and sustain job-creating economic growth, enhance the quality of social service provisioning and to invest adequately to reduce risks from disasters.

Way Forward

Positive lessons learned from the MDGs era will need to be scaled up. For example, in health, education, water and sanitation, the Sectorwide Approach yielded better results because of coordinated resource mobilization. Similarly, the triangular partnership between the government, private sector and development partners proved quite effective in some areas, but will need to be augmented significantly especially to spur reforms that attract substantial private capital and entrepreneurship. Nepal will need to constantly update its targets and indicators contained in sectoral master plans, medium term plans and strategies. Many SDG goals and indicators do not yet have a quantitative baseline. This needs an urgent redress, and the data that do exist need further disaggregation, particularly based on new political jurisdictions. Monitoring SDGs progress within the existing institutional framework of data generation and management needs an overhaul. Above all, SDGs are interconnected and the achievement of one goal has a synergetic effect on others. These integrated challenge needs a matching response in terms of fiscal, managerial and institutional capacities. 

Source:

\url{https://sustainabledevelopment.un.org/content/documents/15896Nepal_Main_Message_HLPF_2017.pdf}

For main document, refer to: \url{https://www.npc.gov.np/images/category/Sustainable_Devlopment_Agenda_Eng.pdf}
