
# Plans and policies

## General

- MOA has issued an "Implementation Guidelines on PPS for Agriculture Development, 2055 (1998)" to ensure common framework for implementation of pocket package strategy in order to carry out APP at field level. The guidelines have presented the pocket package program under two categories namely Crop production and Livestock production.
- Agriculture fair is based on the concept of "Seeing is believing".
- Department of Agriculture first broadcasted improved production technology in agriculture through radio for the first time in 2016 B.S.
- Agriculture program broadcast over radio was stopped for a few years and later resumed back in 2023 Mangsir 20.
- In group approach of extension is used in convincing a farmer to use a technology when s/he has been made aware of it through mass media approach.

## Periodic planning

- The nineth plan considered poverty reduction and other development goals. The main target of this plan was to reduce the headcount poverty in the headcount poverty index from as high as 42% to 32%, 23%, 15% and 10 by 2002, 2007, 2012 and 2017, respectively. However, it could not be realized as the poverty rate in 2011 was 25%. 
- The tenth plan (2002-2007) is considered as a comprehensive plan designed for the reduction of poverty to a desired level. Designed as the poverty reduction strategy paper (PRSP), the tenth plan incorporated the involvement of the private sector in the market economy with the facilitation from the government side. Because of the bad political situation and existing conflict inside the country, reduction of poverty was a daunting task and this was reflected in the level of poverty that country was facing by the end of this plan.
- Instead of eleventh plan, interim plan for 3 years was launched from 2007/08-2009/10. The main objective of this plan was to generate an experience of a direct feeling of change in the lives of the general public by supporting in the establishment of peace and reducing the existing unemployment, poverty and inequality. This plan was designed in a critical state of transition where the country was formulating a new constitution to restore peace and reconstruction and reintegration among people suffering from the conflict.
- The twelve three year plans (2010/11-2012/13) has kept poverty alleviation as its major agenda and inclusive employment generation and equitable economic growth are considered two important pillars for realizing poverty alleviation. The purpose of this plan is to incorporate every community from all around the country to make sure that every underprivilaged and marginalized group is included. This plan has mobilized volunteers through National Development Volunteer Services (NDVS). NDVS has been implemented by district development committees. The purpose of this program is to mobilize volunteers as moderators in disadvantaged communities such as poor, ethnic, Dalit communities so that they will help them as facilitator in education, health, infrastructure, social mobilization and other areas.

## National tea policy, 2000

- GoN approved and implemented National Tea Policy, 2000 as per intention of National Tea and Coffee Development Board Act, 1992 for:
  - Income generation (enhancing employment, earning foreign currency)
  - Participation in private sector in production, processing and commercial transaction through systematic and sustainable utilization of resources in country.
- Working policies:
  A. Production and processing
    - Banks to provide priority credit
    - Upto 80% loan of total project cost to registered tea plantation industry
    - 7 years grace for orthodox tea and 5 years for green tea on loan in hills and terai respectively.
    - Interest on loan not capitalized in grace period
    - Income tax not levied within grace period
    - Interest and principal to be fully paid up within 10 years from the end of grace period
    - Exemption of 75% on land registration fee
    - Land revenue exemption
  B. Market and trade promotion
  C. Institutional arrangement
  D. Manpower development
  E. Development and promotion of auxillary industries

## 14th plan (FY: 2073/74-2075/76)

- Recently proposed projects: 13
- 21.6% of the population is below poverty line by the end of 13th plan

```{r forteenth-periodic-plan}
read_csv("./data/periodic_plans.csv", skip = 1) %>% 
  knitr::kable(booktabs = TRUE, caption = "Goals and achievements of 13th periodic plan (2073/74-75/76) for selected indicators") %>% 
  kableExtra::kable_styling(latex_options = "striped")
```

- Gross national income in 13th periodic plan was expected to rise by 6.0 percentage, however by 2070/71 it was 5.72%, in 2071.72 2.32% and in 2072/73 it remained 0.77%. Hence resulting in average economic growth of 2.92%.
- There was a projection for an increase in 4.5% in agriculture sector, however, in years 2070/71, 71/72 and 72/73 respectively, 4.55%, 0.81% and 1.33% growth were achived. Hence resulting in average growth of 2.22%
  - Food grain production was projected to reach 1,08,81,000 mt annually. However at the second year of the plan only 92,66,000 mt were realized.
  - There was an estimation of 12,60,000 mt production of fruits. But only 11,86,000 mt were produced.
  - There was an estimation of 36,00,000 mt production of vegetables. However, 36,23,000 mt were produced of it, surpassing the set target.




## National agricultural policy, 2004

Vision

- To bring about an improvement in the standard of living through a sustainable agricultural development to be achived by transforming the current subsistence oriented farming system into a commercial and competative farming system.

Objectives

Broad

To ensure food security and poverty alleviaion by achieving a high and sustainable economic growth through commercial and competative farming system:

Specific

- Agricultural production and productivity shall be increased
- The bases of a commercial and competative farming system shall be developed and made competative in regional and world markets
- Natural resources, as well as the environment and biodiversity shall be conserved, promoted and properly utilized

Policies

Objective 1

- Increasing of agricultural production and productivity
  1. Utilize local potentialities, comparative advantage and special opportunities; Ensure development, extension and utilization of agricultural technology; Commercialization and diversification of agriculture
  2. Scientific land use system
  3. Irrigation, agricultural roads, rural electrification and appropriate agriculture technology development and epansion
  4. Pocket development of HVAP
  5. Entrust local body for formulating, implementing and monitoring agricultural plans suitable to local needs and priorities. Conditional basis of grant.
  6. Multi-district projets to promote agricultural produciton and enterprises operated and suppored at implementation level through central departments and directorates.
  7. Farmer's group appraoch for on-site extension service
    - Agriculture and frest colleges to extend agriculture technologies through package programs
    - IT and mass communication development
  8. National agricultural resource centres for high quality inputs
    - based on development regions and geo-graphical subdivisions
    - NARC to be converted to integrated centre
  9. Participatory and competative agricultral research and development system promotion
    - Technology exchange encouraged between organizations
  10. Private and foreign investment in agriculture research and development encouraged
  11. Input supply monitoring and regulating guarenteed
  12. Surveillance system to assess impact of excessive rains, droughts and calamities.
  13. Emphasis on farmer's training programs
  14. Linkage of agricultural production and enterprises' return to ensure agriculture credit flow.
  15. Establishment of agriculture and forestry university. Quality of agriculture human resource to be increased by arranging cooperation and exchange of technicians and experts among universities/colleges, agriculture research centre and national agriculture resource center.
  16. System development for collecting, analyzing and projecting data required for formulation of plans, determining policies and carrying out monitoring and evaluation of activities related to agriculture sector shall be strengthened.
  17. Women's participation in all fields of agriculture upto 50%
  18. Resource poor farmers (with less than 4 hectares of land) will be identified and classified.

Objective 2

- Special facilities for target groups: For farmer's having less than 0.5 hectares and unirrigated lands, dalit and utpidit classes of farmers and other marginal farmers
  1. Opportunity of gaining access to lands
    - Legal ceilings on landholdings and exemptions
    - Progressive taxation
    - Legal provision for contractual farm lands.
  2. Land bank establishment
    - Local body as information provider
    - Concessional loans
  3. Forest upgradation and other land will be handed to the traget communities under lease.
  4. Special facilities to target groups to build and install infrastructures: small irrigation (pedal pumps, power pumps, sprinklers, drips and water harvesting ponds)
  5. Utilization of means to increase production and income to mitigate food deficit. Network for food mobilization development.
  6. Government services based on priority from food security viewpoint.
  7. Food safety nets development for farmers with less than 0.5 hectares of land.
  
Objective 3

- Development of commercial and competative farming system
  1. Large production pockets, priority for comparative advantage products. Technology and technical sevices as well as infrastructure mobilized in integrated manner.
  2. Local production of food grains will be encouraged under food supply programme
  3. Double track management system will be adopted in government farms and centres
  4. Livestock insurance programmes extension. Poultry insurance and HVAP and seed crops insurance.
  5. Organic farming will be encouraged; certification support
  6. Production of hybrid seeds and improved seeds will be encouraged, GMOs will be regulated.
  7. Traditional, local original agriculture products and technologies will be registered and promoted.
  8. Agriculture training classification
    - Capacity improvement training for agriculture workers and farmers
    - Enterprise promotion training
  9. Training educated but unemployed youths
  10. Local production, sale and distribution of improved agriculture resource inputs (seeds, plants, saplings, breeds, fingerlings, etc.) and manure, insecticides, pesticides, regulated and quality control.
    - Private agriculture lab services will be regulated and accreditated
    - High quality product processing facilites and services will be offered
  11. Agriculture and livestock quarentine services will be systematized and strengthened in order to ensure the production of high quality agriculture products and raise their credibility in local and external markets.
  12. Participation of local bodies will be strengthened in determining, controlling, certifying, and regulating standards of food stuffs.
  13. Regulatory services will be upgraded as per international treaties and agreements and the national requirements.
  14. Promotion of cooperative based agriculture industries and enterprises
  15. Mobilize agriculture industry and enterprise promotion board
    - To analyze and provide outlet to complaints and suggestions
  16. Commodity and subject specific policies equipped with incentives developed in order to attract cooperative and private sectors to make investments in commercial production, processing and marketing
  17. Agricultural industry development policy formulation
    - Interlink agriculture research + production + processing industries + internal and external export markets
  18. Free-based agricultural technology extension services in areas of commercial agricultural production
  19. Private sectors engaged to operate suitable farms/centers through contract lease agreements.
  20. Developing and extending market information system and disseminating such information shall be carried out in private + cooperative + local bodies partnership
  21. Collection centres close to production centres (Hat bazzars, well equipped wholesale and seasonal markets as well as private cooperatives)
  22. Agriculture enterprise promotion board to provide capital and incentives/facilities to industries and enterpreneurs for:
    - import substitution
    - export promotion
  23. Cooperative promotion of potential farmer groups and enterprenuers by mobilizing and promoting local small capital and other resources
    - Rural cooperatives as local delivery points
  
Objective 4

- Conservation, promotion and utilization of natural resources and environment
  1. Impact minimization of agro-chemicals
  2. Organic fertilizer promotion
  3. Gene banks and insitu conservation. Participatory biodiversity parks
  4. Biodiversity conservation, promotion and utilization to improve condition of degraded forests and natural reservoirs.
  5. Conservation oriented farming system
    - Watershed management through local participation
    - Soil erosion control through local participation
  6. Checking cultivable land fragmentation and ensure scientific mangement
  
Objective 5

- Implementation and monitoring arrangement
  1. Participatory involvement of stakeholders in process of formulating, monitoring and evaluating plans connected with agriculture sector from local to central level.
  2. Role of national agricultural development board (Central agriculture development committee and Regional agriculture development committee) devolution for policy implementation to local bodies (VDCs and DDCs) to ensure formulation, implementation, monitoring and evaluation of plans in accordance to LSGA, to:
    - DADC (District agriculture development committee) with technical feedbacks to CADC and RADC
    - ADC (Village level ADCs) with technical feedbacks to CADC and RADC.
  3. Concerned ministries shall implement this policy on their related sectors
    - NADC to monitor the implementation on national level
    - Strategies, programs and responsible bodies of related matters may be implemented by concerned ministries upon approval.
    
