# Major acts and regulations

## The National Civil (Code) Act, 2017 (2074)

Whereas, it is expedient to make timely the civil provisions contained in the country code and other laws, by also amending and consolidating such provisions, in order to maintain morality, decency, etiquette and convenience as well as economic interest of the public by maintaining law and order in the country and maintain harmonious relationship between various castes, races and communities, by making just provisions in the economic, social and cultural field;

Now, therefore, the Legislature-Parliament under clause (1) of Article 296 of the consitution of Nepal has enacted this act. 

- There are a total of 721 sections.

Part-1 Preliminary

Chapter-1 Preliminary statements

Chapter-2 General principles of civil law

- Principles and provisions applicable generally
- Ignorance of law not to be excused
- Act against public interest not to be carried out
- Act contrary to law to be invalid
- A wrongdoer to bear liability for loss or damage
- Act causing nuisance to other not to be done
- Not to enjoy benefit of wrong
- Act against interest to be invalid
- Personality to be recognized
- Good neighborhood to be maintained
- Not to be relieved from civil liability
- Custom or tradition contrary to law not to be recognized
- Applicable to foreigners as well

Chapter-3 Provisions relating to civil rights

- To be equal before law
- Discrimination not to be made
- Discrimination not to be deemed where special provision is made
- Guarantee of freedoms and rights
- Right to privacy deemed to be violated
- Right to make contract
- No taxation except in accordance with law
- No to employ in work against will
- Property not to be acquired, requisitioned, auctioned or forfeited
- Complaint may be filed
- Compensation to be awarded
- Compensation for filing false complaint
- Statute of limitation

Part-2 Law relating to persons

Chapter-1 Provisions relating to natural persons

Chapter-2 Provisions relating to legal persons

Chapter-3 Provisions relating to bankruptcy of natural persons

Part-3 Family law

Chapter-1 Provisions relating to marriage

Chapter-2 Provisions relating to consequence of marriage

Chapter-3 Provisions relating to divorce

Chapter-4 Provisions relating to relationship of parents and children

Chapter-5 Provisions relating to maternal and paternal authority

Chapter-6 Provisions relating to guardianship

Chapter-7 Provisions relating to curatorship

Chapter-8 Provisions relating to adoption

Chapter-9 Provisions relating to inter-country adoption

Chapter-10 Provisions relating to partition

Chapter-11 Provisions relating to succession

Part-4 Law relating to property

Chapter-1 General provisions relating to property

Chapter-2 Provisions relating to ownership and possession

Chapter-3 Provisions relating to use of property

Chapter-4 Provisions relating to cultivation, possession and registration of land

Chapter-5 Provision relating to government, public and community property

Chapter-6 Provision relating to trusts

Chapter-7 Provision relating usfruct

Chapter-8 Provisions relating to servitudes

Chapter-9 Provisions relating to house rent

Chapter-10 Provisions relating to gift and donation

Chapter-11 Provisions relating to transfer and acquisition of property

Chapter-12 Provisions relating to mortgage of immovable property

Chapter-13 Provisions relating to registration of deeds

Chapter-14 Provisions relating to transactions

Part-5 Provision relating to contracts and liabilities

Chapter-1 Provisions relating to obligations

Chapter-2 Provisions relating to formation of contracts

Chapter-3 Validity of contracts

Chapter-4 Provision relating to performance of contracts

Chapter-5 Provision relating to breach of contract and remedies

Chapter-6 Provision relating to contracts of sales of goods

Chapter-7 Provisions relating to contracts of guarantee

Chapter-8 Provisions relating to contracts of bailment

Chapter-9 Provisions relating to contracts of pledge or deposit

Chapter-10 Provisions relating to contracts of agency

Chapter-11 Provisions relating to contracts of carriage of goods

Chapter-12 Provisions relating to contracts of lease

Chapter-13 Provisions relating to Hire-purchase contracts

Chapter-14 Provisions relating to wages

Chapter-15 Provisions relating to indirect or quasi contracts

Chapter-16 Provisions relating to unjust enrichment

Chapter-17 Provisions relating to torts

Chapter-18 Provisions relating to liability for defective products

Part-6 Provisions relating to private international law

## Civil service act, 2049

Date of authentification and publication: 2050-02-04 (May 17, 1993)

1. Nepal health services act, 2053 (1997)
2. Civil service act (First amendment), 2055 (1998)
3. Some Nepal acts amendment act, 2057 (2000)
4. Parliament secreteriat act, 2058 (2001)
5. Civil service act (Second amendment), 2064 (2007)
6. Federal reinforcement and some national act amending acts, 2066
7. Civil service act (Third amendment), 2070
8. Civil service act (Forth amendment), 2072

Chapter-1 Preliminary

Chapter-2 Constitution of civil services

1. Relating to central employee administration agency
2. Organization of civil services
  - Nepal engineering service
  - Nepal agricultural service
  - (Nepal judicial service)
  - Nepal foreign service
  - Nepal audit service
  - Nepal forestry service
  - Nepal miscellenaous service
  - Nepal education service

3. Classes of civil service
  - Gazetted: Special, first, second, third
  - Non-gazetted: First, second, third, forth, fifth

Chapter-3 Fulfilment of vacancy of civil service

Chapter-4 Transfer and promotion

Chapter-5 Salary, allowance, dashain expenses and other facilities

Chapter-6 Retirement, gratuity and pension

Chapter-7 Conduct

- Timeliness/punctuality and regularity
- Discipline and obedience
- Political impact should not be made
- Non participiation in politics
- Government should not be protested against
- Publication/reporting on government activities is prohibited
- Should not accept grant, present and donations
- Cannot establish company and/or business enterprise
- Cannot participate in election
- Cannot parttake in other employment or services
- Cannot seek permit for permanent residence
- Cannot parttake in demonstration and strikes
- Cannot partake in any activities that refrain from government carrying out activities
- Cannot represent trade union
- Provisions relating to organization of a trade union
- Should disclose his/her property details
- Cannot engage in torturing and extortion
- Other conduct
- Conduct towards public
- May be issued warning

Chapter-8 Service security

Chapter-9 Punishment and appeal

Chapter-10 Miscellaneous
