# General knowledge elaborate

## International affairs

### United Nations and International Organizations

\begin{questions}

\question World conference on Women, 1975

\begin{solution}

The conference was held between 19 June and 2 July 1975 in Mexico City, Mexico. It was the first international conference held by the United Nations to focus solely on women's issues and marked a turning point in policy directives. After this meeting, women were viewed as part of the process to develop and implement policy, rather than recipients of assistance. The conference was one of the events established for International Women's Year and led to the creation of both the United Nations Decade for Women and follow-up conferences to evaluate the progress that had been made in eliminating discrimination against women and their equality. Two documents were adopted from the conference proceedings, the World Plan of Action which had specific targets for nations to implement for women's improvement and the Declaration of Mexico on the Equality of Women and Their Contribution to Development and Peace, which discussed how nations foreign policy actions impacted women. It also led to the establishment of the International Research and Training Institute for the Advancement of Women to track improvements and continuing issues and the United Nations Development Fund for Women to provide funding for developmental programs. The conference marked the first time that the parallel Tribune meeting was successful in submitting input to the official meeting and became a catalyst for women's groups to form throughout the world.

\end{solution}

\question United Nations Commission on Status of Women

\begin{solution}

The Commission on the Status of Women (CSW or UNCSW) is a functional commission of the United Nations Economic and Social Council (ECOSOC), one of the main UN organs within the United Nations. CSW has been described as the UN organ promoting gender equality and the empowerment of women. Every year, representatives of Member States gather at United Nations Headquarters in New York to evaluate progress on gender equality, identify challenges, set global standards and formulate concrete policies to promote gender equality and advancement of women worldwide. In April 2017, ECOSOC elected 13 new members to CSW for a four-year term 2018–2022. One of the new members is Saudi Arabia, which has been criticised for its treatment of women.

The commission was formed on 21 June 1946 and is headquartered in NY, USA.

\end{solution}

\end{questions}

## National affairs

\begin{questions}

\question Describe the 15th plan approach paper:
% \makeemptybox{1.5in} % use this to provide a box in question
\begin{solution}
The 15th plan approach paper is a piece of shit.
\end{solution}

\question Write about BIMSTEC.

\end{questions}

\begin{questions}

\question Discuss about the major impacts on people's lifestyle due to the geographic conditions of Nepal.

% \makeemptybox{1.5in} % use this to provide a box in question
\begin{solution}

Physical geography is the study of natural features and phenomena on the planet's surface and our interactions with them. These features include vegetation, climate, the local water cycle, and land formations. Geography doesn't just determine whether humans can live in a certain area or not, it also determines people's lifestyles, as they adapt to the available food and climate patterns. As humans have migrated across the planet, they have had to adapt to all the changing conditions they were exposed to. At first, particular cultures develop because of the physical landscape. Over time, those cultures exert their own influence on the landscape around them.

Life cannot be the same in arctic regions as in the tropics; nor upon deserts of drifting sand as upon the grassy steppes which afford the natural home for wandering shepherds and their herds; nor upon the seacoast with its fisheries and commerce as among the mountains with their forests and mines. But it is not alone the extreme and unusual manifestations of nature which affect the life of man. So relatively inconspicuous a fact as the presence of a creature adapted to become a beast of burden might enable one people to grow into a triumphant race, contributors to a dominant civilization, and the absence of such a creature might condemn another race to backwardness and final extinction.

Geography, in overall, affects socio-economic lifestyle of people in following ways:

\begin{enumerate}
\item Geographic conditions determine the size of populations.
\item The economic occupations of a people are determined by their geographic environment.
\item Stagnation or progression are conditioned largely by geographic surroundings.
\item Lawlessness is the natural consequence of geographic inaccessibility
\item The form of government is affected by geographic conditions
\item Tastes and social and domestic customs are influenced by geographic conditions: Football is out of place in the tropics, and ice-skating is impossible. Athletic sports are indigenous to cool climates, and are the objects of amazement to inhabitants of torrid regions. The long evenings of the northern winter call into being suitable pastimes.
\item Ethical differences are largely influenced by geographic environment
\item Mythologies and religions are influenced by geographic environment: What the nature-myths of a people shall be depends in part upon what aspects of nature in their neighborhood are most impressive, whether they live by the sea, upon the banks of a great river, among the mountains, in the depths of the forest, or on a plain where the overarching sky with sun and stars chiefly command the gaze. The existing form of earthly power and authority tends to shape man's notion of divine rule.
\item Geographic conditions affect the moods and psychic tendencies of a people: General vital processes, upon which the action of the brain and nervous system depends, affected by conditions of heat, light, and moisture, but the nerves themselves are directly stimulated or depressed. To this cause has been ascribed the fact that the cradles of civilization have been found in dry regions like the Egyptian oasis in the desert, and the plains of Iran and of Central America. Not only does climate affect the permanent tendencies of races, but passing changes of the seasons affect the moods of men. Alternations of the seasons give variety to life and stimulation to the imagination.
\item Routes followed by migration, war and commerce have been marked out by geographic highways, and these have been the great distributers of human populations, customs, and commodities.
\end{enumerate}

\textbf{Land Formation}
Land formation is the physical shape of an area and the several processes that help form that shape. One process that makes a big impact is plate tectonics: the movements of crustal plates on the Earth's surface. These plates are constantly sliding past and colliding into one another. Plate movements can affect the availability of water by disrupting rivers and they disturb land formations that humans have settled on, like an earthquake ravaging a major city. Animals hunted by humans for food can be displaced as well, forcing people to move to another area to survive. Thronging cities are found at points of geographical advantage.

\textbf{Soil}
Soil carries out several functions that profoundly impact human activity. Soil recycles nutrients, regulates water quality, sustains life, and provides structural support for buildings. Without healthy soil, a previously fertile area turns into a desert, making it difficult to sustain vegetation and prevent massive loss of life. Soil doesn't just provide for agriculture, it also helps modern life because it contains minerals. These minerals include ore, which contains metals used for electronics and peat used for heating. People may move temporarily to more fertile areas to provide for their families, especially if they live in poorer countries like Kenya.

\textbf{Water Access}
Water is purified by evaporation into the atmosphere, from where it falls back to land and the oceans through rainfall. All humans need water to survive, and depend on regular rainfall and other sources of clean water for drinking and agriculture. Water is found above, on, and under the ground. People tend to settle near bodies of water such as oceans, rivers, and lakes for easy access to large amounts of water. For example, nearly the entire population of Egypt is concentrated around the delta of the Nile River because the rest of the country is an arid desert.

\textbf{Climate}
Climate is the pattern of variation in temperature, humidity, and pressure over an area for long periods of time. There are several types of climates: tropical with high rainfall and temperatures over 18 degrees Celsius, dry, subtropical with mild winters, continental with cold winters, and polar. People have not only adjusted their clothing and housing based on temperature, but their bodies have also adapted. The Masai people have longer limbs that help them lose body heat in the warm climate of East Africa. Arctic-dwelling Inuit adapted by storing more body fat and increasing metabolic rates.
\end{solution}

\question What is the current status of languages used in Nepal according to Language Commission ?

\begin{solution}

Six new languages have been added to the list of 123 languages spoken in Nepal. These newly discovered one include:

Kanchanpur: Rana Tharu,
Manang: Nar Phu,
Gorkha: Chum (Syaar) and Nubri (Larke),
Dolpa: Poike, and
Mustang: Serake (Seke)

Current Chairman of the Language Commission Dr. Lava Dev Awasthi submitted the annual report to President in her Office at SheetalNiwas. Prior to it, the national census 2068 had enlisted 123 languages as the languages spoken in Nepal. The list then had grouped 68 languages of the Sino-Tibetian family, 48 languages of Indo-European family and one each of Dravidian family (Uraon-Kudukh) and Austroasiatic family (Santhali) and a language with anonymous identity (Kusunda) as in different language families.

There are 19 languages with more than 100,000 speakers. This consists of 95.91\% of the total population. Among other languages spoken by the rest of the population 24 languages like Dura, Kusunda, Tilunga have a small number of speakers which has ultimately led them on the verge of extinction.

Among others at stake are: Pali, Sankskrit and Bhot.

The report blames excessive craze for English, colonial mindset and the illusions generated by the global market substituting the local one for endangering glorious linguistic diversity and multicultural lifestyle of Nepal.

To facilitate its activities the commission has prepared the list of experts of 101 languages.

The Commission has suggested to form a High-Level Linguistic Policy Determination Committee and assign it the task of coordinating and facilitating various activities related to the constitutional and other legal provisions related to language.

\end{solution}

\question What is budget? Describe the weakness of Nepal's budgetary system.

\begin{solution}

National (Government) budget is a document prepared by the government or other political entity presenting its anticipated revenues and proposed spending for coming fincancial year. Nepal's budgeting system is a combination of top-down and bottom-up approach, which brings about a synergy between the national level plans and local level needs; and ensures that the budget fulfills the demands of both the state and the locals.

Normally, the process of budget formulation in Nepal would begin in January and end in July, when the fiscal year starts. However, with the provision of the Constitution of Nepal, 2015, the budget cycle has been moved forward to be presented on the date of 15th Jestha (May 28).

The budget formulation steps can be generalized into four phases:
\begin{enumerate}
\item Preparation
\item Enactment/legislation
\item Execution
\item Auditing
\end{enumerate}

The first step in formulating a budget is forecasting, wherein the sources of revenues and tentative areas of expenditures are identified. The process of forecasting is led by a Resource Committee (RC), which is chaired by the Vice Chairperson of National Planning Commission (NPC), and includes other members from NPC, members from Ministry of Finance (MoF), Central Bank of Nepal and the Financial Comptroller General Office (FCGO). The RC determines the size of budget by analyzing overall economic situation of the country with the help of macro-economic indicators. Once the forecast has been prepared, it is presented to the budget committee comprising of the members of the NPC and the MoF. The committee, after thourough discussion sets the budget ceiling, which limits the budget expenditure based on sectors and availability of resources. The committee also prepares the working guidelines for budget formulation. Thereafter, each of the line ministries is asked to submit their programs and budget estimates (both capital and recurrent) in accordance to the guidelines and sectoral budget ceilings. The line ministries then forward the guideline along with the budget ceiling and priorities to respective departments and agencies functioning under it, either at the district level or at the central level. Based on the guidelines, these agencies prepare the forthcoming year's programs and budget and send it back to the concerned departments. The departments compile the programs and budget of all agencies under them and submit it to the respective line ministries. Some negotiations can take place between Ministries and the departments before it is vetted and consolidated by the Ministers and forwarded to the MoF and NPC for finalization.

Planning -- Devolved programs are financed by the center but fall under the administrative purview of the District Development Committees (DDC), hence the process of budget formulation is different from top-down budgeting. The NPC sends guidelines to DDCs for district level plans and programs. The guideline is passed down to the VDCs and Municipalities, who hold village/town council meetings to discuss and prepare sector-wise development programs and projects. Interest groups such as the consumer committees, NGOs, political leaders, and citizens are included in these discussions. Their plans are then forwarded to the VDC/municipality where it gets accumulated. Once the VDC scrutinizes and gives a green signal to the plan, it moves up to the District Council which re-examines the budget and forwards it to the DDC. The DDC then hold meetings with district offices and finalizes district budget and priorities, which is then sent to the NPC and the Ministries. While this is the process that should be theoretically followed, it is not necessarily fully operated because of absence of popularly elected offcials. As departments are not given a sectoral budget ceiling, they generally do not take expenditure limitations into account; insted they look at project-specific targets as a guide for the budget.

Enactment -- Once the MoF receives the budget from all line ministries, inter-ministerial meetings are held to vet and finalize the national budget. Similarly, the NPC discusses all the programs submitted by the Ministries, and finalized those programs in consideration of the relevancy, budget allocation, and budget handling capacity of the Ministry. Before the budget is presented in the parliament, the parliamentarians are presented with a draft budget document for them to discuss the sector-wise specifics. The comments and queries that arise during the ministry-specific discussions are discussed in detail until the relevant ministry and parliamentarians are satisfied with the clarifications provided to their queries. The budget is presented by the government only after the ministry level budget discussion ends. If the majority agrees with the budget then it is approved and is presented to the national Parliament in the form of a Budget Speech by the Minister of Finance.

Execution -- It is also called the procedure of releasing budget. The process of fund release starts with the approval of the budget by the parliament. Two further steps are required after the parliamentary approval of the budget:

\begin{itemize}
\item Finalization of work programs consistent with the ratified budget for each spending unit by the respective line Ministries and their approval by NPC
\item The formal delgation (through official notification) of authority to spend by the Secretary of Finance to sectoral Ministries and then to project managers.
\end{itemize}

Immediately after completion of the discussion on the underlying principles and policies, the Finance Ministries puts before the parliament the Vote on Account Bills, which authorizes the government to spend a specified amount in advance. The process of releasing budget is as follows:

\begin{enumerate}
\item Whereas up to one-third of the previous year's expenditure was often released under the advance bill past fiscal years, the government can now advance up to one-third of the budget for core projects, two-third or one-sixth for remote projects and one-sixth for regular and other programs. Subsequent release can follow after the Appropriation bill gets of the Head of the State assent. Budget release will be made on monthly basis. In the past, trimester budget release was in practice. However, the Financial Comptroller General Office (FCGO) has maintained the trimester and lump sum system for subsidies (DDC, VDC, Education, health, Public corporation, Companies), controlled budget (Medical care, gratuities and others).
\item For donor-funded projects, budget will be released on a pre-funding (donors have to put deposit to GoN, treasury in advance) and reimbursement basis (applied for loan-financed projects and to some extent for bilateral donor-financed projects depending upon the agreement.)
\item The system of imprest account established under ADB and WB-financed projects have also been maintained under which the project authority can withdraw directly from the said account.
\end{enumerate}

After the approval of the Appropriation bill, MoF will inform the entire sector ministries on the project details of the approved budget, and send the sources book on foreign aided projects and letter of authority for all expenditures to all ministries, FCGO and Auditor General's Offices (AGO). Line ministries also forward such budget details and authority latter for expenditure through their concerned Department/Project Coordinator Offices (PCO) to the district line agencies with copies to the FCGO and each District Treasury Offices (DTO).

\begin{itemize}
\item The Department/PCO prepares the unit/wise program supported by budgetary details both source-wise and items-wise and forward it to the NPC and line agencies. In that process, the central level projects will be approved by the NPC and the district level projects by the ministries concerned.
\item After the approval of the program as maintained in (a) the Department/PCO make available to each unit under it the program and budgetary detail. Then each project unit and PCO submit the monthly release reports along with copies of the approved program and authority letters giving budgetary details to the nearest DTO.
\end{itemize}

The FCGO and DTO play important role in the budget release process. The DTOs process all request and will release the funds requested to respective agency's bank account. DTO releases the fund upon the receipt of the following documents:

\begin{enumerate}
\item Authority letter from the concerned ministry,
\item Release order to DTO by FCGO,
\item Project/program duly approved by NPC and document in the budget,
\item The FCGO release funds on a monthly basis, provided the above mentioned conditions are fulfilled and the budget requests tally with the sources book,
\item DTO release the fund only after receiving the statement of expenditure of the previous month from the requesting agency,
\item DTO is also empowered to release the donor portion budget on a reimbursement basis, if so provisioned in the sources book,
\item In the case of pre-funding arrangement in the sources book, budget is released to the extent of donor contribution available.
\end{enumerate}

Auditing -- The final phase of budget cycle is auditing. This is the overall responsibility of the Auditor General (AG) to prepare the annual report after accomplishing auditing of all government transaction. The AG presents its annual report to GoN, which is later forwarded to parliament for discussion and implementation.

\end{solution}

\question What are different types of budget? What are the needs and importances of government budget ?

\begin{solution}

A budget can be of three types
\begin{itemize}
\item Balanced budget: when government receipts are equal to the government expenditure.
\item Deficit budget: when government expenditure exceeds government receipts. A deficit can be of 3 types: revenue, fiscal and primary deficit. A budget deficit occurs when an individual, business or government budgets more spending than there is revenue available to pay for the spending, over a specific period of time.
\item Surplus: when government receipts exceed expenditure.
\end{itemize}

Need and importance of a government budget
\begin{enumerate}
\item Planned approach to government's activities
\item Integrated approach to fiscal operations
\item Affecting economic activities
\item Instrument of economics policy
\item Index of government's functioning
\item Public accountability
\item Allocation of resources
\item GDP growth
\item Elimination of poverty
\item Reduce inequality in distribution of income
\item Tax and non-tax receipt
\end{enumerate}

\end{solution}

\question What is good governance ?

\begin{solution}

There are various definitions of the term \textit{good governance}. These definitions are based on normative assumptions about how decisions should be made within organizations and the functioning of formal and informal structures for implementing such decisions. The UN Commission on Human Rights identifies transparency, responsibility, accountability, participation, and responsiveness as key attributes of good governance. By linking good governance specifically to human rights and sustainable development, the UN explicitly recognizes that governance issues are global in nature and consequently require more nuanced and integrated approach. 

The Canadian International Development Agency defines good governance as "the exercise of ower by an organization (or government) in an effective, equitable, honest, transparent, and accountable way". This approach to governance focuses on how organizations are directed, controlled and shown to be acting responsibly.

UNDP defined good governance as: Good governance is (the striving for) rule of law, transparency, responsiveness, participation, equity, effectiveness and efficiency, accountability and strategic vision in the exercise of policical, economic and administrative authority.

The UNDP (1997) articulates eight principles of good governance. These principles are:

\begin{enumerate}
\item \textbf{Equality of participation in decision making.} All people, irrespect ve of sex, class, or race should be heard and allowed to participate in deliberations that affect them directly or indirectly. In democratic societies, citizens can participate in various ways, ranging from voting to involvement in acts of civil disobedience. In many instances, participation must be informed and organized through civil society actors who can often leverage resources more successfully. Good governance implies that organizations encourage participation from those who may both benefit or be harmed by any decisions taken. Participation also means that individuals have the rights of freedom of association and expression, and to participate in organized civil society without fear of retribution or the stigma of being labeled unfairly as a "special interest" group.
\item \textbf{Organizations must be responsive to the needs of all stakeholders in a reasonable timeframe.} On one level, this means that organizations must hire, train, and retain employees to achieve optimal response time and high quality outcomes. On a more general level, organizations must ensure that they have the capacity, and in some cases the autonomy, to implement changes to structure and management systems to maximize efficiency.
\item \textbf{Organizations must mediate differences between stakeholders to reach a broad consensus.} Good governance requires that organizations involved in divisive issues like abortion, stem-cell research, human cloning, euthanasisa, etc. enter such debates in the spirit of cooperation and mediation. To achieve this goal, organizations must treat all stakeholders consistently and fairly.
\item \textbf{Organizations must be accountable to the stakeholders they serve.} Good governance requires a broad definition of who such stakeholders may be. Many organizations limit intentionally the list of those they define as valid stakeholders to narrow the scope of decision-making authority, the range of topics addressed, and the nature of the decisions that are made. In general, organizations should be accountable to those affected by the entire range of decisions or actions made and implemented by an organization.
\item \textbf{Organizations must strive for transparency in their decision-making processes so that interested parties can understand the bases of decisions and monitor progress.} Good governance requires that organizations justify decisions made by demonstrating how such decisions respect the precedent from previous decisions.
\item \textbf{Organizations must work within legal frameworks that are crafted in fair ways, enforced impartially, and attuned to human rights issues.} Good governance means that a country’s legal environment should be conducive to development. Investors must feel comfortable that due process will be followed in all countries of interest, and that a wide range of issues including protection of intellectual property, fair application of trade subsidies and sanctions, and a regulated financial marketplace exist. Organizations must also follow the laws of the land and ensure that all decisions made are consistent with such laws.
\item \textbf{Decisionmakers should have a broad and long-term vision on how to better the processes of governance to ensure continued economic and social development.}
\item \textbf{Good governance involves guaranteeing the rights of all individuals to maintain and improve their well-being in an equitable and inclusive manner.} This principle conveys the message that good governance is about stewardship and care and that it involves the highest ethical positioning possible.
\end{enumerate}

Clearly, good governance is more political than technical in nature and emphisizes the primacy of equality and the value of vision, strategic thinking, and planning. Good governance is a tool for making organizations work more effectively in a world where trust is declining in government, industry, science, and other institutions. Good governance is based on democratic values that stimulate administrative reforms that affect a range of organizations.

The World Bank has compiled a list of six dimensions of public-sector governance that are used in an aggregate fashion to measure the quality of governance: voice and accountability, political stability and absence of violence, government effectiveness, regulatory quality, rule of law, and control of corruption. As new global standards of governance emerge, indicators like these can be used to diagnose failures and to suggest solutions to a range of performance and process issues.

Good governance is an ideal that is difficult to achieve. Although it is essential for ensuring national prosperity by increasing acccountability, reliability, and predictability of decision making in governments, corportations, and non-governmental organization. To ensure that good governance prevails, elected representatives, corporative executives and boards of directors, professional bodies, and civil society groups need to become more active in learning about the perils associated with "bad" governance (social inequality, development failures, and corporate scandals) and push for stronger laws and policies that protect the public interest.

Founding concept of good governance for Nepal began with the description of \textit{Ram Rajya}, meaning the ideal state. Vedic norms and values of Nepal were guided by this philosophy. As a model figure in statemanship, Ram, an ancient king of south asia, is famous in eastern society. He is well known for sacrificing his much loved wife addressing the public. Governance comprises the mechanisms, processes and institutions through which all the stakeholders, viz., the state, private sector, civil society and citizens articulate their interests.

Following series of events can be identified to have institutionalized the issue of good governance in Nepal:

\begin{itemize}
\item Before 1950s the developing countries' governments oversaw as their major responsibility the task of promoting peace and security and tax collection. After the second world war the focus shifted on the development management. Likewise, the developed countries showed interest in supporting lesser developed ones.
\item Developed countries offered support indifferenty of the aidee country's diversity and the receiver country could not execute planned development programmes due to variety of socio-economic problems.
\item During 1980 it was acknowledged that donor countries should alter their policies regarding development aid while the receiver country should strieve to resolve socio-economic hurdles.
\item For the purpose of maximum utilization of foreign aid, donor countries prepared an Aid Agenda which included good governance as a criteria for granting the support.
\item It was first defined by World Bank in 1989 which broadened the meaning of governance by incorporating the role and interconnection of three different actors: Government (state actors and institutions), Civil Society (civil alliances and non-governmental organizations) and Private Sector (households and companies).
\item 
\end{itemize}

However, not a single political party, regime or movement has been able to quash the contributing factors of bad governance. For the last six decades, Nepal has become the zenith of corruption that is leading Nepal toward a failed state. Many types of corruption are prevailing in Nepal that range from petty corruption, grand corruption, legal, moral and political corruption to organized crimes, which have become one of the impeding formidable forces in ensuring good governance. In Nepal, bureaucracy or public sectors have suffered most from the rampant corruption. In fiscal year 2015/16, Commission for the Investigation of Abuse of Authority (CIAA) Nepal received a total of 15,126 cases of corruption.  Furthermore, according to corruption perception index, Nepal ranks 131st out of 175 countries in the world. From 2004 to 2016, Nepal’s average rank on corruption index has been 133 out of 175 countries.

\end{solution}

\question What is drug abuse ? What are the effects and consequences of drug abuse ?

\begin{solution}

The substance that affects our mind and organs and damages our body if used in uncontrolled amount is drug. The habit of taking drug regularly is drug abuse or drug addition. Drug abuse and addiction have negative consequences on individuals and society as well. In reality, drug addiction is a complex disease, and quitting it takes more than good intentions or a strong will. Drug abuse is a serious public health problem that affects almost every community and family in some way. Each year drug abuse causes millions of serious illnesses or injuries. Drug abuse also plays a role in many social problems, such as drugged driving, violence, stress, and child abuse. It can lead to homelessness, crime, loss of employment, failure in school, domestic violence, etc.

Generally, drugs are illegal. Some of the drugs used and supplied by the drug users and drug traffickers are herion, smack, cocaine, cannabis, etc. Selling of such substance is illegal subject to criminal offense. Although strict laws are in place for punishing those who are involved in drug trafficking business, several people are involved in it. Below are some of the reasons that make it very difficult to stop drug trafficking:

\begin{enumerate}
\item The traffickers run this business in an organized way.
\item The traffickers use their private means of transportation for supply.
\item They have good link in customs, airport, etc.
\item There is good deal of money in this business.
\item The traffickers have link and wide network with high ranking officials and politicians.
\end{enumerate}

\textbf{Causes of taking drug}

The use and trend of using drugs is increasing rapidly in the world. About 4\% of the world's population use drug of some form. Many adolescents, teenagers and youth easily fall to drug abuse than elders because they are easily motivated by traffickers. The causes of drug taking are:
\begin{enumerate}
\item Due to influence of bad company, they trust their peer groups and under peer pressure, youths start using drugs.
\item Drug traders abuse them for their criminal purpose.
\item Attraction to advertisement and promotional activities that youths are inclined to imitate.
\item Due to lack of peace in family environment.
\item Lack of love and care from family members or related peers (girl/boy friends)
\item Teenagers have high expectations and when they are not fulfilled they feel frustrated and take drugs as resort.
\end{enumerate}

\textbf{Effects of drugs to and individual}
\begin{enumerate}
\item Cannot continue education
\item Failure and setbacks in exams and cannot develop career
\item Loose jobs due to decreased attention to work
\item Possibility of contracting diseases like AIDS, Cancer, etc
\item Suffers from financial crisis
\item Increase in criminal attitude
\end{enumerate}

\textbf{Effects of drugs in a family and society}
\begin{enumerate}
\item Emotional stress in the family
\item Family loses peace and prestige
\item Financial crisis in the family
\item Kids are victimized
\item Squabble and conflict with neighbors
\item Accident, robbery, murder, kidnapping and criminal activities increase in the society
\item Society struggles with economic and infrastructure development
\item Society loses active and creative manpower
\end{enumerate}

\textbf{Solution to the problem of drug abuse}
\begin{enumerate}
\item Strict laws should be made and implemented against drug traffickers.
\item Mass awareness programmes should be conducted to aware general public about the consequences of drug abuse
\item Various social organizations should play an active role in raising awareness against the drug abuse
\item Children and youths should receive proper counselling
\item Children should be raised in a good environment with proper love and care from parents
\item Rehabilitation centres should be provisioned for those seeking institutional support
\item Family and society should develop positive attitude towards those individuals committed to refrain drug use.
\end{enumerate}
\end{solution}

\question What is social conflict? Discuss about the causes and consequences of social conflict in Nepal.

\begin{solution}

A society composed of diverse of individuals and groups. Each individual or group within a society have their unique ethnicity, language, culture and religion and socio-economic background. Similarly, it is hard to find individuals with common pursuit of interests, hobbies, habits and perspective. Therefore, in a ways, diversity itself gives way to conflict. Individuals differing for various interpersonal attributes and socio-cultural background can have a sense of amusement, non-acceptance, dispute/debate and disagreement in simple to moderate manifestation. In extremes of those, feelings of envy and grudge as well as tendency to exploit physical means of harm arises. All these happenings are characteristic of social conflict.

Following factors give rise to social conflict in Nepal

\begin{enumerate}
\item An individual loses trut in other and fails to respect his rights and authorities
\item Unemployment
\item Increase in poverty
\item Economic inequality
\item Indifference to social customs and values
\item Drug abuse and intoxication
\item Lack of social justice
\item Lack of education and awareness
\end{enumerate}

Although there are some \underline{positive} consequences of social conflict, including progression of socio-economic transformation, increase in awareness, improvement of social justice system and occassional enrichment of solidarity, several \underline{negative} consequences of it exit. Some of which are:

\begin{enumerate}
\item Disruption of social peace and order
\item Increase in criminal activities of robbery, murder, kidnapping
\item Encroachment of personal rights and feedom of individuals
\item Social tradition will be replaced by wrong social customs and values
\item Socio-economic development and physical development will be stalled.
\end{enumerate}

Acknowledging that social conflict has a wide reach within multiple socio-economic, religious and political sphere of a community and a nation as a whole, the situation should be resolved creatively rather than forcibly. A peaceful debate and a harmonious mindset with the feeling of tolerance are the pre-requisite for social order setting.
\end{solution}

\question What are the problems in implementing public policy in Nepal ?

\question How can we control the deforestation that might be caused by socio-economic factors ? Explain

\begin{solution}

Deforestation is the clearence of forest or woodland for extracting natural forest product such as timber, firewood, medicinal herbs, or any other form of human or human induced activities that result in loss of forest species. Such activities may include encroaching forest space and overgrazing, etc.

Most of the population of Nepal dwell in rural areas with minimum access to urban infrastructure -- easy transportation, well developed alternative sources of fuel, means of communication and specialized occupation. This means people are excessively reliant on natural unprocessed products derived mainly from forest, for making their living. The 2011 AD forest survey indicated that Nepal has more than 40% of its land area covered with forest, thus highlighting significant interaction of forest ecosystem with people, communities, biodiversity and economy. The relationship is more profound when the context is rural, which most of the Nepal is composed (82.93% according to 2068 BS census).

Still today, people use firewood as major source of fuel for cooking food to handling chores. In a lack of permanent residence building, several families still make thatched homes out of forest timber and tree cuttings. The latter is also fed to cattle as an important part of roughage diet since villages do not have reach to concentrate feed for the animals. Depleting an important reservior of human livelihood maker and animal provider in rural topography of Nepal will only make residents of these areas more vulnerable to economic shocks. When a household is engaged in forest timber accrual and supply as a source of earning, this dependence will lead to economic setbacks and overall lower quality of life during periods of lean supply from forest. Interestingly, the relationship applies conversely also, because regions like inner terai districts of Nepal, with inherently rich forest resources, are found to be progressing very quickly.

An accelerating rate of forest clearence can be controlled by one or more of the following measures:

1. Protection, utilization and benefit sharing scheme should be developed for community managed forest. Community participation in planning and execution of such schemes will make them have the feeling of ownership.
2. Alternative sources of energy should be promoted for fuel.
3. Marginal lands and shrublands should be disallowed for intensive agriculture and livestock grazing.
4. Acknowledging that every 1 hectare of arable land should be accompanied by 3 hectares of forestland, programmes for forest reclaimation and plantation should be intensified.

\end{solution}

\question What are the provisions in Constitution of Nepal, 2072 for activities, rights and duties of Commission for Abuse of Authorities ?

\begin{solution}

\end{solution}

\question What are the major reseasons for deforestation in Nepal ? What are the consequences of it ?

\begin{solution}

Deforestation is occuring in Nepal due to human and natural causes. Forest encroachment, illegal forest clearance, clearance due to waterway entry (river passage), land slide, forest fires, uncontrolled grazing, unchecked extraction of forest floor resources such as stones, pebbles, sand and minerals, lack of public awareness, etc are the major reasons for deforestation in Nepal. Several factors contributing to deforestation can be summarized as below:
\begin{itemize}
\item Excessive utilization of forest resources in physical infrastructure development.
\item Forest protection, conservation and promotion activities are not having impact.
\item Afforestation programmes and forest conservation endevours are not well organized and effective.
\item Very feeble participation of stakeholders in overall development of forest sector.
\end{itemize}

Deforestation in Nepal has wide consequences, some of them are:

\begin{itemize}
\item Most important factor causing large-scale floods is deforestation in Tarai and Siwalik regions. Large-scale deforestation of northern Tarai and Chure range has aggravated flood problems in Tarai. Forest and vegetation obstruct the flow of water and reduces flow speed. Water is absorbed underground, resulting in less runoff and fewer floods. Also, forestland upstream provides a natural buffer for Tarai thus providing more response time. Deforestation has thus left the Tarai people with less reaction time, frequent and intense flooding, filling of agricultural lands with sand, diminishing ground water and high concentration of soluble minerals such as arsenic in tube well water.
\end{itemize}

\end{solution}

\question What is the role of cooperative sector in economic development of Nepal ?

\begin{solution}

Cooperatives were initially established for raising income generating activities of group of peoples of common interest. Individuals organize into a cooperative voluntarily, cooperate for common good, and are righful to the benefits that arise.

\end{solution}

\question What are the current facilities and remunerations in place for public service personnels ?

\begin{solution}

The facilities and remunerations that public service employees receive are the benefits they are authorized to for dedicating their labor, skill and time in providing service on behalf of government. The reward-facilities may be monetary or non-monetary. The civil service act, 2049 and civil service regulations, 2050 provisions following reward and facilities to the employees:

Monetary reward-facilities

\begin{itemize}
\item Monthly salaray and allowance
\item Grade facilites (increment of salary) after serving for a year
\item Payed holiday service
\item Facility of retirement benefits upon phasing out of service
\item In event of heart, kidney and cancer diseases there is provision additional 5 lakhs support
\item Life insurance of upto 1 lakhs
\item Every year 1 month salary amount will be offered as festival benefit to working personnels
\item Retired personnels will receive a retirement benefit amount of 1 month in addition to regural amount every year as festival benefit
\item Saving of salary (10 percente) as provident fund and additional amount equal to the salaray fraction will be paid by government
\item Provision of payment for health treatment -- equalling 12 month salary for gazatted officer, 18 month and 21 months salary for non-gazatted personnels and personnels without level specification, respectively.
\item Two third of the increased salary will be available in retirement pension, in every raise in salary.
\item Family pension or retirement fund payment
\item Family will be granted Rs 150,000 in case the personnel dies while in service
\item For death of civic service personnel member in a family, child care allowance of 5000 for a child each (for 2 children) will be provided.
\item Monetary award in civil service day to awardees.
\item Allowance for uniform and dress
\item Educational fund, family fund and disabled personnel fund facilities
\end{itemize}

Non-monetary reward-facilities

\begin{itemize}
\item Relocation transfer every 2 years, alternating between rural and urban centres
\item If both husband and wife are employed on the same service they will be attempted for transfer to a common district
\item Non-gazatted personnels will most likely be transferred to nearest localities to their home.
\item Leaves of different kinds
\item For foreign residing ambassadors and personnels employed in consular offices, at most 5 years of unpaid leave will be provisioned
\item Employee service protection, service contract protection and employee protection related provisions
\item For advocating professional rights of personnels, freedom for alignment in trade union
\item For punishing a personnel on beaureucratic basis, provison of refarral to the public service commission.
\end{itemize}

\end{solution}

\question What are the recommendations for making public service more attractive in Nepal ?

\begin{solution}
\begin{itemize}
\item Update basic pay and salary features to reflect contemporary status
\item Develop "pay for performance" indicator and implement in all offices
\item Provision special facilities for personnels working in rural areas
\item Update allowance offerings on dressing and uniform
\item Construction of integrated residence facilities for personnels
\item Automate transfer and promotion system in order to make it more transparent and predictive
\item In order to provision personnels filing up vacant positions in public sector, employee recruitment system should be more responsive and expedient, possibly arraning for twice a year recruitment.
\item Improve workplace environment and render it free of unncessasry interferes.
\item Identification and punishment of wrongdoers amongs the recruited personnels in order to improve public image of the service.
\item Upgradation of public service act and regulations to reflect contemporary needs to make service modern and public friendly.
\end{itemize}

Finally, It should be acknowledged that public service personnels are the carriers of social change. Therefore the sector should be strengthened, efficient and progressive. For this to happen several fiancial, including monetory and non-monetory, amendments should be made. Recruitment process should be streamlined and moderninzed to allow easy entrance of competent individuals. It should be ensured that the personnels are efficiently mobilized. Only then, the public service sector can manifest its full potential. This develops both the service sector and its employees and improves the productivity of the service.

\end{solution}

\question What is devolution ?

\begin{solution}

Devolution is defined as the transfer of power from higher to lower units of any system. In its broad form devolution resembles decentralization, but is often regarded as being more complete and permanent than decentralization. Most frequently, devolution is used with reference to the transfer of responsibilities and authority from central to subnational (or regional to local) levels of government. The World Bank distinguishes between deconcentration, delegation, and devolution as three distinct modes of administrative decentralization of the redistribution of authority, responsibility, and financial resources for providing public services. The three types are differntiated according to the degree of transfer, with decentralization being the weakest form and delegation coming next. 

Hence, devolution is regarded as the strongest mode of decentralization in the sense that powers are devolved to political entities with a separate corporate status, such as local or regional governments. That is why devolution is also referred to as political decentralization. 

Motivations for devolution in that sense include the perception that devolved governments are best placed to develop and implement policies that exploit endogenous local or regional capabilities and are, hence, an appropriate reaction to increased competition between regions in a globalized economy.

To qualify as a devolved system, the subnational levels of government should be legally established as institutions that exercise power within clearly recognizable geographical boundaries. Other criteria include democratic institutions such as popular elections and the existents of assemblies.

Nepalese context ???

\end{solution}

\question What is E-government ?

\begin{solution}
E-government (electronic government) refers to the impact of information and communication technologies, particularly the Internet, on the values, processes, and outcomes of public bureaucracies.

Government-to-government interactions are concerned with the use of technologies to enhance the internal efficiency of public bureaucracies, through, for example, the automation of routine tasks and the rapid sharing of information between departments and agencies. Government-to-business interactions typically involve the use of the Internet to reduce the costs to government of buying and selling goods and services from firms. Government-to-citizen inter- actions involve using the Internet to provide public services and transactions online, and to improve the design and delivery of services by incorporating rapid electronic feedback mechanisms, such as instant polls, Web surveys, and e-mail.

Use of information and communication technology in government first expanded during the 1950s and 1960s, the heyday of ideas of scientific administration. However, e-government as it is most commonly understood today emerged as an agenda for general reform of the public sectors of liberal democratic political systems during the early 1990s. U.S. President Bill Clinton's administration led the way with the 1993 National Performance Review of the federal bureaucracy.

The ubiquity of computer networks offers the potential to increase political participation and reshape the state into an open, interactive, network form, as an alternative to both traditional, hierarchical, bureaucratic organizations and more recent, marketlike forms of service delivery based on the contracting out of public-sector activities (usually termed the new public management). Government becomes a learning organization, able to respond to the needs of citizens, who are in turn able to influence public bureaucracies by rapid, aggregative feedback mecha- nisms such as e-mail, online discussion forums, and interactive Web sites.

Alternatively, e-government does not necessarily require greater public involvement in shaping how services are delivered, but instead, indirectly benefits citizens through the efficiency gains and cost savings produced by the reduction of internal organizational friction, chiefly via the automation of routine tasks. It joins and coordinates the activities of previously disparate government departments and services.

The critics of e-government suggest that changes are limited to a managerial agenda of service delivery more consistent with the new public management and that the opportunities offered by the Internet for invigorating democracy and citizenship might be missed.

\end{solution}

\question Explain the role of tourism sector in the economic development of Nepal.

\begin{solution}
Tourism is one of the highly potential sectors for economic development of Nepal as it expands the opportunities for employment, income generation through indirect involvement and direct earning of the foreign currency.

The home country to 8 of the world's top 10 highest peaks, birthplace of the Gautam Buddha and a center of faith for large swathe of hindu piligrims around the world, Nepal, also hosts numerous culturally rich societies as well as world heritage sites.

According to World Travel and Tourism Council (WTTC) annual report in 2018, travel and tourism is one of the world's booming industries, generating approximately 8.8 trillion USD annually. Over 600 million international tourists visit different parts of the world every year.

According to Lonley Planet, Kathmandu is the 5th top travel destination in the world for the year 2019. Recent years have seen positive signs of progressing tourism industry with the increase in inflow of foreign tourists after the devastating 2015 Earthquake. According to economic survey, 2018/19, the number of tourists arrivals in 2018 (not counting tourists who arrived by land) was 1173072, which is 25% more than 2017. The tourism industry brought in foreign currency equivalent to 76.09 billion NRS in the FY 2017/18.

In 2018, the number of registered travel agencies reached 3508 and trekking agencies 2649. Government has formulated policies and allocated a budget of Rs 2.68 billion for the FY 2019/20 to support tourism sector in developing infrastructure and encouragin environment-friendly tourism activities. Rs 15.85 billion has been allocated for aviation sector improvement in the same year. Unfortunately worldwide spreading of COVID-19 pandemic, which reinstated nationwide lockdowns and tightened travel restrictions, caused government to retract its plans for launching a Visit Nepal 2020 campaign.

\end{solution}

\question What do you mean by periodic plan ? What are the major strategies adopted by the ongoing periodic plan (2073/74-2075-76) ?

\question What do you mean by environment management ? Describe the interrelationship between environment management and sustainable development.

\begin{solution}

Environment management is concerned with the description and monitoring of environmental changes, with predicting future changes and with attempts to maximise human benefit and to minimise environmental degradation due to human activities. Environmental managers are a diverse group of people including academics, policy-makers, non-governmental organisation (NGO) workers, company employees, civil servants and a wide range of individuals or groups who make decisions about the use of natural resources (such as fishers, farmers and pastoralists). Yet, characteristically, environmental management is about decision-making -- and it is especially concerned with the process of decision-making in relation to the use of natural resources, the pollution of habitats and the modification of ecosystems. Fundamentally, then, environmental management is a political activity because those decisions - about resources, pollution and ecosystems - are never neutral or objective.

Rural parts of Nepal (home to 81.75\% population) are traumatized by the poor geographical terrain wherein majority of household are reliant on forest (constitute 44.74\% of total area), biodiversity and natural watershed resources -- to the extent that these resources are already seeing a peril. The environment here is subject to the stresses and strains of deforestation, lossof top soil, misuse of pesticides or insecticides, soil contamination, a decrease in productivity, watershed disruption, a shortage of resources, landslides, flooding and indoor pollution. The general environmental problems in urban cities and municipalities are air and water pollution, unmanaged solid waste, the lack of land-use planning, inefficient urban infrastructure, a conglomeration of manufacturing establishments, resource shortages, over-crowding and loss of vegetation.

Currently there are 5,646 industries in operation in Nepal (Registered at DoI 2013/14), composed of agriculture and forestry, energy, manufacturing, service, construction, mining and tourism sectors. Capital wise, there are 686 large, 1330 medium and 3630 small industries.

Thus, in this context with need of rapid economic development through extensive resource mobilization, amidst the pushbacks from changing global climate, environment management and its conceptual ties with sustainability at the core, holds much greater importance. The human and infrastructure losses due to the earthquake of April 25, 2015 have become a great threat and challenge for environmental management in the present scenario of our country. Some interventions are already in place. Those constitute:

\begin{itemize}
\item Constitution of Nepal, 2015; Article 30: Right to Clean Environment
\item SDG Goal, 2030
\item Environment Protection Act, 1997: The main thrusts of the Act and the Regulation are pollution control and environment assessment (EA). Regarding environmental pollution prevention and control, a pollution control permit system is conceived in the regulation. Detailed procedural approaches including environmental standards are identified by MOEP and executed through concerned line agencies. EA, the other environmental tool, is categorized into two parts: initial environmental examination (IEE) and environmental impact assessment (EIA). Development projects under the scope of IEE will be cleared by the concerned line agency, whereas MOEP will concentrate on the EIA category projects. Here again, monitoring of the EA-granted projects by MOEP has to be carried out by the concerned line agencies. Similarly, a provision of a revolving fund for pollution control, environment and heritage conservation, awareness creation, research and award business exists in the regulation. In addition to these, a compensation claim of damage due to environmental pollution caused by any sources could create controversies because of its vagueness and complaint handling procedures.
\item Nepal has adopted the notion of green development to minimise stress on environment and to mitigate the impacts on climate change. National policy has stressed environment and climate change. It has mainly focussed on strengthening and updating environmental policy, existing laws, rules and mechanisms. It also focuses on enhancing institutional capacities.
\item ISO 9001 Quality Management System: more than 600 companies registered
\item ISO 14001 Environmental Management System: more than 30 companies registered
\item ISO 14006
\item Status and Assessment of EMS Implemented Industries of Kathmandu Valley, MoI, 2009 
\item Environment Sector Programme Support (ESPS) 2000
\end{itemize}

\end{solution}

\question What is the role of public, private and community institutions in environment management ?

\begin{solution}
The act of describing, monitoring, predicting changes and maximizing human benefits from natural resources by maintaining a balance in their use and conservation without negatively affecting their quality and availability for future generations is called environment management. The role of public, private and community institutions in environment mangement is highlighted below:

\textbf{Public sector}

\begin{enumerate}
\item Forest, watershed, ponds and water reservoir conservation
\item Reducing negative impacts of climate change and introduction of green development concept
\item Mandatory provisioning of environmental impact assessment in development and construction projects
\item Air pollution, water pollution, sound pollution, soil pollution, food pollution and industrial pollution control and setting threshold in place for keeping them on check
\end{enumerate}

\textbf{Private sector}

\begin{enumerate}
\item Respecting and implementing plans, policies and laws-bylaws set forth by government
\item Proper management of industrial and manufacturing wastes
\item Public construction projects should be environment friendly
\item Bearing of social responsibility
\end{enumerate}

\textbf{Community sector}
\begin{enumerate}
\item Emphasis on organic farming and synthetic chemical-free fertilizer management in farming
\item Increase awareness on sanitization and proper waste disposal in society
\item Increase role in deforestation control
\item Lauch campaign on waste management and develop community level infrastructure such as public toilet and waste treatment unit for the activity
\end{enumerate}

\end{solution}

\question (Long answer type) Briefly analyse the existing situation of poverty in Nepal. Also mention the measures to be taken for poverty reduction in future.

\begin{solution}

Poverty alleviation

The state of economic and social backwardness is called the poverty. A set of economic and humanitarian measures, strategies and activities intended to permanently lift people out of poverty is known as poverty alleviation/reduction. There are policy, legal and institutional efforts being made in Nepal to reduce poverty.

The consitution of advocates and the sustainable development goals have highlighted social security and justice for people of all gender, regions while lending special emphasis to economically backwarded group of people in the society. Several programmes launched in the past two decades attempted to address the issue of poverty reduction and since the 10th five year plan, the issue was tackled systematically. Povery was categorized in three dimensions -- income poverty, human poverty and social deprivation. Currently more than 50 programmes aimed at lifting poor of their status are launched. In order to ensure that such programmes recognize true poverty stricken households and provide require interventions, a task of poor household identification and issuance of identity card to those has been on-going. Consequently, Nepal has made a significant progress in addressing poverty and improving human development index (HDI). Still, currently 18.7% of the population lie below poverty line and 28.6% of population is poor according to multidimentional poverty index (2018/19). This means we are still far from being established as a affluent nation.

Sustainable development goals envisages, all multi-dimensional indicators of poverty addressed, which includes increament of per capita income and reduced economic inequality among classes of people of different geographical locations, gender and social sectors and reformed national efforts towards this end in future. Similary, efforts of public, private and community and NGO, INGO, including development stakeholders need to be concerted and streamlined with strong cooperation for poverty reduction.

The 15th plan foresees a reduced absolute poverty rate to 11% and multidimensional poverty indicator to 13% by the end of planning period. Likewise it approaches for significant improvement of economic inequality between different income group of people.

Apart from strategic and working course of action set forth by government for current planning period, a general framework of measures for poverty alleviation are given below:

\begin{itemize}
\item Income generation is the major safeguard against poverty, henceforth activities promoting employment and skill development should be promoted
\item The distribution of poor households -- location, size and status should be recorded and database updated regularly
\item Identity card should be distributed among the identified households in order to facilitate easy launching of programmes to the target group.
\item Policy amendments with allowance package for truly poor individuals should be made
\item Programmes and projects aimed at skill enrichment of different sectors of people should be launced based on priority
\item Settlement plans for refugees should ensure their upliftment
\item Street children, disabled and elder citizen should be granted special support
\item Equal opportunity for employment to all classes of citizens
\item Government should aim for improving livelihoods of the poor through their self-reliance
\item Promote activities that increase self-employment. For this, agriculture commercialization and diversification should be done at policy level and supply of fertilizer, improved seeds and chemicals should be assured.
\item Investment environment should be improved for increased investment in agriculture, manufacturing, trade, tourism, health and education.
\item Fostering of inter-agency cooperation between government organizations in the fight against poverty.
\end{itemize}

A state of poverty reflects weak privilage for a nation and its citizens. It also means that the economy is underdeveloped and unhealthy for modern infrastructure attainment. Thus a targeted approach, that identifies and arranges basic facilities for the poor so as to enable them uplift their livelihood through skill generation and income generation enterprise is the current necessity in nationwide fight against poverty.

\end{solution}

\question What are the development related policies mentioned in constitution of Nepal ?

\question Mention the problems for achieving good governance in Nepal.

\question What do you mean by rule of law ? Explain.

\question What is the meaning of reservation ? Why is it necessary in government services ? Mention.

\question (Long answer type) What type of relationship have been envisioned between federal, state and local levels in the constitution of Nepal ? Explain.

\question How does the management information system help in decision making process ?

\question What do you mean by inventory management ("Jinsi byabasthapan") ? Highlight about its importance in Nepalese public administration.

\question Write short notes on:
\begin{enumerate}[label*=\alph*., leftmargin=1cm]
\item Tax reduction at source
\item Civil service 
\end{enumerate}

\question What are the geographical features of Nepal ? Mention in brief.

\question Although, Nepal is an agricultural country, what are the reasons for decreasing productivity of arable land in recent years.

\question What are the negative impacts or such impacts possible due climate change in Nepal ? Mention.

\question Write about the "Chepang" ethnic group.

\question What provisions and guidelines have Forest act, 2049 set for utilization and management of forest in Nepal? Mention.

\begin{solution}

The Forest Act, 1992, defines national forest, state-managed forest, protected forest, community forest, leasehold forest, religious forest and private forest as well as ownership of different types of forest, and their management. The Act encourages people to own and to use forest, rather than depend on national or state-owned forest. The Forest Regulation, 1994, fixes users' price rates for timber, fuel-wood, medicinal plants and herbs, flowers and furs, fruits and seeds, bark, logs, and allied forest products. Likewise, charges for animal and cattle grazingare also fixed by the regulation.

Similarly, separate regulations for national parks such as the Royal Chitwan National Park and Royal Bardia National Park make it possible to charge different fees for entrance and recreational activities such as safari, hunting game species and fishing. Another milestone in the forestry sector is the Buffer Zone Management Regulation, 1995, which aims to harmonize relation between national parks and the people around those parks. This regulation also encourages the communities around parks to form users' groups so that they can mange and use the buffer zone resources.

\end{solution}

\question (Long answer type) What is energy crisis ? What are the measures that can be taken to solve the crisis ? What are the different sectors affected by energy crisis ?

\question Explain briefly on the prospect of hydroelectricity development in Nepal.

\question What is human development index (HDI) ? Explain in brief.

\question Discuss in brief the role of private sector in economic development of Nepal. 

\question What is poverty ? What is the difference between absolute and relative poverty ?

\question Write short notes on:

\begin{enumerate}[label=(\roman*)]
\item Ethnic groups of Nepal
\item Biodiversity
\end{enumerate}

\question What is the status of environmental pollution in Nepal ? Discuss about the efforts made by Government of Nepal in reducing effects of environmental pollution and preparing for climate change ?

\question What is meant by standard time ? Mention how is standard time of Nepal determined ?

\question What are the measures that should be taken to conserve forest resources in Nepal ?

\question Write in brief about the Lhosar festival celebrated in Nepal.

\question Justify: Unplanned urbanization negatively impacts development of nation.

\question How are indigeneous and local ethnic groups prioritized in Nepal ? Mention what strategies are taken by government to that end.

\question (Long answer type) "Foreign employment significantly contibutes to customs earning of Nepal". Briefly elaborate the statement.

\question What are the different types of climates occuring in Nepal based on the geographical features ?

\question Write in brief about the importance of water resources of Nepal.

\question What are the major causes of deforestation in Nepal. Discuss.

\question Explain about the importance of tourism industry in economic development of Nepal.

\question According to Army Act, 2063 what are the punishment provisioned through Court Marshall ?

\begin{solution}
According to the Army Act, 2063 (Chapter-11; Section (dafa) 101), 

1. Following penalties may be imposed by court marshall:

\begin{itemize}
\item Life imprisonment along with confiscation of entire property,
\item Confiscation of his or her entire share of ancestral property,
\item Imprisonment of upto Fourteen years,
\item Removing from service without prejudicing eligibility for any governmental service in the future, or dismissing with ineligibility for any governmental service in the future,
\item Demotion to a lower rank,
\item Freezing of promotion for Five years,
\item Deduction of salary and allowances for Three months in case the offence has been committed in the course of military action,
\item Freezing of salary and allowances until the recovery of compensation,
\item Freezing of salary increments for a period not  exceeding Two years,
\item Warning (Nasihat).
\end{itemize}

2. The following penalties shall be imposed for the following offences:

\begin{enumerate}
  \item Life imprisonment along with confiscation of entire property for the commission of offences as referred to in Section 38, 39 or Clause (a) of Sub-section (1) of Section 42.
  \item A maximum Fourteen years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Section 40,
    \item Offences provided in Section 41 and Clause (a) of Section 45 during a military operations,
    \item Offences provided in Section 43 or 46 if committed intentionally,
    \item Offences provided in Clause (a) or (b) of Section 44 committed against a person while discharging his/her duties during a military operation,
    \item Offences provided in Section 47.
  \end{enumerate}
  \item A maximum Ten years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Clauses (a) or (b) of Section 44 committed against a person not during the military operation,
    \item Offences provided in Section 48, 49 or 50, (3) Offences provided in Clause (a) of Section 51 or Clause (a) of Section 52.
  \end{enumerate}
  \item The penalty of confiscation of entire property or maximum of Seven years of imprisonment shall be imposed for the commission of offences provided in Clause (b) of Sub-section (1) of Section 42.
  \item A maximum of Seven years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Section 41 committed not during military operation,
    \item Offences provided in Section 46 that are committed unintentionally,
    \item Offences provided in Clauses (b), (c), (d), (e), (f) or (g) of Section 52,
    \item Offences provided in Section 43, 54 or 63.
  \end{enumerate}
  \item A maximum of Five years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Clause (c) of Section 44, (2) Offences provided in Clause (a) of Section 45 committed not during the period of a military operation,
    \item Offences provided in Clauses (b) or (c) of Section 51 or Sections 45, 56 or 57.
  \end{enumerate}
  \item A maximum Three years of imprisonment shall be imposed for the commission of offences provided in Clauses (c) or (d) of Sub-section (1) of Section 42 or Sections 58, 59 or 60.
  \item A maximum of Two years of imprisonment shall be imposed for the commission of the following offences:
  \begin{enumerate}
    \item Offences provided in Clauses (e), (f), (g) or (h) of Sub-section (1) of Section 42,
    \item Offences provided in Clause (b) of Section 45,
    \item Offences provided in Clause (h) of Section 52 committed by personnel below the rank of officer while discharging duties during a military operation,
    \item Offences provided in Section 43 that are committed unintentionally,
    \item Offences provided in Section 61.
  \end{enumerate}
  \item A maximum of Six months imprisonment shall be imposed if a personnel below the rank of officer commits offences provided in Clause (h) of Section 52 except in the period of military operation or while on duty.
  \item A person who commits offences provided in Clauses (i) and (j) of Section 52 shall be removed from the service.
  \item A person who commits offences provided in Clause (k) of Section 62 shall be barred from Two salary increments or promotion for Two years.
  \item A person who attempts to commit such offences as referred to in Chapter-7 or induces another person to commit such offences shall, unless there is specific provision in this Act, be imposed the following penalties:
  \begin{enumerate}
    \item A maximum of Fourteen years of imprisonment for attempting to commit an offence for which a penalty of life imprisonment along with confiscation of entire property may be imposed, and half of the maximum (range) imprisonment for other offences which have been attempted,
    \item Equal penalty for inducement (incitement) to commit an offence as imposed for committing an offence,
    \item A maximum of Fourteen years of imprisonment for inducement to commit an offence which has not been committed (completed), and half of the maximum (range) punishment for inducement to commit any other offence which had not actually been committed (completed).
    \item If a person who committed an offence provided in Clause (b) of Sub-section (1) of Section 42 has absconded and is not found (traced) does not produce him/herself within Thirty Five days, his/her partition share to ancestral property shall be frozen from being transacted. If such person does not appear him/herself or could be found through making a search within Three years, his/her partition share to ancestral property shall be confiscated and auctioned, and the money therefrom shall be deposited to the Government Treasury.
    \item After confiscation of partition share to ancestral property, if the  offender is found, he/she may be imposed life imprisonment along with confiscation of the entire property.
    \item A person who is dismissed from service and disqualified for any governmental job in future pursuant to Clause (j) of Sub-section (2), shall not be paid his/her remaining salary or allowances and pension which he/she is entitled and other facilities except the money accumulated in his/her provident fund.
  \end{enumerate}
\end{enumerate}

Besides these there is Battlefield penalty (Section 104) and Departmental action (Section 105) and Collective fine (Section 107).

\end{solution}

\question What are the causes of malnutrition ?

\begin{solution}

Malnutrition is a condition that results from eating a diet in which one or more nutrients are either not enough or are too much such that the diet causes health problems. Every year 406,000 people die globally due to malnutrition. In economically impoverished country like Nepal, majority cases of health related issues arise due to undernutrition, rather than due to excess of nutrition. Although, it is touted that Nepal is an agricultural country and its plains a storehouse of granary, prevalance of nutritional deficiency (an important factor setting back Nepal's food security achievement) is staggering. Following are the main factors contributing to malnutrition:

\begin{enumerate}
\item Lack of nutritious diet
\item General public lack awareness on importance of nutritious diet
\item Lack of skills and techniques on cooking and food storage with maximum nutrient retention
\item Inability of properly constituting a diet despite availavility of range of food items
\item Lack of proper installments for safe storate of food
\item Due to lack of suitable supply system for remote hilly and mountainous regions, general scarcity of adequate food is observed
\item Lacking awareness on general importance of food
\item Campaigns aimed at awaring the public have not been effective.
\end{enumerate}
\end{solution}

\question What is the accounting system in practice in Nepal ? What are the features of double entry system of bookkeeping ?

\begin{solution}

An accounting system allows a business to keep track of all types of financial transactions, including purchases (expenses), sales (invoices and income), liabilities (funding, accounts payable), etc. and is capable of generating comprehensive statistical reports that provide management or interested parties with clear set of data to aid in the decision-making process.

The \textbf{new accounting system} is the present accounting system of government of Nepal which keeps the systematic record of all revenues and expenditures of the government offices performed through the bank. It is the systematic and scientific system for recording all the revenue and expenditures of government offices. It was implemented since 2019/20 in phase wise basis. In 1993 BS, Biratnagar Jute Mill used the double entry system for the first time in private sector. This system emphasizes on banking transactions and is based on double entry system, which keeps the record, according to budget heads in prescribed forms.

The objectives of new accounting system, as recommended by the Account Committee, 2017 are:

\begin{itemize}
\item Maintenance of systematic accounting of financial transactions
\item To provide information about funds and their utilization
\item Safeguarding physical properties
\item To make auditing simple and economical
\end{itemize}

Double Entry System Concept

If each and every financial activity is recorded by using the rule of debit and credit then such modern, systematic, scientific and fundamental concept of accounting is called double entry system. It has a two-fold effect on the accounting process. The double entry system is a modern system of bookkeeping based on duality principle propounded by Luca De Pacioli on 1494 A.D. from his book "Summa de Arithmetica" on "Accounting of Venice" chapter. Double entry system prevents accounting frauds errors.

Accounting principle in double entry system of bookkeeping is based on Equation \ref{eq:double-entry-equation} :

\begin{equation}
Assets = Equity + Liabilities
(\#eq:double-entry-equation)
\end{equation}

Features of double entry system of bookkeeping are:

\begin{enumerate}
\item It has a double effect of every financial transaction
\item Equal effect on both sides
\item A complete, scientific and reliable method of accounting
\item Helpful to prevent frauds and errors
\item Flexible for the correction in the process
\item Useful for internal control system
\item Concept of debit the receiver, credit the giver.
\item It keeps the full recording of economic transactions
\item Helpful to make final accounts
\item Easy to analyze and help to make comparable financial statements
\item Complex to understand, time-consuming, expensive and not suitable for small organizations
\item A universally accepted rule of accounting
\end{enumerate}
\end{solution}

\question What are the provisions in place for constituting a Press council in Nepal ?

\begin{solution}

The press council act, 2048 provisions under section 6 the following constitution of the council (The section has been edited in the course of enacting several other acts and laws since its first enactment; thrice in 2057 and twice in 2066) :

(1) Government of Nepal shall constitute a Council and the Council shall consist of the following persons,

\begin{itemize}
\item A retired Justice of the Supreme Court or a Senior Advocate or a person designated by Government of Nepal from among the persons who have rendered special contribution in the field of Newspaper --- Chairperson
\item Chairperson, Federation of Nepali Journalists --- Member
\item Six persons nominated by Government of Nepal in consultation with the Journalist Associations at the rate of two persons each from journalists, editors and publishers --- Member
\item One person nominated by Government of Nepal from among the working journalists --- Member
\item One person nominated by Government of Nepal from amongst the persons who have rendered distinguished service in the various fields including journalism --- Member
\item One person nominated by Government of Nepal from  amongst the journalists as recommended by Associations concerned with literary journalism --- Member
\item Director-General, Department of Press Information --- Member Secretary
\end{itemize}

(2) The tenure of office of the Chairperson and the members of the Council shall be Four years.

(3) If the Chairperson or any member desires to resign from his/her office before the expiary of his/her tenure, the Chairperson may submit his/her resignation in writing to the Government of Nepal and a member may submit his/her resignation in writing to the Chairperson.

\end{solution}

\end{questions}

\begin{questions}

\question What are the current acts and laws in Nepal ?

\begin{solution}
1. Nepali Language Publication Corporation Act, 2021 (1964)
2. Nepal Ship (Registration and Logbook) Act, 2027 (1971)
3. Nepal Special Service Act, 2042 (1985)
4. Non-resident Nepali Act, 2064
5. Passports Act, 2024 (1967)
6. The Consumer Protection Act, 2075 (2018)
7. Work Operation Fund Act, 2043 (1986)
8. Water Tax Act, 2023 (1966)
9. Nepal Treaty Act, 2047 (1990)
10. Supreme Court Act, 2048 (1991)
11. Regional Development Plans (Implementation) Act,2013 (1956)
12. Rajya Rajauta (Petty States and Rulers) Act, 2017 (1961)
13. Periodic Tax Recovery Act, 2012 (1955)
15. The University Grants Commission Act, 2050 (1993 A.D.)
16. The Stamp Duty Act, 2019 (1963)
17. The Pesticides Act, 2048 (1991)
18. Radio Act, 2014 (1957)
20. Act Restricting Investment Abroad, 2021(1964)
21. Act to Provide for Enhancement of the Circulation of Nepalese Currency, 2014(1957)
22. The Administrative Procedures (Regulation) Act, 2013 (1956)
23. Animal Health and Livestock Services Act, 2055 (1999)
24. Animal Slaughterhouse and Meat Inspection Act, 2055(1999)
25. Anti Defection Act, 2054 (1997)
26. Contingency Fund Act, 2016 (1959)
27. Drugs Act, 2035, (1978)
28. Nepal Tourism Board Act, 2053
30. Public Security Act, 2046 (1989)
31. Associations Registration Act, 2034 (1977)
32. AUDIT ACT, 2048 (1991)
33. banking-offence-and-punishment-act-2064-2008
35. Child Labor (Prohibition and Regulation) Act, 2056 (2000)
36. Commissions of Inquiry Act, 2026 (1969)
37. Infectious Disease Act, 2020(1964)
38. Immovable Property Requisition Act, 2013 (1956)
39. Human Trafficking and Transportation (Control) Act, 2064
41. The Copyright Act, 2059 (2002)
42. Development Board Act, 2013 (1956)
43. Domestic Postal Goods (Insurance) Act, 2019 (1962)
45. Foreign Investment Tax Act, 2019 (1963)
46. Judicial Fund Act, 2043 (1986)
47. Nepal Citizenship Act, 2063 (2006)
48. Essential Services Operation Act, 2014 (1957)
49. Export and Import (Control) Act, 2013 (1957)
50. Essential Goods Protection Act, 2012 (1955)
51. Extradition Act, 2045 (1988)
52. Legal Aid Act, 2054 (1997)
55. Nepal Agency Act 2014
57. International Financial Transactions Act, 2054 (1998)
58. National Judicial Academy Act, 2063 (2006)
59. Mother's Milk Substitutes (Control of Sale and Distribution) Act, 2049 (1992)
60. Compensation Relating to Torture Act, 2053 (1996)
61. Multimodal Transportation of Goods Act, 2063(2006).
62. National Trust for Nature Conservation Act, 2039 (1982)
63. Electricity Act, 2049 (1992)
64. Interpretation of Laws Act, 2010(1954)
65. Lottery Act, 2025 (1968)
66. Nepal Electricity Authority Act, 2041 (1984)
67. Constitutional Council (Functions, Duties, Powers and Procedures) Act, 2066 (2010)
70. Feed Act, 2033 (1976)
71. Jhora Area Land Act, 2028 (1971)
72. National Parks and Wildlife Conservation Act, 2029 (1973)
73. National Guidance Act, 2018 (1961)
74. Loan and Guarantee Act, 2025(1968)
75. Narcotic Drugs (Control) Act, 2033 (1976)
76. Motor Vehicle Tax Act, 2031 (1974)
78. Nepal Health Research Council Act, 2047 (1991)
79. Competition Promotion and Market Protection Act, 2063 (2007)
80. Evidence Act, 2031
81. Money Laundering Prevention Act, 2063 (2008)
83. Motion Picture (Production, Exhibition and Distribution) Act, 2026 (1969)
84. Arbitration Act, 2055 (1999)
85. Domestic Violence (Offence and Punishment) Act, 2066 (2009)
86. Donations Act, 2030 (1973)
87. National Cooperatives Development Board Act, 2049 (1992)
88. Insurance Act, 2049 (1992)
90. Aquatic Animal Protection Act, 2017(1960)
91. National Dairy Development Board Act, 2048(1992)
92. Explosives Act, 2018 (1961)
93. Essential Commodities Control (Authorization) Act, 2017 (1961)
94. Impeachment (Regulation of Procedure) Act, 2059 (2002)
95. Birth, Death and Other Personal Events (Registration) Act, 2033 (1976)
96. The Foreign Investment and Technology Transfer Act, 2019 (2075)
97. House and Land Tax Act, 2019 (1962)
98. The Industrial Enterprises Act, 2049 (1992)
99. Nepal Standards (Certification Mark) Act, 2037 (1980)
100. National Tea and Coffee Development Board Act, 2049 (1993)
101. Bonded Labour ( Prohibition )Act, 2058 (2002)
102. Diplomatic Privilege and Immunities of the Foreign States and Representatives Act, 2027 (1970)
103. The National Broadcasting Act, 1993
104. Industrial Enterprises Development Institute Act, 2053 (1996)
105. Lumbini Development Trust Act, 2042 (1985)
106. Act Prohibiting the Charging and Taking of Amount (Bhatti Charsa etc.) by Birta-holder on Birta, 2015 (1958)
107. Act Relating to Institutions Acting as Financial Intermediary, 2055 (1999)
108. Act Relating to Land of Jhora Area, 2028 (1971)
109. Nepal Agricultural Research Council Act, 2048(1992)
110. Agriculture and Forestry University Act, 2067 (2010)
111. Nepal Water Supply Corporation Act, 2046 (1989)
112. Nepal Trust Act, 2064 (2008)
113. Nepal Pharmacy Council Act, 2057 (2000)
114. Nepal Nursing Council Act, 2052 (1996)
115. Nepal Rastra Bank Act, 2058 (2002)
116. Nepal Medical Council Act, 2020 (1964)
117. Nepal Health Professional Council Act, 2053
118. Nepal Bar Council Act, 2050 (1993)
119. Nepal Law Commission Act, 2063 (2007 )
120. Nepal Airlines Corporation Act, 2019 (1963)
121. National Human Rights Commission Act, 2068 (2012)
122. National Insurance Corporation Act, 2025 (1968)
123. Nepal Administrative Staff College Act, 2020 (1982)
124. National News Agency Act, 2019 (1962)
125. National Foundation for Upliftment of Aadibasi/Janjati Act, 2058 (2002)
126. Nepal Music and Dance Academy Act, 2064 (2007)
127. Mines and Minerals Act, 2042 (1985)
128. Mediation Act, 2068 (2011)
129. Archives Preservation Act, 2046 (1989)
130. International Finance Corporations Membership Acquisition Act, 2022 (1965)
131. Corporations Act, 2021 (1964)
132. Black Marketing and Some Other Social Offenses and Punishment Act, 2032 (1975)
133. Caste Based Discrimination and Untouchability Offence and Punishment Act, 2068 (2011)
134. Forest Act, 2049 (1993)
135. Construction Business Act, 2055 (1999)
136. Bretton Woods Agreement Act, 2018 (1961)
137. Far-western University Act, 2067 (2010)
138. Negotiable Instruments Act, 2034 (1977)
139. Mid-western University Act, 2067 (2010)
140. Gorkhapatra Corporation Act, 2019 (1963)
141. Hotel Management and Sale and Distribution of Liquors (Control) Act, 2023 (1966)
142. The B. P. Koirala Institute of Health Sciences Act, 2049 (1993)
143. The Greater Janakpur Area Development Council Act, 2055 (1998)
144. Iodized Salt (Production, Sale and Distribution) Act, 2055(1998)
145. Amount and Governmental Contract Arrangement Act, 2020(1963)
146. Insolvency Act, 2063 (2006)
147. Land Acquisition Act, 2034 (1977)
148. Kathmandu University Act, 2048 (1991)
149. International Development Association’s Membership Acquisition Act, 2019 (1962)
150. Land Revenue Act, 2034 (1978)
151. Martyr Gangalal National Heart Disease Centre Act, 2057 (2000)
152. Lumbini Bouddha University Act, 2067 (2006)
153. Land (Survey and Measurement) Act, 2019 (1963)
154. Local Administration Act, 2028 (1971)
155. Local Development Training Academy Act, 2049 (1993)
156. International Centre for Integrated Mountain Development Act, 2040 (1983)
157. The Human Body Organ Transplantation (Regulation and Prohibition) Act, 2055 (1998)
158. The Guthi Corporation Act, 2033 (1976)
159. Ancient Monument Preservation Act, 2013 (1956)
160. The Electronic Transactions Act, 2063 (2008)
161. Armed Police Force Act, 2058 (2001)
162. Arms and Ammunition Act, 2019 (1962)
163. Ayurveda Medical Council Act, 2045 (1988)
164. The B.P. Koirala Memorial Cancer Hospital Act, 2053(1997)
165. Birta Abolition Act, 2016 (1959)
166. The Building Act, 2055
167. Nepal Chartered Accountants Act, 2053 (1997)
168. Citizen Investment Trust Act, 2047 (1991)
169. Commission for the Investigation of Abuse of Authority Act, 2048 (1991)
170. Communication Corporation Act, 2028 (1972)
171. Compensation Act, 2019 (1963)
172. The Lands Act, 2021(1964)
173. Construction Business Act, 2055 (1999)
174. Corporations Act, 2021 (1964)
175. Customs Act, 2064 (2007)
176. Decorations Act, 2064 (2007)
177. Education Act, 2028 (1971)
178. Electricity Theft Control Act, 2058 (2002)
179. Excise Duty Act, 2058 (2002)
180. Nepal Fine Arts Academy Act, 2064 (2007)
181. Privatization Act, 2050 (1994)
182. Water Resources Act, 2049 (1992)
183. Private Forests Nationalization Act, 2013 (1957)
184. The Social Welfare Act, 2049 (1992)
185. Notary Public Act, 2063
186. Right to Information Act, 2064 (2007 )
187. Trade Union Act, 2049 (1992)
188. Tax Settlement Commission Act, 2033 (1976)
189. Telecommunications Act, 2053 (1997)
190. Statistics Act, 2015 (1958)
191. Working Journalists Act, 2051(1993)
192. Wealth Tax Act, 2047 (1990)
193. Water Tariff Fixation Commission Act, 2063 (2006)
194. Water Supply Management Board Act, 2063 (2006)
195. Nepal Veterinary Council Act, 2055 (1999)
196. Ukhada Act, 2021 (1964)
197. Tribhuvan University Act, 2049(1992)
198. Town Development Fund Act, 2053 (1997)
199. Town Development Act, 2045 (1998)
200. Road Board Act, 2058 (2002)
201. Postal Act, 2019 (1963)
202. Partnership Act, 2020 (1964
203. Police Act, 2012 (1955)
204. The Patent, Design and Trade Mark Act, 2022 (1965)
227. Special Court Act, 2059 (2002)
228. [The] Kathmandu Valley Development Authority Act, 2045 B.S. (1988)
229. Technical Education and Vocational Training Council Act, 2045 (1988)
230. Summary Procedures Act, 2028 (1972)
231. Standard Measurement and Weight Act, 2025 (1968)
232. Sports Development Act, 2048 (1992)
233. Some Public Documents Authentication (Procedures) Act, 2063 (2006)
234. Solid Waste Management Act, 2068 (2011)
235. Soil and Watershed Conservation Act, 2039(1982)
236. Social Practices (Reform) Act, 2033 (1976)
237. Ship Registration Act, 2027 (1971)
238. Senior Citizens Act, 2063 (2006)
239. Seeds Act, 2045 (1988)
240. Tourism Act, 2035 (1978)
241. Tobacco Products (Control and Regulatory) Act, 2068 (2011)
242. [The] Ownership of Joint Housing Act, 2054 B.S. (1997)
243. Security of the Health Workers and Health Organizations Act, 2066 (2010)
244. Secured Transaction Act, 2063 (2006)
245. Scholarships Act, 2021 (1964)
246. Revenue Tribunal Act, 2031 (1974)
248. Securities Act, 2063 (2007)
249. Press Council Act 2048 (1992) 
250. Patan Academy of Health Sciences Act, 2064 (2008)
251. The Prevention of Corruption Act, 2059 (2002 A.D)
252. Purwanchal University Act, 2050 (1994)
253. Public Service Commission Act, 2066 (2010)
254. Public Roads Act, 2031 (1974)
255. The Public Procurement Act, 2063 (2007)
256. Public Debt Act, 2059 (2002)
258. Prisons Act, 2019 (1963)
261. Remuneration, Conditions of Service and Facilities of the Authorities of the Constitutional Bodies Act, 2053 (1997)
265. Press and Publication Act, 2048 (1991)
266. Poverty Alleviation Fund Act, 2063 (2006)
267. Pokhara University Act, 2053 (1996)
268. Plant Protection Act, 2064 (2007)
269. Nepal Petroleum Act, 2040 (1983)
270. Pasture Land Nationalization Act, 2031 (1974)
271. Mutual Legal Assistance Act, 2070 (2014)
272. Judicial Council Act, 2073 (2016)
273. Employee Provident Fund Act, 2019 (1962)
274. An Act to Regulate and Control International Trade in Endangered Wild Fauna and Flora
275. Administration of Justice Act, 2073 (2016)
276. Pashupati Area Development Trust Act, 2044 (1987)
277. Karnali Academy of Health Sciences Act, 2068 (2011)
278. Nepal Health Service Act, 2053 (1997)
279. Army Act, 2063 (2006 )
280. Civil Service Act, 2049 (1993)
281. Motor Vehicles and Transport Management Act, 2049 (1993)
282. Passports Act, 2024 (1967)
283. The Crime Victim Protection Act, 2075 (2018)
284. The Privacy Act, 2075 (2018)
285. The Public Health Service Act, 2075 (2018)
286. The Right to Employment Act, 2075 (2018)
287. The Act Relating to Rights of Persons with Disabilities, 2074 (2017)
288. The Right to Food and Food Sovereignty Act, 2075 (2018)
289. The Right to Housing Act, 2075 (2018)
290. The Right to Safe Motherhood and Reproductive Health Act, 2075 (2018)
291. The Social Security Act, 2075 (2018)
292. The Act Relating to Children, 2075 (2018)
293. The Act Relating to Compulsory and Free Education, 2075 (2018)
294. Bank and Financial Institution Act, 2073 (2017)
\end{solution}

\question Discuss about the importance of environment on human health.

\begin{solution}
About one quarter of the diseases worldwide can be accredited to environmental causes, with 40\% of the sufferers being children under five.

Among the ten most significant dangers to the developing countries with high-mortality rate are unsafe water and sanitation and hygiene problems. Just about 80 per cent of each and every type of infectious disease is caused by unclean water. Globally, 1.1 billion people lack access to safe water supply and 2.4 billion to adequate sanitation.

In East Asia and the Pacific, 48 per cent of the population have access to improved hygiene while in South Asia, merely 37 per cent have such access. Inadequate water and insufficient hygiene lead to ill health.

Over 200 million people in nine Asian countries, more often than not living in rural areas, are at risk of arsenicosis, cancer and eventual death from the long-term use of groundwater infected with arsenic.

Arsenic toxicity has a pervasive effect on all systems in the body and long-term consequences on children, slowing their cognitive expansion and cerebral ability. There is no known medical cure for arsenicosis. The only sure way of preventing arsenicosis is to avoid drinking impure water. Furthermore, extreme fluoride in water causes dental and skeletal fluorosis. Lead emissions are also a serious problem in the region.

In the Asian and Pacific area, indoor air contamination poses the uppermost health risk. Contact with smoke from solid fuel like wood, dung, coal and agricultural remains increases the amount of contamination. Indoor air pollution causes an accumulation of pollutants, such as coarse and fine particulate matter, carbon monoxide, oxides of nitrogen, benzene, toluene and formaldehyde, in the bodies of those exposed to indoor air pollution. Epidemiological evidence suggests a link between indoor air toxic waste and respiratory infections, TB, cancers, low birth weight and greater infant and prenatal mortality. 

Nepal's performance seems to be worst when it comes to protecting environment and combating air pollution. Nepal is among the bottom five countries on the Environmental Performance Index 2018, plummeting 27 points from 149 in 2016, according to a biennial report by Yale and Columbia Universities along with the World Economic Forum. Air pollution in Nepal, particularly in the Kathmandu Valley, has emerged as a serious environmental health risk.

Rapid urbanisation, unplanned development activities, smoke from brick kilns, ongoing road widening drive and construction works for the Melamchi Water Supply project and increasing number of vehicles have contributed in making Kathmandu one of the most polluted cities in the world.

Furthermore, the concentration of particulate matter is observed higher during night in winter because of the formation of inversion layer which acts as the blanket to trap pollutants. The Particulate Matter (PM2.5) concentration in Kathmandu is five times more than the National Ambient Air Quality Standard of Nepal set by the government, and way more than the World Health Organisation (WHO) standard.

Most of air pollution-related deaths are from non-communicable diseases and in terms of global disease burden, air pollution is the cause of over one-third deaths from stroke, lung cancer and chronic respiratory diseases, says the WHO. One-quarter of deaths occur due to ischemic heart disease. According to a WHO report, nearly 740 people died from acute lower respiratory infection, 1,770 from chronic obstructive pulmonary disorder, 932 from lung cancer, 3,328 from ischemic heart disease and 3,183 from stroke in Nepal in 2016.

However, the number of vehicles being registered in Kathmandu is rapidly increasing. Weak institutions, corruption and lack of technology are also adding to Kathmandu’s air pollution. One of the key issues is monitoring of air quality by using standard, good quality and practically identical strategies and instruments.

WHO points to a lack of reliable public transport system. Transport system needs to be strengthened and alternative mode of transport such as cycling for short routes must be encouraged by creating safe cycling routes. In Kathmandu, 41 per cent of people travel by foot while 2 percent people use bicycles. So, walking and cycling should be made more convenient.

Apart from its instant toxic and carcinogenic effects, air contamination affect the environment and health in other ways. Some air pollutants descend as acid rain. Acid rain causes ecological degradation which impacts ecosystems, increasing health hazards. 

Ozone depletion, associated with use of ozone-depleting chemicals, is expected to augment UV-B radiation, resulting in the oppression of immune systems and skin cancer. In South East Asia, 70 million people are seasonally affected by air pollution due to forest fire.

A number of pesticides are associated with cancers, miscarriages and inborn malformations. Agrochemical poisoning and agro-machinery accidents cause diseases, injuries and death that are underreported.

Small-scale farmers are especially vulnerable to the exposure to chemical fertilisers and pesticides that are widely used in the region, and to equipment-related hazards aggravated by sustained hard physical labour with old and poorly maintained gear.

A lot of new infectious diseases have emerged because viruses have jumped the species fence from flora and fauna to humans. Undeveloped production systems, in particular intensive animal husbandry in densely populated areas, with livestock in close proximity to humans, are the perfect breeding ground for new diseases.

SARS as well as avian influenza are fresh examples. These diseases affect not only humans, but also flora and fauna and vegetation. They also threaten food safety and livelihood. Thus, these diseases have themselves turned out to be drivers of environmental alteration.

A notorious issue in foodstuff production is the use of genetically modified organisms. There is vigorous global debate on the large-scale use of genetically modified organisms in developed countries when their long-term penalty on human health has not been well-known.

Plastic is extensively used for wrapping food. These substances could be released if ingested. Vast quantities of microscopic plastic fragments are building up in oceans. The accumulation of plastic wreckage in parts of the central Pacific Ocean is six times greater than that of resident plankton, the very foundation of the food chain. There is indication that plastic debris is being ingested by marine organisms and might go into the food chain.

Haphazard waste disposal is a chief health danger. Non-biodegradable plastic waste constitutes a main part of waste. Plastic floats in water; it accumulates and absorbs toxic hydrophobic chemicals from other sources. Artificial waste also clogs sewerage systems, causing severe hygiene problems.

In spite of some progresses made since the Basel Convention on the Trans Boundary Movement of Hazardous Waste came into force, large amounts of hazardous waste, including electronic waste, are still exported to developing countries in the region. Recycling is often absent and the burning of plastic and dumping are common.

The unsafe disposal of hazardous domestic medical and manufacturing waste pose severe health risks to people in the region. Governments in the region should pay serious attention to ecological health.

\end{solution}

\question Explain about soil erosion, status and its consequences for Nepal. 

\begin{solution}
According to a United Nations-backed study, a third of the planet's land is severely degraded and fertile soil is being lost at the rate of 24 billion tonnes a year. In Nepal, the situation is even worse because two-thirds of the country's total area is geologically fragile where soil erosion is exceedingly high. Topsoil loss has been reported as high as 87 tonnes per hectare per year on sloping terraces. When the top soil is lost, the land is degraded.

Poor land management in Nepal has caused soil erosion each year with impacts not just on food production but also on biodiversity loss, carbon loss and disaster resilience. Forecasts on land in South Asia indicate that countries like Nepal will have to face the greatest challenges if better land regulation and improved farming technologies are not put in place.

When farmland is ploughed and tilled, the exposed topsoil is often blown away by wind or washed away by rain. Erosion due to faulty practices in crop production, for example, has resulted in the loss of millions of tonnes of topsoil every year. This leads to reduced soil fertility and degraded land.

Unscientific farming in the hills (steep slope) is one of the causes of soil erosion in Nepal. Shifting cultivation and unnecessary tillage practices also lead to land degradation and damage the ground vegetation and natural ecosystems. Cultivation on the steep slope without taking improved farming practices such as terracing, selection of appropriate crops and use of organic manures into consideration have contributed to increased soil erosion. Furthermore, agricultural intensification produces certain by-products and side effects that are unfriendly to the environment. Ways must, therefore, be found to minimise the effects of these by-products and side effects on the quality of soil.

Maintenance and enhancement of soil fertility are vital for food security and environmental sustainability. Ecologically sound agroforestry systems such as inter-cropping and growing tree crops in the sloppy lands can be helpful for the sustainability of farming. Many farming practices have been developed to improve efficiency in the use of resources and strengthen research on sustainable agriculture in developed countries and have made us hopeful about scientific and technological innovation in the management of soil.

The practice of tilling sloped land along lines of consistent elevation in order to conserve rainwater and to reduce soil losses from surface erosion is called contour farming. It acts as reservoirs to catch and retain rainwater, thus permitting increased infiltration and more uniform distribution of water. The contour farming is a traditional practice in the hilly areas of Nepal.

Another good practice to control soil erosion is the creation of windbreakers by planting evergreen trees around farmland in windy areas like Mustang. It helps prevent the wind blowing away the soil from the farmland. Windbreakers also help in protecting crops from damage caused by strong and severe wind and improve plant health, quality and yield. Crops protected from wind are able to retain significantly more moisture. Matting is the process of covering the soil with biodegradable materials that include mulch, straw, coconut fibre and wood chips. These are held together with biodegradable netting made from coco coir.

Crop rotation with non-hosts of the pathogens that require control is considered one of the most important cultural factors for reducing overall disease problems of crops as well as minimising soil erosion. Beneficial organisms can be added directly, or the soil environment can be made more favourable for them through use of compost and other organic amendments. Soil pH, calcium level, nitrogen form and the availability of nutrients can all play major roles in soil disease management. Adequate crop nutrition makes crops more tolerant of or resistant to disease.

Trees are often considered to be the universal answer to control soil erosion. Tree roots help prevent landslides on steep slopes and streambank erosion. Horticultural crops, particularly fruit trees, have positive implications for the future development of mountain agriculture in terms of minimising soil erosion, harnessing mountain niches and comparative advantages.

Agro-forestry is a sustainable land use system and practice in which woody perennials (trees, shrubs) are grown with herbaceous annuals (crops, pasture grass). It supports the livelihood of billions of people worldwide and provides a wide range of products such as food, fuel, fibre, fodder and forage for livestock. Even the landless farmers sustain their livelihood with this system.

According to a case study of agro-forestry from the mid-hills of Nepal, it is possible to earn Rs 45,490 per hectare from carbon sequestration per household if a payment scheme is introduced. It prevents the further degradation of the undulated fragile land of hilly areas.

Soils and agro-ecosystems are essential for sustainable production, hence farmers, social workers, politicians and agriculturists should come together to develop soil management strategies for sustainable production. Farmers should try to keep their farmland productive for generations to come.
\end{solution}

\question What are the provisions in Nepal relating on the "Right to Information" ? Discuss in detail.

\begin{solution}
Government of Nepal enacted the Right to Information Act, 2064 (2007)

\textbf{Preamble}

1. To make the functions of the state open and transparent in accordance with the democratic system and to make responsible and accountable to the citizen
2. To make the access of citizens simple and easy to the information of public importance held in public bodies
3. To protect sensitive information that could make adverse impact on the interest of the nation and citizen, and for the necessity to have legal provisions to protect the right of the citizen to be well-informed and to bring it into practice.

\textbf{Right to information}

1. Every citizen shall have the right to information subject to RTI act.
2. Every citizen shall have access to the information held in the public bodies.

\textbf{Provision regarding commission}

1. An independent national information commission will be established for the protection, promotion and practice of right to information.
2. A Chief Information Commissioner and two other information commissioners will be in the commission.
3. In order to appoint Chief Information Commissioner and Information Commissioners, there will be a committee comprised as follows:
  a. The speaker -- Chairman
  b. Minister of state minister for information and commission -- Member
  c. President, federation of Nepalese journalists -- Member
4. The Government of Nepal on the recommendation of the Committee under Sub-Section (3), will appoint a Chief Information Commissioner and Information Commissioners; while appointing in this way, at least one female will have to be included.
5. The Committee in accordance with Sub-Section (3) will follow inclusive principles as much as possible with recommending for appointment of Chief Information Commissioner and Information Commissioners.
6. The procedures of recommendation in accordance with Sub-Section (3) will be as determined by the Recommendation Committee itself.

Why RTI

RTI Act 2007 gives you the right to ask for and receive information about any activity from a public body. Public bodies include the following entities:

1. Bodies formed under the constitution
2. Bodies established by the Act
3. Bodies constituted by the government of Nepal
4. Public service provider organizations or foundations established as per the law
5. Political party and organization registered under prevalent laws
6. Organized institutions under the full or partial ownership or under control of the GoN, or organized bodies receiving grants from the GoN
7. Organized institutions formed by the Bodies established by the GoN or any other agencies lawfully formed through an agreement
8. NGOs/Institutions directly or indirectly funded by the GoN or foreign government or international organizations/institutions
9. Other bodies or institutions defined as public bodies by the GoN through a notice published in Nepal gazette.

The seeker of information has to submit a written application to the concerned information officer. It is important for the applicant to clearly specify the information sought. Unclear requests make things difficult to provide correct information. Hence, requests for information should be as clear and specific as possible.

No fees will be charged for the first half hour of monitoring in public bodies or getting information from work place, getting records, or undertaking records inspection and observation. After that the charge in Rs 50 per person, per hour. Likewise, there are no fees for inspection in public libraries and public places where information is made available.

Public bodies will nominate a staff as an information officer for the public's ease of access to information. The head of the office should provide information to the PIO to disseminate it in accordance to sub-section (I) of RTI act. An information section will be set up in all public bodies to disseminate information. The PIOs regularly update their information and keeps records regarding their work plans, expenditure, financial transactions, rules, regulations, laws, and directives. The RTI act anticipates that public bodies store (archive) their information going as far back as 20 years from the commencement of the RTI act. Unless there are resonable and sufficient grounds to validate those exceptions, public bodies cannot evade the responsibility to disclose information. Following information, however, shall not be obliged to be made available:

1. Information harmful to soverignty, integrity, national security public security, law and order of the country; and information that can jeopardize international relations;

2. Information that could have direct bearing on research, investigation and prosecution of a criminal case

3. Information harmful to economic, financial, monetary wellbeing or posing threat to someone's intellectual property rights, as also to banking and financial secrecy.

4. Information that could jeopardize the harmonious realations subsisting between various castes and communities.

5. Information posing threat to a person's right to privacy, personal security, health and property.


In case decision rendered by the Chief of Public body is not satisfactory, one can file the appeal (within 35 days of decision received) to the commission either by directly approaching the commission office or getting it registered in the concerned office or through the concerned District Administration Office. Alternatively, one can also mail the appeal directly to NIC, via any postal services.

Centre for Law and Democracy, Canada has published a comparative study report on existing RTI laws of 111 countries in the world, in which Nepal has been ranked 27th in the world with the score of 104 out of 150. The worldwide experience shows that RTI supports good governance and helps to reduce corruption. The National Information Commission had completed its first RTI Audit in 2016 through ex-secretaries of the government. The second RTI Audit was completed in 2017 through senior journalists.

After analysing all aspects, it was found that 11 ministries (35%) were found working as per law. Similarly, 20 ministries (65%) were partially satisfactory. The commission has made 10 suggestions, including adding "imparting information" in Article 27 of the constitution, taking out of the word "secret" from the employees' oath, amongst other, to the government on the basis of the results of this RTI audit.

\end{solution}

\question What is civil society ? Mention its role in good governance ?

In Nepal, the term civil society (Nagarik Samaj) has become very popular and hit the popular psyche with a comprehensive magnitude. Not only non-governmental organisations but even private and business organisation and corporate bodies often tend to claim themselves as being a part of the civil society.

It includes the entire range of organised groups and institutions. These institutions should be independent of the state. They should be voluntary, and at least to some extent self-generating and self-reliant. These, of course, include not only non-governmental organisations but also independent mass media, think tanks, universities, and social and religious groups.

Pluralism, diversity

In fact, to be part of the civil society, groups must meet some other conditions as well. In a democracy, civil society groups should have respect for the law, for the rights of individuals, and for the rights of other groups to express their interests and opinions.  In fact, the word "civil" implies tolerance and the accommodation of pluralism and diversity.

An important prerequisite for civil society groups is that they must keep and preserve their autonomy and independence of the state and private sector.

The first and most basic role of the civil society is to limit and control the power of the state. Of course, any democracy needs a well-functioning and authoritative state. Civil society actors should watch how state officials use their powers. They should raise public concern about any abuse of power. They should lobby for access to information, including freedom of information laws, and rules and institutions to control corruption.            

This constitutes a second important function of civil society:  to expose the corrupt conduct of public officials and lobby for good governance reforms. Even where anti-corruption laws and bodies exist, they cannot function effectively without the active support and participation of civil society. In this regard, the role of civil society organisations in Nepal has been very poor and lukewarm.

Moreover, civil society should help to promote political participation. NGOs can do this by educating people about their rights and obligations as democratic citizens, and encouraging them to listen to election campaigns and vote in elections. NGOs can also help develop citizens' skills to work with one another to solve common problems, to debate public issues and express their views.

Moreover,  civil society organisations can help to develop the  values of democratic life. The values of democratic life are tolerance, moderation, compromise and respect for opposing points of view. Without this deeper culture of accommodation, democracy cannot be stable. These values cannot simply be taught; they must also be experienced through practice.

The civil society can also help to develop programmes for democratic civic education in the schools as well. In Nepal, as we are at a very crucial stage of implementing the new  federal constitution, we need to inculcate the values of tolerance and accommodation in the citizens. The civil society organisations can be tapped for this very purpose.

What can be said is that the  civil society is an arena for the expression of diverse interests, and one role for civil society organisations is to lobby for the needs and concerns of their members, as women, students, farmers, environmentalists, trade unionists, lawyers, doctors and so on. NGOs and interest groups can present their views to the parliament and local governments by contacting individual members and testifying before parliamentary committees. They can also establish a dialogue with relevant government ministries and agencies to lobby for their interests and concerns.

Civil society is not simply to be in tension with the state. Just because civil society is independent of the state doesn't mean that it must always criticise and oppose the state. In fact, by making the state at all levels more accountable, responsive, inclusive, effective - and hence more legitimate - a vigorous civil society strengthens citizens' respect for the state and promotes their positive engagement with it.

A democratic state cannot be stable unless it is effective and legitimate, and has the respect and support of its citizens.  Civil society is a check, a monitor, but also a vital partner in the quest for this kind of positive relationship between a democratic state and its citizens.

The  civil society can strengthen democracy and provide new forms of interest and solidarity that cut across old forms of tribal, linguistic, religious and other identity ties. Democracy cannot be stable if people only associate with others of the same religion or identity. When people of different religions and ethnic identities come together on the basis of their common interests as women, artists, doctors, students, workers, farmers, lawyers, human rights activists and environmentalists, civic life becomes richer, more complex and more tolerant.

Parochial interests

However, in Nepal, the real danger lies in the fact that the political parties have promoted primordial identities so intensely that the ethnic groups have started to keep focus on their narrower and parochial interests. This will hurt the process of democracy building and state reorganisation in line with the provisions of the Constitution of Nepal.

\end{questions}
