# Public relation and political science

## Public policy

Public policy is the process by which governments translate their political vision into programmes and actions to deliver outcomes.

In his book 'Advanced Introduction to Public Policy', B. Guy Peters defines public policy as "the set of activities that governments engage in for the purpose of changing their economy and society", effectively saying that public policy is legislation brought in with the aim of benefiting or impacting the electorate in some way.

Author B. Dente in his book 'Understanding Policy Decisions' explains public policy as "a set of actions that affect the solution of a policy problem, i.e. a dissatisfaction regarding a certain need, demand or opportunity for public intervention. Its quality is measured by the capacity to create public value."

Democracy itself is a public philosophy driven by rule-governed leaders desiring to fulfil public needs and rights. Leaders acting solely for private gain devoid of public concern lose legitimacy. Effective leaders concert actions by crafting policies and mobilising human and material resources to achieve public goals whether it is managing public security, reducing poverty, supplying foods, health, education, drinking water, energy, unsettled accounts, or control epidemics. Public policy focuses on the decisions that create the outputs of a political system, such as transport policies, the management of a public health service, the administration of a system schooling and the organization of a defence force. The public problems that influence public policy making can be of economic, social, or political nature.

Rational choice theory, or now more frequently known as evidence-based policy, argues that focusing on scientific evidence, instead of history and culture, should guide our public policy making.

Public policy making can be characterized as a dynamic, complex, and interactive system through which public problems are identified and resolved by creating new public policy or by reforming existing public policy.

Public policy making is an exhausting and time-consuming 'policy cycle'. The basic stages of policy cycle are as follows;

- a problem is identified, 
- a policy response is formulated, 
- the preferred solution is then selected and implemented, and 
- finally the policy is evaluated. 

However, the evaluation stage takes an in depth look into what can be learnt from the process as a whole, whether the original problem has been solved, and if not, what is recommended as an alternative course of action. Thus, returning policy makers to the very first step; the identification. 

In public policy making, numerous individuals, corporations, non-profit organizations and interest groups compete and collaborate to influence policymakers to act in a particular way. The large set of actors in the public policy process, such as politicians, civil servants, lobbyists, domain experts, and industry or sector representatives, use a variety of tactics and tools to advance their aims.

Public policies come from all governmental entities and at all levels: legislatures, courts, bureaucratic agencies, and executive offices at national, local and state levels. Many actors can be important in the public policy process, but government officials ultimately choose public policy in response to the public issue or problem at hand. In doing so, government officials are expected to meet public sector ethics and take the needs of all project stakeholders into account. It is however worth noting that what public policy is put forward can be influenced by the political stance of the party in power.

Since societies have changed in the past decades, the public policy making system changed too. In the 2010s, public policy making is increasingly goal-oriented, aiming for measurable results and goals, and decision-centric, focusing on decisions that must be taken immediately. Furthermore, mass communications and technological changes such as the widespread availability of the Internet have caused the public policy system to become more complex and interconnected.

**Framework for public policy formulation in Nepal**

- Constitution of Nepal is the major source which provides guidance to define the frame of public policy formualtion in Nepal.
- The provisions of preamable which are not subject to changes;
- Provision of constitutional commissions;
- Theory of separation of power; and
- Guiding principles of the state have provided the government with a framework for policy formulation.

**Factors influencing public policy formulation in Nepal**

- Policy guidance as visualized and framed in the constitution
- Political vision reflected in the election manifesto of political parties
- Philosophical/ideological ground setting the political culture of the political parties
- Public agencies and bureaucracy
- Development partners' interests
- Economic actors: market, private sectors and agencies of globalization
- Key economic/fiscal (Ministry of Finance) and development planning (National Planning Commission) agencies
- Pressure groups and minorities' stakeholders
- Elites and community leaders
- Voters, the common people
- Professional institutions
- Resources

**Gaps in policy making**

A set of inter-related issues that limit the effective policy process in Nepal are:

- Defining policy problem properly is undermined to existing practice of individual decision making.
- Limited professional capacity, knowledge, skill and integrity in policy making
- Various pressure groups, I/NGOs and elites dominate over the public interest
- Policy making based on personal perception and lack of institutional homework and preparation.
- In many other instances, undue political influences also affect the policy process.
- Practice of imitating policy substances from the other countries without realizing the different domestic needs and context.
- Influenced by international agencies which may not reflect the welfare of the country.
- Substantially influenced by the policy changes in India owing to the deepened political, economic, cultural relationship and open border.
- Coordination and management of the stakeholders and neutral buereaucracy which are critical for the effective policy process are poor.
- Inadequate communication of the policy provisions, ineffective monitoring and evaluation mechanisms limit effective policy management practice in Nepal.

The failure of each public policy in Nepal to achieve the goals can be credited to policy makers’ skill on means, not ends, to link technical knowledge to desirable collective action. The uncanny challenges faced by Nepal at multi-level governance follow the same legacy breeding unequal effects on various spaces. Administrative blockage, political factionalism and social movements continue to strain the state’s outreach and exercise authority in society vital to the art of governance. Without a pluralistic policy consensus, improving the lives of Nepalis lingers.

The ability of Nepali state to attain autonomous capacity to formulate public policy rests on social learning aptitude of policy makers and skill in cleaning the imported policies and ideologies so that they fit people’s knowledge, needs and legitimate institutions, such as community, local governance and parliament to musters their ownership and stake. So far Nepali policy makers have diagnosed the nation’s problem of progress by disciplinary angle of single-cause determinant - traditional society, landlocked position, dependency, intellectual marginalisation, centralisation of power, gender inequality, social hegemony, fatalism, population growth, migration of youth, economic liberalisation, aid conditionality, etc. and prescribed corresponding solution. Latest fads of number-crunching growth, structural adjustment and SDGs as shorthand for progress in no way provide guarantee for maximising welfare gains given dismal growth of labour market. Worse still, each policy discipline contests the knowledge of the other rather than engages in mutual learning to situate the policy in the Nepali context and duly reform it through social feedbacks.

Public policy has now moved beyond 'rational choice' to impact assessment at various spheres—ecology, politics, society and security. It has offered judicious roles for Nepali state in infrastructure, public goods, justice and regulatory regime in which it can determine and enforce the rule of law and equip leaders to endorse binding measures of public policy on what works. Since majority of Nepalis stands between the capital and the labour, policy response for progress must capture the middle ground by accepting the power of global market to spur innovation, efficiency, competition, investment and productivity growth in a framework of welfare state.

Obviously, progress can be achieved only if contribution of each actor fists into the polity, makes everyone connected through social inclusion which also minimises the losers. The stability of democratic polity rests on the supply of public goods. Nepal’s commitment to human rights, humanitarian laws and constitution prompt the leaders to formulate and coordinate policies, allow elected bodies to mediate them and balance the public, private and cooperative sectors based on their relative gain. The pursuit of justice of Nepalis spurs an intrinsic right to human dignity. An economy cannot grow without social support and ecological sustainability. Coping with change entails Nepalis lifelong learning of problems and formulation and execution of correct public policy. As their lives have become increasingly complex, only a free discourse of diverse options can help evolve a systemic view on public policy.

\begin{questions}

\question What is good governance ?

\begin{solution}

There are various definitions of the term \textit{good governance}. These definitions are based on normative assumptions about how decisions should be made within organizations and the functioning of formal and informal structures for implementing such decisions. The UN Commission on Human Rights identifies transparency, responsibility, accountability, participation, and responsiveness as key attributes of good governance. By linking good governance specifically to human rights and sustainable development, the UN explicitly recognizes that governance issues are global in nature and consequently require more nuanced and integrated approach. 

Good governance is a process of executing a coherent governing plan for the nation based on the interests and priorities of the people. It purports to create a just society based on the principles of inclusiveness, liberty, equality and cooperation. Those in office, especially the elected ones, must represent the concerns, values and needs of the people and empower them through the realization of their basic rights, including the right to development and self-determination, by developing their access to markets, assets, goods and services and institutions. In the post-modern society, citizens' ability to articulate their needs to those in power lies in a transparent communication process. This process needs to provide them proper access to the institutions of governance, the media and expert policy dialogues that affect their lives. This is the way sovereign citizens can make the governing power transparent and accountable. Good governance equally needs self-discipline and integrity of those in power, the corporate sector and civil society.

The Canadian International Development Agency defines good governance as "the exercise of ower by an organization (or government) in an effective, equitable, honest, transparent, and accountable way". This approach to governance focuses on how organizations are directed, controlled and shown to be acting responsibly.

Good governance thrives on a rediscovery of common grounds on which the elite --political leaders, bureaucracy, businesspersons and ordinary citizens-- agree on the core public issues and shape their respective courses of action. In a polyglot population, the architecture of good governance rests on the sound legitimacy of governors which is possible only in a climate where there is broad representation of social interests and where a heritage of pride in social pluralism combines with an honor for culture, family, education and statecraft. A great degree of fairness during election and a broad-based representation of diverse sections of people are required to establish the legitimacy of leaders. It is this legitimacy that provides a kind of public order in the system. Yet, a system can only become stable if the society becomes wealthy enough to overcome the tumult arising out of various political, ideological, social and religious convictions. Modernization also requires a reform in the entrenched work ethics that deprecates manual labor. Such ethics comes from a feudal tenure system that fosters share tenancy and exploits the peasants and workers which prevents the transformation of a largely agrarian society into a modern and prosperous one.

UNDP defined good governance as: Good governance is (the striving for) rule of law, transparency, responsiveness, participation, equity, effectiveness and efficiency, accountability and strategic vision in the exercise of policical, economic and administrative authority.

The UNDP (1997) articulates eight principles of good governance. These principles are:

\begin{enumerate}
\item \textbf{Equality of participation in decision making.} All people, irrespect ve of sex, class, or race should be heard and allowed to participate in deliberations that affect them directly or indirectly. In democratic societies, citizens can participate in various ways, ranging from voting to involvement in acts of civil disobedience. In many instances, participation must be informed and organized through civil society actors who can often leverage resources more successfully. Good governance implies that organizations encourage participation from those who may both benefit or be harmed by any decisions taken. Participation also means that individuals have the rights of freedom of association and expression, and to participate in organized civil society without fear of retribution or the stigma of being labeled unfairly as a "special interest" group.
\item \textbf{Organizations must be responsive to the needs of all stakeholders in a reasonable timeframe.} On one level, this means that organizations must hire, train, and retain employees to achieve optimal response time and high quality outcomes. On a more general level, organizations must ensure that they have the capacity, and in some cases the autonomy, to implement changes to structure and management systems to maximize efficiency.
\item \textbf{Organizations must mediate differences between stakeholders to reach a broad consensus.} Good governance requires that organizations involved in divisive issues like abortion, stem-cell research, human cloning, euthanasisa, etc. enter such debates in the spirit of cooperation and mediation. To achieve this goal, organizations must treat all stakeholders consistently and fairly.
\item \textbf{Organizations must be accountable to the stakeholders they serve.} Good governance requires a broad definition of who such stakeholders may be. Many organizations limit intentionally the list of those they define as valid stakeholders to narrow the scope of decision-making authority, the range of topics addressed, and the nature of the decisions that are made. In general, organizations should be accountable to those affected by the entire range of decisions or actions made and implemented by an organization.
\item \textbf{Organizations must strive for transparency in their decision-making processes so that interested parties can understand the bases of decisions and monitor progress.} Good governance requires that organizations justify decisions made by demonstrating how such decisions respect the precedent from previous decisions.
\item \textbf{Organizations must work within legal frameworks that are crafted in fair ways, enforced impartially, and attuned to human rights issues.} Good governance means that a country’s legal environment should be conducive to development. Investors must feel comfortable that due process will be followed in all countries of interest, and that a wide range of issues including protection of intellectual property, fair application of trade subsidies and sanctions, and a regulated financial marketplace exist. Organizations must also follow the laws of the land and ensure that all decisions made are consistent with such laws.
\item \textbf{Decisionmakers should have a broad and long-term vision on how to better the processes of governance to ensure continued economic and social development.}
\item \textbf{Good governance involves guaranteeing the rights of all individuals to maintain and improve their well-being in an equitable and inclusive manner.} This principle conveys the message that good governance is about stewardship and care and that it involves the highest ethical positioning possible.
\end{enumerate}

Clearly, good governance is more political than technical in nature and emphisizes the primacy of equality and the value of vision, strategic thinking, and planning. Good governance is a tool for making organizations work more effectively in a world where trust is declining in government, industry, science, and other institutions. Good governance is based on democratic values that stimulate administrative reforms that affect a range of organizations.

The World Bank has compiled a list of six dimensions of public-sector governance that are used in an aggregate fashion to measure the quality of governance: voice and accountability, political stability and absence of violence, government effectiveness, regulatory quality, rule of law, and control of corruption. As new global standards of governance emerge, indicators like these can be used to diagnose failures and to suggest solutions to a range of performance and process issues.

Good governance is an ideal that is difficult to achieve. Although it is essential for ensuring national prosperity by increasing acccountability, reliability, and predictability of decision making in governments, corportations, and non-governmental organization. To ensure that good governance prevails, elected representatives, corporative executives and boards of directors, professional bodies, and civil society groups need to become more active in learning about the perils associated with "bad" governance (social inequality, development failures, and corporate scandals) and push for stronger laws and policies that protect the public interest.

Founding concept of good governance for Nepal began with the description of \textit{Ram Rajya}, meaning the ideal state. Vedic norms and values of Nepal were guided by this philosophy. As a model figure in statemanship, Ram, an ancient king of south asia, is famous in eastern society. He is well known for sacrificing his much loved wife addressing the public. Governance comprises the mechanisms, processes and institutions through which all the stakeholders, viz., the state, private sector, civil society and citizens articulate their interests.

Following series of events can be identified to have institutionalized the issue of good governance in Nepal:

\begin{itemize}
\item Before 1950s the developing countries' governments oversaw as their major responsibility the task of promoting peace and security and tax collection. After the second world war the focus shifted on the development management. Likewise, the developed countries showed interest in supporting lesser developed ones.
\item Developed countries offered support indifferenty of the aidee country's diversity and the receiver country could not execute planned development programmes due to variety of socio-economic problems.
\item During 1980 it was acknowledged that donor countries should alter their policies regarding development aid while the receiver country should strieve to resolve socio-economic hurdles.
\item For the purpose of maximum utilization of foreign aid, donor countries prepared an Aid Agenda which included good governance as a criteria for granting the support.
\item It was first defined by World Bank in 1989 which broadened the meaning of governance by incorporating the role and interconnection of three different actors: Government (state actors and institutions), Civil Society (civil alliances and non-governmental organizations) and Private Sector (households and companies).
\item 
\end{itemize}

However, not a single political party, regime or movement has been able to quash the contributing factors of bad governance. For the last six decades, Nepal has become the zenith of corruption that is leading Nepal toward a failed state. Many types of corruption are prevailing in Nepal that range from petty corruption, grand corruption, legal, moral and political corruption to organized crimes, which have become one of the impeding formidable forces in ensuring good governance. In Nepal, bureaucracy or public sectors have suffered most from the rampant corruption. In fiscal year 2015/16, Commission for the Investigation of Abuse of Authority (CIAA) Nepal received a total of 15,126 cases of corruption.  Furthermore, according to corruption perception index, Nepal ranks 131st out of 175 countries in the world. From 2004 to 2016, Nepal’s average rank on corruption index has been 133 out of 175 countries.

\end{solution}

\question What is the role of cooperative sector in economic development of Nepal ?

\begin{solution}

Cooperatives were initially established for raising income generating activities of group of peoples of common interest. Individuals organize into a cooperative voluntarily, cooperate for common good, and are righful to the benefits that arise.

\end{solution}

\question What are the current facilities and remunerations in place for public service personnels ?

\begin{solution}

The facilities and remunerations that public service employees receive are the benefits they are authorized to for dedicating their labor, skill and time in providing service on behalf of government. The reward-facilities may be monetary or non-monetary. The civil service act, 2049 and civil service regulations, 2050 provisions following reward and facilities to the employees:

Monetary reward-facilities

\begin{itemize}
\item Monthly salaray and allowance
\item Grade facilites (increment of salary) after serving for a year
\item Payed holiday service
\item Facility of retirement benefits upon phasing out of service
\item In event of heart, kidney and cancer diseases there is provision additional 5 lakhs support
\item Life insurance of upto 1 lakhs
\item Every year 1 month salary amount will be offered as festival benefit to working personnels
\item Retired personnels will receive a retirement benefit amount of 1 month in addition to regural amount every year as festival benefit
\item Saving of salary (10 percente) as provident fund and additional amount equal to the salaray fraction will be paid by government
\item Provision of payment for health treatment -- equalling 12 month salary for gazatted officer, 18 month and 21 months salary for non-gazatted personnels and personnels without level specification, respectively.
\item Two third of the increased salary will be available in retirement pension, in every raise in salary.
\item Family pension or retirement fund payment
\item Family will be granted Rs 150,000 in case the personnel dies while in service
\item For death of civic service personnel member in a family, child care allowance of 5000 for a child each (for 2 children) will be provided.
\item Monetary award in civil service day to awardees.
\item Allowance for uniform and dress
\item Educational fund, family fund and disabled personnel fund facilities
\end{itemize}

Non-monetary reward-facilities

\begin{itemize}
\item Relocation transfer every 2 years, alternating between rural and urban centres
\item If both husband and wife are employed on the same service they will be attempted for transfer to a common district
\item Non-gazatted personnels will most likely be transferred to nearest localities to their home.
\item Leaves of different kinds
\item For foreign residing ambassadors and personnels employed in consular offices, at most 5 years of unpaid leave will be provisioned
\item Employee service protection, service contract protection and employee protection related provisions
\item For advocating professional rights of personnels, freedom for alignment in trade union
\item For punishing a personnel on beaureucratic basis, provison of refarral to the public service commission.
\end{itemize}

\end{solution}

\question What are the recommendations for making public service more attractive in Nepal ?

\begin{solution}
\begin{itemize}
\item Update basic pay and salary features to reflect contemporary status
\item Develop "pay for performance" indicator and implement in all offices
\item Provision special facilities for personnels working in rural areas
\item Update allowance offerings on dressing and uniform
\item Construction of integrated residence facilities for personnels
\item Automate transfer and promotion system in order to make it more transparent and predictive
\item In order to provision personnels filing up vacant positions in public sector, employee recruitment system should be more responsive and expedient, possibly arraning for twice a year recruitment.
\item Improve workplace environment and render it free of unncessasry interferes.
\item Identification and punishment of wrongdoers amongs the recruited personnels in order to improve public image of the service.
\item Upgradation of public service act and regulations to reflect contemporary needs to make service modern and public friendly.
\end{itemize}

Finally, It should be acknowledged that public service personnels are the carriers of social change. Therefore the sector should be strengthened, efficient and progressive. For this to happen several fiancial, including monetory and non-monetory, amendments should be made. Recruitment process should be streamlined and moderninzed to allow easy entrance of competent individuals. It should be ensured that the personnels are efficiently mobilized. Only then, the public service sector can manifest its full potential. This develops both the service sector and its employees and improves the productivity of the service.

\end{solution}

\question What is devolution ?

\begin{solution}

Devolution is defined as the transfer of power from higher to lower units of any system. In its broad form devolution resembles decentralization, but is often regarded as being more complete and permanent than decentralization. Most frequently, devolution is used with reference to the transfer of responsibilities and authority from central to subnational (or regional to local) levels of government. The World Bank distinguishes between deconcentration, delegation, and devolution as three distinct modes of administrative decentralization of the redistribution of authority, responsibility, and financial resources for providing public services. The three types are differntiated according to the degree of transfer, with decentralization being the weakest form and delegation coming next. 

The need for decentralization is not just an option for countries as a way of good governance. It is increasingly being necessitated by circumstances, both national and international. National pressure for decentralization stems from the openness of the polity that is being increasingly adopted throughout the world. In Nepal, political openness was institutionalized in 1990 by restoring multiparty rule. Real democracy requires the people themselves to be involved in shaping their own lives. And decentralization is the only means of devolving authority from the center to the local units of governance.

Hence, devolution is regarded as the strongest mode of decentralization in the sense that powers are devolved to political entities with a separate corporate status, such as local or regional governments. That is why devolution is also referred to as political decentralization. 

Motivations for devolution in that sense include the perception that devolved governments are best placed to develop and implement policies that exploit endogenous local or regional capabilities and are, hence, an appropriate reaction to increased competition between regions in a globalized economy.

To qualify as a devolved system, the subnational levels of government should be legally established as institutions that exercise power within clearly recognizable geographical boundaries. Other criteria include democratic institutions such as popular elections and the existents of assemblies.

Another aspect of the national imperative to decentralize for countries like Nepal comes from a combination of the country's geography and the status of its economic development. Since communication between the center and local governments is not as smooth as it is with countries having adequate infrastructure, one needs a measure of local autonomy to run local affairs, if only to avoid delays in decision-making. Similarly, the diversities existing among the people and places are not conducive for central governments to provide directives for everything. Even simple government tasks like running high school graduation examinations will need to keep the local circumstances in mind. It is not always possible for the center to run local operations. Hence, decentralization becomes an imperative.

At a time when national economies are being pushed by global forces towards centralization of a global scale, there is a need for governments throughout the world to decentralize as much powers as they can so that each local unit can decide on how to protect its own resources from unfair exploitation by global developments and instead extract benefit from them. This means that even for the protection of national identity and national interests, central governments throughout the world will be forced to seek the help of local efforts. There is no alternative to decentralization, the only question is how to go about it.

Decentralization goals were set by the National Planning Commission (NPC) since the Third Five-Year Plan (1964-69) to create a financial basis for people's participation. The Seventh plan also laid stress on formulation, implementation, maintenance and mobilization of local resources and talents. The Panchayat system had granted the local bodies taxation rights under Panchayat Development and Land Tax. The basic structure of the political economy-- social mobilization through local units and Back to the Village National Campaign, land reforms, modernization of health, education, agricultural, industrial and service sectors, development of transport and communication and the spatial and sectoral differentiation of the planning tradition, management and coordination system -- created by the Panchayat system laid down the socioeconomic base for development in Nepal.

The Nepal's constitution of 1990 made powerful provisions for decentralization. First of all, it shifted the power from an all-powerful monarch to the citizens in favor of an open and democratic system of governance, multi-party polity, popular sovereignty, constitutional and human rights to the people and constitutional monarch. Two "nesting" rules of the Constitution governed the mandate of decentralization in Nepal. First, the Directive Principles and Policies of the State articulates that "conditions suitable to the enjoyment of the fruits of democracy through wider participation of the people in the governance of the country by way of decentralization, and to promote general welfare by making provisions for the protection and promotion of human rights, by maintaining tranquility and order in society" need to be maintained. Second, Article 46(C) stipulated that fifteen members, three from each of the Development Regions, will be elected to the Upper House of Parliament in accordance with law on the basis of the system of single transferable vote by an electoral college consisting of the Chief and Deputy Chief of the Village Development Committee (VDC) and municipality level local authorities and the chief, deputy chief and the members of the District Development Committee (DDC). These two provisions provided the constitutional legitimacy to local self-governance in Nepal.

Decentralization policies appear more pronounced in the Ninth Five-Year Plan (1997-2002). It aimed to strengthen the local units to take the responsibility of formulating and executing local development plans by themselves. This is supposed to be achieved by institutionalizing local government, increasing people's participation in the mobilization and distribution of local resources, social and economic development of geographically disadvantaged areas, improvement, expansion and development of suitable local technology, entitlement of women, indigenous and backward communities of rural areas, enhancing the participation of local people for sustainable development and establishing technological and human development infrastructure in rural areas.

Local self-governance in Nepal came at a time when the state was squeezing itself through an economic crisis and structural adjustment policies. A devolution of expanded responsibilities at such a time meant that the local units were left without the requisite authority and resources. Even then they were more concerned about autonomy than anything else. Local government federations, that represent the coalition of interests and are united for collective action, have argued for the application of "subsidiarity" in decision-making and favor an autonomous self-governance involving devolution. It seems to reflect that horizontal, locally-controlled organizations are instrumental in stocking interpersonal trust and social capital because of the proximity of people and their familiarity with each other and, consequently, better able to cooperate in development efforts.

To unify all these Acts and to prepare a comprehensive framework for local self-governance, Prime Minister Sher Bahadur Deuba appointed a High Level Decentralization Coordination Committee (HLDCC) under his Chairmanship in late 1995. It identified several weaknesses in past practices, such as undefined scope and jurisdiction of local self-governance, overlapping laws, deficiency in institutional culture, lack of political determination, resource scarcity, absence of a mechanism to enforce civic accountability among the elected bodies and government officials, problems in the sustainability of development projects, dearth of planned development processes, flawed elections and organizational technique, etc. Similar problems were identified in the realms of coordination, monitoring and evaluation of development activities. (HMGN, 1996:29-34). Accordingly, a Bill was prepared by HLDCC to be presented in the Parliament. It was replaced in 1997 by the coalition government of UML, RPP and NSP led by Lokendra Bahadur Chand. This coalition government brought an ordinance to amend some laws relating to local bodies and local elections and initiated changes in the power, composition, representation and organizational set up of the LGIs. All these are included in a separate Local Governance Bill passed by the parliament on September 18, 1998. The promulgation of the Local Self-Governance Act (LSGA, 1999 and Rules 1999) thus provides a detailed framework for decentralization and constitutes a basis of good governance at the grassroots level.

The first priority for the Nepalese government is to create a central level neutral institution of local federations and independent experts to build consensus on major development issues and to avoid policy weakness, policy instability and policy reversals. The second is establishment of effective institutions of political authority at the level of the state, polity and the government before social democratization, market reforms and power devolution can take place. The pulling of the collective strengths of the state, the market and civil society through an effective coordination mechanism is essential to make the power of the center effective and responsive. Constitutionalization of these forces including establishing a system of effective checks and balances and power separation is equally important to foster the democratic attributes of rule of law, transparency, accountability and equity. Only then can governance accomplish the needed virtuous circle (synergy) for development.

\end{solution}

\question Write short notes on:

\begin{enumerate}
\item Deconcentration
\item Delegation
\item Privatization
\item Denationalization
\item Deregulation
\end{enumerate}

\begin{solution}

\textbf{Deconcentration}

"merely involves the shifting of workload from central government ministry headquarters to staff located in offices outside of the national capital." (Rondinelli et al: 1989,76) Decentralization based on de-concentration does not allow the local units ample freedom to take initiatives and decisions without the consent of the central authority. But, it allows the delegation of certain financial and administrative decision-making powers to local authorities and people do not have to go to the capital city for every decision.

\textbf{Delegation}

"refers to a situation in which the central government transfers responsibility for
decision-making and administration of public functions to local governments or semi-autonomous organizations that are not wholly controlled by the central government but are ultimately accountable to it" (Litvack, et al 1998: 4-6). Delegation of power thus implies granting of some authority and decision-making powers to local authorities. But central government retains the power to reverse the local decisions and can take these powers back. Local authorities are responsible to carry out only assigned functions. They do not have autonomous policy-making capacity. The delegation of power means the delegation of trust.

\textbf{Privatization}

Privatization "is the act of reducing the role of government, or increasing the role of the private sector, in an activity or in the ownership of assets." (Savas:1987, 89). It is widely contended that too much state intervention strangles the productive energies of the private sector. In many de-communized and authoritarian regimes, centralized planning contributed to a swelling bureaucracy and helped in sustaining the political status quo. Critics argue that privatization is intended to separate the economy from social control by granting industrialists and business classes autonomy from the state and society, has fostered different stages of development within the same state and has justified economic growth free from ethics and civic obligations. In nations like the United States, Canada, Brazil and Mexico and the newly industrialized countries of Asia, for example, privatization has produced a rapid decay of the public realm, an indiscriminate depredation of the public good and the maldistribution of market-driven benefits.

\textbf{De-nationalization}

Denationalization is a particular form of privatization that involves "selling to the private sector (or giving away to the public or the workers) government-owned enterprise or government-owned assets used in producing goods or services; by extension, this form of privatization also encompasses "demunicipalization', and other forms of "de-statification". (Savas, 1987: 89). The defenders of the free-market school of thought have a radical imagination. They imagine that self-help organizations, non-government organizations and private sectors will be able to initiate development only through the erosion of the re-distributive capacity of the welfare state. Besides this, they also favor the free play of market forces as a convenient strategy to empower individuals to build their own fate.

Critics argue that the mobility of capital, technology and information across borders has not only challenged the coherence of democratic governance but also pointed to the withering human values and the very social fabric of democratic accountability. The cost of the actual decline in real wages, job layoffs, the widening gulf between the rich and the poor and de-coupling the fate of the workers from corporate profits has been enormous. In other words, structural adjustment of only the poor people is taking place which, by implication, is causing a democratic deficit. The belief in the capability of market-based transactions to solve all problems, including social ones, has fostered the most narrowly profit-oriented definition of rationality.

\textbf{Deregulation}

"franchises eliminating other price control and entry barriers in order to permit the market to respond to peoples' needs"(Savas, 1989: 89). The reason for deregulation is that bureaucratic control over policy breeds bribery, corruption, commission and patronage and impedes economic growth. Deregulation of labor markets and a reform in the tax structure might induce external investments but these investments must be weighed against the unintended effects in social sector activities, especially the ecology, education, health and welfare. Creating a flexible environment in business and excessive extraction of natural resources for export in the process of becoming market-friendly make the majority of the poor even more deprived of a sustainable livelihood. 

Its critics, therefore, argue that without a proper coordination the people of developing countries suffer badly owing to their smaller competitive advantage. They thus remain vulnerable to external market fluctuations. Therefore, cutting of tariffs, privatization, opening the economy to foreign companies and total denationalization of development subvert the various policy-oriented issues including monetary and fiscal policies, expenditure and pricing. Some degree of central control is, therefore, essential to keep various societal elements in balance (such as defense, foreign policy, banking and the social sectors, etc.) and to prevent the possibility of anarchy.

\textbf{Debureaucratization}

The notion of 'downsizing the state,' to create private opportunity and personal responsibility in all the realms of human life provides the rationale for cutting down the size of the bureaucracy. De-bureaucratization also encompasses the reduction of the role of the central government in many areas of the national economy (Dahal, 1996). It should also oppose the power of large corporations, if they have a monopoly. Debureaucratization pushes for deregulating the economy in an effort to promote incentives, competition, efficiency, transparency and accountability. Essentially, a bureaucratic state is identified by its techniques of ruling, regulating and governing the polity, economy and society through the use of a bureaucracy. Since bureaucratic forms of administration have proved unsuccessful in large-scale organizations, owing to their hierarchy, chain of command, status-oriented role, over-regulation, and technocracy-based culture, it impedes the process of economic growth, innovation and development.

In order to push for a Weberian type of 'legal-rational' bureaucracy, efficient enough to innovate, adapt, and orient itself towards a goal, rational choice theories advocate 'de- bureaucratization' of the development and governance processes and rational control of the environment. In developing countries, in general, and Nepal, in particular, political democracy followed a series of economic reforms. The policy imperative of de-bureaucratization to give a sufficient degree of freedom to private entrepreneurs had thus already been realized before the multiparty polity was ushered in. Neoclassical economists view that bureaucracy has its own autonomous interests which may neither coincide with democracy nor development. Liberal and Marxist theorists reveal that bureaucracy represents the essence of a state, and the state, in turn "represents an aggregation of private interests in which public policy is but the outcome of a pluralistic class struggle among interest groups." (Gilpin: 1975,28)

Bureaucracy needs to be reinvented to make it efficient, people-centered and fair. The Weberian type of legal-rational bureaucracy worked well during the agricultural and industrial revolutions when people worked with hands, rather than brains. It provided job security, economic stability, infrastructure development and social justice. But, in the information society of today, competitive market pressures have put the hierarchy-laden bureaucracy under duress rendering it increasingly difficult to function. An information society requires flexible and adaptable institutions that can offer high quality goods and services to the people. "It demands institutions that are responsive to their customers, offering choices of non-standardized services; that lead by persuasion and being inventive rather than commands; that give their employees a sense of meaning and control, even ownership. It demands institutions that empower citizens rather than simply serving them." (Osborne and Gaebler: 1992,15)

\end{solution}

\question What is the relationship between decentralization and good governance ?

\begin{solution}

Good governance and decentralization are inextricably linked in today’s Nepalese context. Rational allocation of decision-making is central not only to the efficient operation of a democratic polity but also to prevent an overburden of the decision-making load on a particular level of governance to its breakpoint and disintegration. Management efficiency cannot be had without a substantial devolution of central power, responsibilities and resources to sub-national units of government. It also enlarges the area for decision-making freeing the grassroots from the straitjacket of central directives. With a major constraint to the realization of the common people's aspirations gone, a wider space for people's representation and participation from below becomes available. Any complex society requires a diverse, heterogeneous and multitudinous decision making structure to carry out its multiple tasks in a coherent, explicit and predictable manner.

Apart from the moral imperative to work for greater democracy, there is also a political directive to decentralize government. The ongoing process of globalization and the expanding participation of people have overwhelmed the power of the central government to decide and act swiftly and efficiently. New conditionalities of foreign aid focus on people's preference and priorities, ownership, equity and participation in policies, institutions and processes in policy making. In other words, the central government is under greater pressure today than in the past to shift some of its powers to local units of self-governance--a governance that can become a workshop for citizen participation, community building, leadership development, social mobilization, conflict resolution and economic, political and social development.

It will prove to be a difficult process given the centralization tendencies not only of national politics and policy but also of international pressures from global centers of finance and multilateral centers of development policy. Apart from that are regional obligations of the state that make the task of decentralization all the more difficult, but even more necessary.



\end{solution}

\question What is E-governance ?

\begin{solution}

E-governance (electronic government) refers to the impact of information and communication technologies, particularly the Internet, on the values, processes, and outcomes of public bureaucracies.

Government-to-government interactions are concerned with the use of technologies to enhance the internal efficiency of public bureaucracies, through, for example, the automation of routine tasks and the rapid sharing of information between departments and agencies. Government-to-business interactions typically involve the use of the Internet to reduce the costs to government of buying and selling goods and services from firms. Government-to-citizen interactions involve using the Internet to provide public services and transactions online, and to improve the design and delivery of services by incorporating rapid electronic feedback mechanisms, such as instant polls, Web surveys, and e-mail.

Use of information and communication technology (ICT) in government first expanded during the 1950s and 1960s, the heyday of ideas of scientific administration. However, e-government as it is most commonly understood today emerged as an agenda for general reform of the public sectors of liberal democratic political systems during the early 1990s. U.S. President Bill Clinton's administration led the way with the 1993 National Performance Review of the federal bureaucracy.

The 2018 E-Government Development Index places Nepal in the 117th position among 193 countries. Although Nepal is said to be the first country to bring 3G in the south Asian region, it is still at crawling stage with regard to expansion compared to the rapid progress made by other asian countries.

The ubiquity of computer networks offers the potential to increase political participation and reshape the state into an open, interactive, network form, as an alternative to both traditional, hierarchical, bureaucratic organizations and more recent, marketlike forms of service delivery based on the contracting out of public-sector activities (usually termed the new public management). Government becomes a learning organization, able to respond to the needs of citizens, who are in turn able to influence public bureaucracies by rapid, aggregative feedback mecha- nisms such as e-mail, online discussion forums, and interactive Web sites.

Alternatively, e-government does not necessarily require greater public involvement in shaping how services are delivered, but instead, indirectly benefits citizens through the efficiency gains and cost savings produced by the reduction of internal organizational friction, chiefly via the automation of routine tasks. It joins and coordinates the activities of previously disparate government departments and services.

The critics of e-government suggest that changes are limited to a managerial agenda of service delivery more consistent with the new public management and that the opportunities offered by the Internet for invigorating democracy and citizenship might be missed.

\textbf{Status of e-Governance in Nepal}

e-Governance in Nepal has steadily evolved from computerization of Government Departments to initiatives that encapsulate the finer points of Governance, such as citizen centricity, service orientation and transparency. Lessons from previous e-Governance initiatives have played an important role in shaping the progressive e-Governance strategy of the country. Due cognizance has been taken of the notion that to speed up e-Governance implementation across the various arms of Government at National and Local levels, a programme approach needs to be adopted, guided by common vision and strategy. This approach has the potential of enabling huge savings in costs through sharing of core and support infrastructure, enabling interoperability through standards, and of presenting a seamless view of Government to citizens.

e-Governance Master Plan (e-GMP) takes a holistic view of e-Governance initiatives across the country, integrating them into a collective vision, a shared cause. Around this idea, a massive countrywide infrastructure reaching down to the remotest of villages is evolving, and large-scale digitization of records is taking place to enable easy, reliable access over the internet. The ultimate objective is to bring public services closer home to citizens, as articulated in the Vision Statement of eGMP.

"Make all Government services accessible to the common man in his locality, through common service delivery outlets, and ensure efficiency, transparency, and reliability of such services at affordable costs to realise the basic needs of the common man"

In an effort to improve e-governance, there are following institutional and policy arrangements in place in Nepal:

\begin{enumerate}
\item Department of Infromation Technology (DoIT)
  \begin{itemize}
  \item Established in 2013, under ministry of communication and information technology.
  \item Focuses on implementing e-governance and covers IT related laws and policies, Banepa IT park.
  \end{itemize}
\item Nepal IT center: Also working as GIDC of government agencies, with DR site in Hetauda
\item Controller of Certification (OCC): Formed to authorize to legalize digital signatures
\item National IT coordination council: Formed under chairmanship of Prime minister
\item Electronic transaction act, 2006
\item e-Governance master plan (eGMP), 2007
\item ICT Development Project (2008-2014). The project promised of:
\begin{itemize}
\item Rural e-community (wireless broadband, tele-centers)
\item Government network (GIDC, Groupware)
\item eGov Application (GEA, NID, PSC recruitment MS, Land record MS, VRS and Driving licence)
\item HR development (Awareness, training)
\end{itemize}
\item IT policy, 2067 (2010)
\item 10 year master plan (2011): initiated by NTA taking into account telecom acts
\item iCT in education master plan, 2013-17
\item IT Umbrella Act, 2014
\item National IT Roadmap (2015)
\item eGMP-2 (2015)
\item Broadband policy, 2071
\item ICT policy, 2072
\end{enumerate}

Despite its immense potential in achieving sustainable growth, objectivity and improved governance, and responsive service delivery, Nepal has been lagging to eliminate information poverty and keep pace with global digital revolution. Only 21 percent of the total population of Nepal has access to the internet. Digital transformation demands involvement of diverse stakeholders to meet specific socio-economic priorities.

source: \url{https://www.undp.org/content/dam/nepal/docs/2018_undpnepal/UNDP_NP-Tech4SDGs-NageshBadu.pdf}; The kathmandu post and other.
\end{solution}

\question What are the provisions in place for constituting a Press council in Nepal ?

\begin{solution}

The press council act, 2048 provisions under section 6 the following constitution of the council (The section has been edited in the course of enacting several other acts and laws since its first enactment; thrice in 2057 and twice in 2066) :

(1) Government of Nepal shall constitute a Council and the Council shall consist of the following persons,

\begin{itemize}
\item A retired Justice of the Supreme Court or a Senior Advocate or a person designated by Government of Nepal from among the persons who have rendered special contribution in the field of Newspaper --- Chairperson
\item Chairperson, Federation of Nepali Journalists --- Member
\item Six persons nominated by Government of Nepal in consultation with the Journalist Associations at the rate of two persons each from journalists, editors and publishers --- Member
\item One person nominated by Government of Nepal from among the working journalists --- Member
\item One person nominated by Government of Nepal from amongst the persons who have rendered distinguished service in the various fields including journalism --- Member
\item One person nominated by Government of Nepal from  amongst the journalists as recommended by Associations concerned with literary journalism --- Member
\item Director-General, Department of Press Information --- Member Secretary
\end{itemize}

(2) The tenure of office of the Chairperson and the members of the Council shall be Four years.

(3) If the Chairperson or any member desires to resign from his/her office before the expiary of his/her tenure, the Chairperson may submit his/her resignation in writing to the Government of Nepal and a member may submit his/her resignation in writing to the Chairperson.

\end{solution}

\question What is civil society ? Mention its role in good governance ?

In Nepal, the term civil society (Nagarik Samaj) has become very popular and hit the popular psyche with a comprehensive magnitude. Not only non-governmental organisations but even private and business organisation and corporate bodies often tend to claim themselves as being a part of the civil society.

It includes the entire range of organised groups and institutions. These institutions should be independent of the state. They should be voluntary, and at least to some extent self-generating and self-reliant. These, of course, include not only non-governmental organisations but also independent mass media, think tanks, universities, and social and religious groups.

Pluralism, diversity

In fact, to be part of the civil society, groups must meet some other conditions as well. In a democracy, civil society groups should have respect for the law, for the rights of individuals, and for the rights of other groups to express their interests and opinions.  In fact, the word "civil" implies tolerance and the accommodation of pluralism and diversity.

An important prerequisite for civil society groups is that they must keep and preserve their autonomy and independence of the state and private sector.

The first and most basic role of the civil society is to limit and control the power of the state. Of course, any democracy needs a well-functioning and authoritative state. Civil society actors should watch how state officials use their powers. They should raise public concern about any abuse of power. They should lobby for access to information, including freedom of information laws, and rules and institutions to control corruption.            

This constitutes a second important function of civil society:  to expose the corrupt conduct of public officials and lobby for good governance reforms. Even where anti-corruption laws and bodies exist, they cannot function effectively without the active support and participation of civil society. In this regard, the role of civil society organisations in Nepal has been very poor and lukewarm.

Moreover, civil society should help to promote political participation. NGOs can do this by educating people about their rights and obligations as democratic citizens, and encouraging them to listen to election campaigns and vote in elections. NGOs can also help develop citizens' skills to work with one another to solve common problems, to debate public issues and express their views.

Moreover,  civil society organisations can help to develop the  values of democratic life. The values of democratic life are tolerance, moderation, compromise and respect for opposing points of view. Without this deeper culture of accommodation, democracy cannot be stable. These values cannot simply be taught; they must also be experienced through practice.

The civil society can also help to develop programmes for democratic civic education in the schools as well. In Nepal, as we are at a very crucial stage of implementing the new  federal constitution, we need to inculcate the values of tolerance and accommodation in the citizens. The civil society organisations can be tapped for this very purpose.

What can be said is that the  civil society is an arena for the expression of diverse interests, and one role for civil society organisations is to lobby for the needs and concerns of their members, as women, students, farmers, environmentalists, trade unionists, lawyers, doctors and so on. NGOs and interest groups can present their views to the parliament and local governments by contacting individual members and testifying before parliamentary committees. They can also establish a dialogue with relevant government ministries and agencies to lobby for their interests and concerns.

Civil society is not simply to be in tension with the state. Just because civil society is independent of the state doesn't mean that it must always criticise and oppose the state. In fact, by making the state at all levels more accountable, responsive, inclusive, effective - and hence more legitimate - a vigorous civil society strengthens citizens' respect for the state and promotes their positive engagement with it.

A democratic state cannot be stable unless it is effective and legitimate, and has the respect and support of its citizens.  Civil society is a check, a monitor, but also a vital partner in the quest for this kind of positive relationship between a democratic state and its citizens.

The  civil society can strengthen democracy and provide new forms of interest and solidarity that cut across old forms of tribal, linguistic, religious and other identity ties. Democracy cannot be stable if people only associate with others of the same religion or identity. When people of different religions and ethnic identities come together on the basis of their common interests as women, artists, doctors, students, workers, farmers, lawyers, human rights activists and environmentalists, civic life becomes richer, more complex and more tolerant.

Parochial interests

However, in Nepal, the real danger lies in the fact that the political parties have promoted primordial identities so intensely that the ethnic groups have started to keep focus on their narrower and parochial interests. This will hurt the process of democracy building and state reorganisation in line with the provisions of the Constitution of Nepal.

\question What is civil society ? What are the role of civil society in democratic practices ?

\begin{solution}

Civil society can be understood as the "third sector" of society, distinct from government and business, and including the family and the private sphere. By other authors, civil society is used in the sense of 

\begin{enumerate}
\item the aggregate of non-governmental organizations and institutions that manifest interests and will of citizens or 
\item individuals and organizations in a society which are independent of the government.
\end{enumerate}

Sometimes the term civil society is used in the more general sense of "the elements such as freedom of speech, an independent judiciary, etc, that make up a democratic society" (Collins English Dictionary). Especially in the discussions among thinkers of Eastern and Central Europe, civil society is seen also as a normative concept of civic values.

The literature on relations between civil society and democratic political society have their roots in classical liberal writings of G.W.F. Hegel from whom they were adapted by Alexis de Tocqueville, Karl Marx, and Ferdinand Tönnies. They were developed in significant ways by 20th century researchers Gabriel Almond and Sidney Verba, who identified the role of political culture in a democratic order as vital.

They argued that the political element of political organizations facilitates better awareness and a more informed citizenry, who make better voting choices, participate in politics, and hold government more accountable as a result. The statutes of these political organizations have been considered micro-constitutions because they accustom participants to the formalities of democratic decision making.

More recently, Robert D. Putnam, an American political scientist, has argued that even non-political organizations in civil society are vital for democracy. This is because they build social capital, trust and shared values, which are transferred into the political sphere and help to hold society together, facilitating an understanding of the interconnectedness of society and interests within it.

Others, however, have questioned the link between civil society and robust democracy. Some have noted that the civil society actors have now obtained a remarkable amount of political power without anyone directly electing or appointing them. It has been argued that civil society aided the Nazi Party in coming to power in 1930s Germany. It has also been argued that civil society is biased towards the global north. Partha Chatterjee has argued that, in most of the world, "civil society is demographically limited." Finally, other scholars have argued that, since the concept of civil society is closely related to democracy and representation, it should in turn be linked with ideas of nationality and nationalism. Latest analyses suggest that civil society is a neoliberal ideology legitimizing antidemocratic attacks of economic elites on institutions of the welfare state through the development of the third sector as its substitute.

Civil society include among others, following institutions:

\begin{enumerate}
\item Academia
\item Activist groups
\item Charities
\item Clubs (Sports, social, etc.)
\item Community foundations
\item Community organizations
\item Consumer organizations
\item Cooperatives
\item Foundations
\item Non-governmental organizations
\item Non-profit organizations
\item Private voluntary organizations
\item Professional associations
\item Religious organizations
\item Social enterprises
\item Social movement organizations
\item Support groups
\item Trade unions
\item Volunatary associations
\end{enumerate}

\end{solution}

\question What are the problems in implementing public policy in Nepal ?

\question What is meant by public expenditure and financial accountability ?

\begin{solution}

About PEFA: Historical Overview

PEFA began in 2001 as a means to harmonize country level assessment of public financial management (PFM) across the organizations that established the program. Those organizations were the European Commission, International Monetary Fund, World Bank, and the governments of France, Norway, Switzerland, and the United Kingdom. They remain the custodians of the program and have supported PEFA through four phases of implementation.

PEFA was established as a means to reduce the duplication and costs of multiple assessments and to facilitate dialogue between government and others about how to improve the effectiveness of fiscal policies. PEFA was also aimed at improving the results of development cooperation as part of the global aid effectiveness agenda. It provided support for the Strengthening Approach established in 2005 through the Paris Declaration, then further developed in the Accra Agenda for Action in 2008, and the Busan Partnership for Effective Development Cooperation in 2011.

Effective institutions and systems of public financial management (PFM) play a crucial role in the implementation of national policies concerning development and poverty reduction. Good PFM is the linchpin that ties together available resources, delivery of services, and achievement of government policy objectives. If it is done well, PFM ensures that revenue is collected efficiently and used appropriately and sustainably.

PEFA introduced a standard methodology and reference tool for PFM diagnostic assessments. It was extensively discussed and tested between 2001 and 2005 with the aim of harmonizing the needs of government and their development partners for a common analytical tool and shared data. The first publicly available version of PEFA was launched in 2005 and reports for Afghanistan and Zambia were produced in that year. 

Since the early assessments in 2005 PEFA has been used more than 500 times in 150 countries. It has become the acknowledged standard for PFM assessments and has amassed a pool of data comprising over 40,000 individual performance scores.

PEFA Program Phases

To date there have been four phases of the PEFA program. The current phase began in July 2012.

Phase I (2002-2005): Development
Phase II (2006-2008): Dissemination
Phase 1II (2009-2012): Integration
Phase IV (2012-2017): Global Public Good

\end{solution}

\end{questions}

## Good governance (Management and operation) act, 2064 (2008)

- Date of authentication and publication: 2064/10/23 (Feb 6, 2008)

Preamble

Preamble: Whereas, it is expedient to make legal provision in relation to good governance by making public administration of the country pro-people, accountable, transparent, inclusive and participatory and make available its outcome to the general public; upon adopting the basic values of good governance like rule of law, corruption-free and smart (lean or smooth) administration, financial discipline, and efficient management of public work and resources to create situation for providing public services in speedy and cost-effective manner; by bringing into execution (enforcement) of the right of the citizens upon having good governance by translating it to practical reality; and transform the administrative mechanism into service delivery mechanism and facilitator;

Chapter-1: Preliminary
  - Short title and commencement
  - Definitions: Constitution, Minister, Secretary, Ministry, Head of department, Office in charge, Prescribed

Chapter-2: General provisions regarding to the Operation (execution) of governance
  \begin{itemize}
  \item Functions to be carried out at different levels
  \item Thematic (subject wise) ministry and department to be constituted
  \item Essential body may be constituted
  \item Basis for executing administrative functions
    \begin{itemize}
    \item Greater interest of nation and people
    \item Equity and inclusiveness
    \item Rule of law
    \item Guarentee of human rights
    \item Transparency, objectivity, accountability and honesty;
    \item Economic (financial) discipline, corruption-free, lean (smart) and people-oriented administration
    \item Impartiality and neutrality of administrative mechanism
    \item Access of people to administrative mechanism and its decision
    \item Decentralization and devolution of powers; and
    \item Popular participation and optimum utilization of local resources
    \end{itemize}
  \item Policies to be pursued by the Government of Nepal:
    \begin{itemize}
    \item Economic liberalization
    \item Poverty alleviation
    \item Social justice
    \item Sustainable and efficient management of natural and public resources
    \item Empowerment of women and promotion of gender justice
    \item Environmental protection
    \item Uplifting of ethnic groups, dalit, economically and socially backward classes
    \item Development of remote areas and balanced regional development
    \end{itemize}
  \end{itemize}

Chapter-3: Operation and responsibility of administrative function

  - Maintaining good governance to be the duty of concerned authority
  - Responsibility of the minister
  - Chief secretary and his/her responsibility (Functions, powers, duties and responsibilities):
  
  \begin{itemize}
  \item To perform or cause to perform the functions of the office of prime minister and council of ministers as an administrative chief of that office under the supervision and direction of the prime minister,
  \item To supervise the functions carried out by the secretaries and other special class officers of the Government of Nepal as a supervisor and issue necessary direction in relation to their administrative works,
  \item TO coordinate or cause to coordinate among the functions of different Ministries and other concerned bodies,
  \item To coordinate among the different Ministries and other institutions of the central level to implement or cause to implement goverance reform programme as an integral part of the country's public administration
  \item To act as the secretary of the Council of Ministers and authenticate the decisions of the council of minister in that capacity,
  \item To mobilize or cause to be mobilized the concerned ministries for the execution of the decisions of Government of Nepal (Council of Minister) and supervise the status of implementation of those decisions,
  \item To motivate the secretar yand other officials for making administrative mechanism of the country lean (smart) and effective,
  \item To convene the meeting of secretary, from time to time, to make functions of the Government of Nepal effective; and supervise the status of implementation of the decisions taken by such meetings,
  \item To moniter, inspect and supervise or cause to do so to administrative functions of the different ministries and other offices at the central level,
  \item To scrutinize (examine) the agenda/proposal submitted by the secretaries and present them for the decision of the Government of Nepal, Council of Ministers, and return or cause to return in case such agenda/proposal found to be incomplete,
  \item To moniter or cause to be monitored the state of enforcement (execution) of bilateral and multilateral treaty of which Nepal is a party,
  \item To perform other prescribed functions
  \end{itemize}
  
  - Responsibility of the secretary:
  
  \begin{itemize}
  \item Facilitate the concerned minister to formulate policy of the Government of Nepal
  \item Carry out the functions of the ministry or constitutional body or central level office of his/her incumbency under the direction and supervision of the concerned minister
  \item Present proposal before the concerned minister for necessary reform in policy matters in the ministry of constitutional body or central level office of his/her incumbency
  \item Control and supervise over the management, daily work performance and civil servant of the ministry or constitutional body or central level office of his/her incumbancy.
  \item Make necessary supervision and/or control of the functioning the ministry, constitutional body or central level office or departments of his/her incumbency or office subordinate to such office and give them necessary directives.
  \item Implement or cause to implement the policies and programmes approved by the Government of Nepal
  \item Submit a montly report to the Office of the Prime minister and Council of Minister, as prescribed, on the major works performed by the ministry or consitutional body or central level office of his/her incumbency and other concerned offices.
  \item Formulate and sumbit the annual programme of the ministry or consitutional body or central level office before the minister and implement, moniter, evaluate and make progress assessment or cause to do so to the approved programme.
  \item Prepare and submit annual report before the minister on major works performed by the ministry or constitutional body or central level office.
  \item Transfer, recruit or depute the personnel up to gazetted class two officers of the ministry or constitutional body or central level office of his/her incumbency or subordinate office. Provided that, transfer of civil servants from one ministry or constitutional body or central level office or other body or department or subordinate offices to another ministry or constitutional body or central level office or body or department or subordinate office shall be made according to the provision of the prevailing laws.
  \item Make nomination of the officers up to gazetted class two for foreign study, training, study tour, or for other such purposes on behalf of Government of Nepal and approve foreign visit deputation.
  \item Implement or cause to implement the decisions taken by the Government of Nepal (Council of Ministers) on matters related with the ministry, or constitutional body or central level office of his/her incumbency  and  supervise  the  state  of implementation of such decision.
  \item Implment the decisions made by the meeting of the secretaries.
  \item Honour  the  personnel  with  outstanding  or appreciable work performance with the reward of up to Three grade increment in salary or cash prize of up to Five Thousand Rupees with the detail description of the work performed by such personnel.
  \item Make frequent supervision of the projects run by the ministry, constitutional body or central level office or head of the department under these offices and give necessary direction.
  \item While making supervision pursuant to Clause (o), if it is found that the project has not been completed within stipulated time or the completed project found to be less than the quality, make necessary inquiry and take necessary action against the head of the department or project chief under whose authority the concerned project is operated.
  \item Undertake or cause to be undertaken the other functions, duties and powers as prescribed.
  \end{itemize}
  
  - Responsibility of the Head of the Department (10 points)
  - Responsibility of the Chief Office-holder (7 points)

Chapter-4: Procedure to be adopted while carrying out Administrative function
  
  - Certain procedure to be followed
  - Decision to be made within certain time
  - Transparency to be maintained while making decision
  - Basis and reason to be mentioned in the decision
  - Decision not to be made in conflict of interest
  - Performance contract may be made
  - Consultation may be made with Civil society or stakeholders while implementing the matters of public concern
  - Responsibility not to be set evaded
  - Power may be delegated
  - Provision relating to official or professional code of conduct

Chapter-5: Miscellaneous

  - Discharing official responsibility
  - Citizen's charter to be maintained
  - Mobile service may be operated
  - Provision of fixing reasonable service fees
  - Provision relating to public participation and ownership
  - Provision relating to establishment of governance reform unit
  - Public hearing to be held
  - Greivance management
  - Approval to be obtained to open an account in foreign bank
  - Not to encroach (interfere) on the authority of other officials
  - Advisor may be appointed
  - Spokesperson to be appointed
  - Constitutional body and local body shall comply the act
  - Information technology may be brought into practice
  - Monitoring and evalutation committee
  - Disposal of government function and supervision of government office
  - Facilities of service shall be prescribed
  - Annual report to be submitted
  - Work performance indicator
  - Saving of acts done in good faith
  - Power to frame rule
  - Directive or manual may be framed
  - To be governed as per the prevailing laws
  - The effect of repeal of good governance (Management and operation ordinance) 2062
  
