## Public participation

Participation is life of democracy and foundation for sustainable development.

Simply, participation indicates involvement. Getting involved in any activites, development action, plans and project in some means is participating. But still participation is a very vague element in development and vital compound in good Governance. Following definitions are more constructive in defining participation.

"People's Participation is conceptually integrated with re-distribution of economic and political power in the process of development and is therefore subject to value judgment." -- M.R. Ghonemy

Participation is more than simply voting. Participatory processes must entail open dialog and broadly active civic engagement. It requires that individuals have a voice in the decisions that affect them. Processes, not just outcomes are key to this broader interpretation of participation. Participation means many things to many people. Perception differs as well: some see participation as a technique to implement better projects, while others see it as a development goal or part of a rights-based development approach. 5 The challenge is complex and solutions are not simple Participatory development means involving people in diagnosing the situation and problems, planning and deciding courses of action, implementing agreed upon tasks, monitoring, evaluating and sharing the benefits as well as responsibilities of joint action. Participatory development is a process through which stakeholders can influence and share control over development initiatives, and over the decisions and resources that affect themselves. 6 Participation is not something that can be conjured up or created artificially. Participation is a feeling on the part of the people, not just the mechanical act of being called in to take part in discussions.

Participation possess following potentialities:

Joining together the interest groups both direct and indirect to a convincible point.
Management for sustainability.
Good governance
Equitable benefit sharing

In order for development projects to reflect positively, following aspects of participation are necessary:

- Bottom Up approaches of planning including well communicated ideas and demand based perception. 
- Capacities, culture and empowerment factors relatively adjusted with community and identified stakeholder. 
- Equity based benefit sharing mechanism. 
- Identified role and responsibilities clearly defining the output and its impact to participating agency. 
- Conducive environment and comfortable provisioning. These factors as sounds simpler are very hard to comply.

As participation is founded by democratic and people oriented ruling in the same time it needs a good political culture and conductive environment. "Participation for development and vice versa." Nepal developments lack to resonance this particular effect. Supplied participation on blue print approaches has fostered pseudo participation. Pseudoparticipation has resulted in failure of institutions to convey the outputs.

Management has fails to attain the essence of participation oriented policy. Participation has been a game of elite to consume and absorb resources. Finally the mass of people who remained as a suburb of the participation are deprived and evoked. Real participation is both a mean and ends in realm of development.

"What are impacts of popular candidate making unpopular and bias decision and its impacts to people?" Pseudo-participation is just outcomes of implementation failure of policy, unethical doing from leaders and institutions. These are due to transitional society dominated by bureaucratic inefficiency and corrupted political culture. Small community based to multi-sectored project, all of them has failed to adopt team work, common benefit sharing and recognition of value for each other as a outcomes we have decades long of conflicting and interrupted project. Poverty is still extreme. Access to capacities building and its use in enterprise and services are less possible to majority of rural people. Elite's dominancy still do exist. We have still not got rid from trickle down development approaches and blue print tendencies. Social taboos are so strong that the effort, indigenous skills attained and people's positive aspirations are consumed out before resonance. Often blamed statement are; People sell votes for foods and cloths, politician are corrupted and make bias policy, bureaucracy holds ruling attitude, community user groups are elite dominated absorbing resources and misused, industry and commerce are pointed to benefiting through quality and quantity difference/curtailing etc. These factors are interdependent and needs some kind of coordinated orchestration for irrational job to commence.

Leaders were never aware and committed for crime free, corruption less and cooperative society, instead they frequently committed for so in media to gain cheap popularity. Every news paper, radio television and informant talks about power, corruption and praise for money. Continuous exposure to these events has a long term negative impacts to people in the society.

Participation as a key element in Nepal's Sustainable Development: "Substantial participation creates a more rational basis for local decision- making, increases the transparency and accountability of the administration, and allows better monitoring of resource management." The vital task to be compiled for winning the Nepal struggle for development are a) democracy with political Culture and stability b) Poverty reduction with social and economical reform c) National vision orientation with unified and identified outputs. If we can manage these three things we will be able to compete with the world with our today's excellent resources and peculiarities. One of the strategic approaches to poverty reduction being explored by the government is "improvement of livelihoods focusing on people centered participatory development."

Participatory processes (like 'voice', openness and transparency) promote truly successful long term development. These processes do not guarantee success. But an understanding of the centrality of open, transparent and participatory processes in sustainable development helps us to design policies – strategies and processes – that are more likely to lead to long term economic growth, and that reinforce the strengths of the processes themselves. Evidence from several reports clearly depicts that the benefits of participation outweigh the costs. 

To sustain the rule of law, the 'checks' on abuses of the power and influence participation have to be strengthened. There are three elements to achieve this: 

1. strengthen civil society as a source of countervailing power (political parties, unions, consumer groups, think tanks and other NGOs).
2. Increase transparency by protecting 'right to know' among the citizens
3. extend citizens' rights to legal recourse, to sue the non-action by the government.

Participation of the poor is inadequate without involving the powerful and well-to-do in a dialogue to find solutions. Development requires change. Change is threatening. Participatory processes ensure that these concerns are not only heard, but also addressed; as a result, these processes dissipate much of the resistance to change. Participation is thus essential to effect the systemic change in mindset associated with the development transformation, and to engender policies that make change more acceptable.

At the same time, we need experts to think of various solutions, to present alter- natives, and then to discuss them with the poor. We also need to have experts to help understand the larger socioeconomic and historical contexts or the systemic causes of problems, such as poverty, which are not immediately visible to the people The views of the poor and experts must be seen as complementary for development to succeed.

Therefore, open, transparent, and participatory processes are important ingredients in the development transformation – important both for sustainable economic development and for social development that should be viewed as an end in it and as a means to more rapid economic growth. Beside as participation is culture which also transmits; leaders, professionals and institutions must promote ethical and good governed practices to demonstrate the culture of participation to local institutions and community. Mechanism must ensure equity based benefit sharing, ownership among the stakeholder and to best the demand led projects. Meaningful participation can only be expected where people have access to basic needs with quality education and health and for this participation. It is fairly a competitive pursuing of people oriented participation to integrate the strength to improving cycle moving toward goal of sustainable development.
 
Participation is a foundation of democracy. Still it can't not guarantee to development. Outcomes are based on treatments. Nepal development realm also suffers from pseudo-participation. This has affected achieving equity based empowered local communities. Experiences achieved and lesson learned are least realized. In spite of frequent talking about participation of marginalized and good governance, our action are not unlike the three monkey who refuse to see, hear and speak on behalf of misunderstanding, misuse and corruption in participative mechanism. Great emphasis and highlights on reports has been given to mechanical participation, these are just to demonstrate attracting funds. But had we ever revitalized and reinvented participative approaches for its effectiveness and efficiency? Fraction on perception and expectation on participation from ground communities and power practitioner are different practiced in two different ways. Gradually participation in development has now been a show piece and it continuously loosing value based on outputs. Finally, for participation to succeed, it should not be conceived in terms of technique or even as a goal, but rather in terms of its authenticity.
