## Write an essay in about 800 to 1000 words in following issues:

1. We live in a world besieged by media and technology. Every sector of our life is impacted by the presence of modern forms of communication system. Write an essay discusses the influence of modern forms of communications on everyday life.

\begin{solution}

The very nature of human being as a social creature underlines the importance of communication in one's day-to-day life. Human beings interact, possibly much effectively and efficiently than any other life forms in this planet. Much of the achievements we are relishing today, from kitchen utensils to high performance computers are all, in a way, fruits of reliable communication. This is to say that innovations are triggered in several ways through communication. It is also true that modern day communication, we use in the form of media and technology, have been made possible by the feats of human innovation -- once again guided by state of the art communication systems.

Early developments in communication technology consisted of invention of telegram and telephone, which extensively relied on electrical signals on copper wire. As the search for better communication infrastructure continued, data (including video and audio) sharing over wireless frequencies and optical cables are on upsurge today. To recapitulate the role of communication channel, we can refer to an event that is purported to have put an end to the World War II. Invention of cipher (a tool that decrypts hidden messages) on those days became a landmark in intercepting German radio communication channels and gaining the information about overhanging threat military assault. In the retrospect, communication development during World War might not seem as much of a feat when we consider high performing broadband facilites that are at our disposal today.

Communication system today pervades all spheres of life be it physical or socio-economic. It wasn't uncommon, just a few decades earlier, for people to commute great deal of distance just for the sake delivering information through postal services. Proliferation of telecommunication services in every major inhabitated part of world has made it non-essential for the paper mail services to physically transport tremendous amounts of exchanges people are making. This trend in frequent exchange of ideas and even general information among peoples -- families, friend, scholars, researchers, etc., is expected to only expand in future. The imperative is that, as means of communication gets cheaper and accessible, people need not be constrained to utilize information wealth due to their physical distance.

More often than not, means of communication exert their importance at times of crisis. Remote areas are remote for more than a reason but one of those consistently includes them not being able to communicate with authorities on time. This is a situation that typically results in greater marginalization, as individuals from distant localities lacking proper communication methods are increasingly unheard of their problems and scarcities. For example, when a disease outbreak occurs in such an area, relief package and medical interventions become delayed, resulting in significant losses of life. In contrast, well-connected areas where government can quickly initiate a rescue operation will have more lives saved.

When looked at for side-effects on an individual, communication affects even the mundane aspects of life. Citizens of 21 century take toolsets of communication for granted. There is little to how every day engagements of families are ran without crediting to modern communication technologies. Grocery stores and dairy shops have the communication network set to have knowledge of market; A dairy handler has to know who are his customers for what products. Daily updates on traffic and weather to work are all televised through various news channels so that commuters can be punctual to their work. Furthermore, in the workplace, all commercial startups communicate over telephone or email to their clients. This, in comparison to early days approach of door to door visit for sales promotion and order acquistion, is a stark gain in efficiency and scale. A supply order could be made over a phone call while also provisioning for accumulated order the previous day for the same household equipment to areas nearby thereby significantly cutting down the cost of repeated transportation.

Our social thread forms a web of close circle of friends and families along with tendencies to keep-on-touch with them. This emotional and social sphere of our lives too is strung more tightly together than ever before with the advent of new communication technologies. Rashid can now ask what the weather is like in Australia to one of his friends from Nepal in a video call, while also hoping some days to see them there in person. His mother can make a quick appointment with a doctor in a phone call after knowing that Birat is ill. In addition to surfing a personalized news-stand online right before the meeting, one is now also able to address a meeting which includes a mass of 50 people. This is made possible due to wide projection and affordable cinema technology which allow people to conduct presentations as well as entertain with movie.

Besides trivial occurances of everyday life, various channels of communication are used by government organizations to address public and state their vision for country. Likewise, several government insitutions have made social media formum also a platform for obtaining public feedback and outcries, while also attempting to address them. For example, if suspected for a criminal activity, goverment can call for a surveillance of an individual or a group through the use of closed circuit cameras (CCTV) or the GPS system of suspected's smartphone. Although for the case it is clear that criminal threat outweights the expectation that government action hurts individual privacy, there can be scenarios where this application of technology can be subjected to debate. Meanwhile, there is always a chance that political groups may misuse media to propagandize their statements to only gain popularity, while masking up facts that give different flavor.

With all the merits it has brought to individual and societal lives, modern communication technologies can well be thought of as integral part of development. While it has connected people for good, indiscriminate retrieval and exchange of some information can have detrimental consequences -- With great power, comes a greater responsibility.

\end{solution}
