
## Media and information communication technology

### Role of Media

There is no denying the fact that media play a significant role in national affairs and national development. It not only promotes national identity and harmony but also contributes in achieving economic progress and social development. As the media touches almost every aspect of public life, its responsibility is crucial for creating, shaping and reflecting public opinion. Considered as the heart of democracy and rule of law, the media also helps nations meet various formidable contemporary challenges. Nepal has witnessed a noteworthy growth in the media sector following the restoration of democracy in 1990. The Rising Nepal's sister publication, the Gorkhapatra daily, has been a national heritage in the country's media sector. The vernacular Nepali newspaper has entered the 120th year of its launching. As a state media, the publication has seen many ups and downs since its inception on May 6, 1901 (Baisakh 24, 1958 B.S.). Despite facing a myriad of challenges, the publication has continued to serve the nation and the people

Human life is regulated by communication of which media constitute a part, a truth producing part. It is a process of learning, awareness and coordination of behaviour. It helps to visualise the life's prospects. Media make up a union of soft power of text, image and sound to get the voice of people into the public sphere and widen the scale of their deliberation and participation in decisions. In the multi-sided process of nation building various insights, perspectives and concepts of media are useful resources to satisfy peoples' yearning for freedom, justice and national identity. Media thus offer a marketplace of ideas to exercise choice. Their autonomy in rules, finance, professionalism and context-sensitivity enable them to freely report about the vices of Nepali society and offer options to mitigate them.

Nation building under the state's leadership and mobilisation of civic bodies with robust technical and financial support are the most desirable gifts in a world of disarray. Modern means of communication, cultural diffusion, justice and democracy are propelling the fusion of Nepali nations into its state symbolising an epithet of public will. Now, Nepali leaders need to transmit specific interests of groups into public and national interest and socialise them to identify with Nepaliness. It is not by the secluded tribal identity but equal citizenship that defines the Nepali state and its civic nationalism defies predators.

Its impersonal spirit can abolish feudalism and clientelism and protect citizens from alien manipulation of consciousness while producing different levels of communication through endogenous progress. Nepali nations exist in many parts of the world and communicate with each other through language, culture and civilisation. This means that spatial view alone is not enough to arrest its historicity.

Now Nepali media are gripped by a dilemma between constitutional freedom and traditional politics rooted in tribal affinity, not national affinity with the state which is a sphere of rights, solidarity and democracy. Democracy has opened a scope for multi-channel message and citizens' feedbacks to leaders obliging them to evolve national outlook. The diversity of Nepali media has linked politics with social life - families, communities, cultural and linguistic groups, and articulated their desires so that illicit grievances do not upturn social cohesion.

Similarly, they have eased economic structures of production, exchange and distribution of public goods thus overcoming the problems of scarcity created by an imbalance of supply and demand. The current social dynamics in Nepal based on identity politics is, however, straining civic renewal facilitated by Nepal's many post-traditional societal traits vital to bond social capital for cultivating positive multipliers of nation-building. Some media in Nepal with distinct pattern of communication are more conducive to nation-building than the other.

Nepali media's role in building democratic life in society, political structures and parties and crafting a strong national identity cannot be misjudged but this type of media have yet to delink violence from politics. The control of the media by partisan, corporate and geopolitical interest tends to polarise the national audience into good and evil and chip the nation's civic culture.

Professional media grounded in public interests articulate distributive justice to foster a feeling of civic solidarity which creates general loyalty to constitutional state and adapt the old pattern of life to new stimuli and demands. They are considerate, not context free, in orientation as they help build thoughtful considerations among diverse communities, shape rational consensus and add to social cooperation by hauling positive message, information, values and issues that are essential for an educated public-policy oriented dialogue. In times of crisis they bring the connectors of society in a dialogue and synthesise diverse perspectives to fit into a national will. Nepal precisely requires a pro-active role of professional media which can foster a single public identity, equality of citizens before the law, instil civic duty to each other and close the elite-mass gap.

Enlightened media can pass civic knowledge in the entire arteries of polity, help each to bridge the space between the centre, Kathmandu and periphery and across the social classes and shore up the process of national unity. They help citizens free from fatalism, stamp out social ills of Nepali society and provide freedom from all types of tutelage. The sharing of lived experience of surviving citizens can provide learning opportunities for others to build on and strengthen resilient traits of national awareness, historical experience, crisis adaptation, revitalisation and post-conflict reconciliation.

Media freedom, in this sense, is connected to social accountability, public ethics and human rights. Likewise, pluralism in news means upholding normative standards of democracy, human rights, social justice and peace and the civic spirit of a deliberative civic culture which is vital to include the perspectives, values and interests of all sides in nation-building through diverse strategies and outreach:

The unification of people in the state promises its stability and endurance. In Nepal a gap persists between Nepali speaking, spiritually-oriented rural society and the English-stressing materially-oriented urban sub-society. This dualism, rested in a digital gap, is exposing the citizens to bumpy media socialisation and disposition without higher phase of life. Wearing away of this dualism is central to building this nation. Remote areas of Nepal demand the spur of progress indicators. Integration of the periphery to the centre, Kathmandu, requires the diffusion of media channels and effective outreach of the Nepali state so that democratic nation-building can impel from the bottom-up.

Nation building implies a process of cultivating common values, sentiments, feeling, emotion and interests across the diverse people. The split in education and health of Nepal, public and private, cuts up a critical support to under-classes and diffusion of cultural memories so crucial for political acculturation of diversity to changing times. Culture itself is a distilled knowledge shaped by communication. Nepali media must help to integrate political parties, civil society, business and citizens into a national communicative space and cultivate their loyalties to the state. So long as citizen, as members of state, is clientalised to personalised leaders building responsive capacity to state staggers. This is the reason Nepali media find difficulty to judge politics from non-partisan angle.

Self-governance is intrinsic to human genes. It is based on their self-developed consciousness about the physical space, language, culture, ancestry, history, religion and laws often reinforced by the narration of media. They together make up the nation of people. Modern nation-building requires the de-tribalisation of society and transfer of tribal, ethnic, caste, religious, regional and linguistic loyalty to the state, a .state having enough autonomy and capacity aided by its resources to determine its free existence. Tribalisation of political parties, media and civil society and their inability to imbibe civic virtues risk national cohesion in the same way as clientialisation of citizens to personalised leaders. Both cut the freedom of Nepalis and their ability to defend the hard-shell of the state within which democracy is situated.

The communicative gift of Nepalis is a key to realise their inner vigilance and ability to air voice on public matters. The free flow of information offered by the media under the Nepali constitutional right to information has made them critical of a range of issues and source of their valid judgment. Attentive citizens' expression in the social media reflect the condition of Nepalis and their needs offering opinions, options and promises for the solution of burning problems. Politicisation of citizens with added rights but few duties has, however, made Nepali politics aspiration-driven, even some media offer radical view rather than shape credible opinion and objective reporting essential for nation-building.

Media pluralism is the hallmark of democracy but diverse media socialisation of citizens has also fragmented Nepal's civic culture. When news, views and analysis are assorted with parochial interests, the flow of information turns public sphere jarring. Nepali citizens are, therefore, seeking to exonerate themselves from this sordid fact and criticise the national leaders for the nation's elongated political transition.

For nation-building Nepal has adhered the politics of social inclusion, partly multiculturalism, partly accommodation, federalism and promotional measures for weaker sections of society and quota for the marginalised. Nepal's distributive justice is rooted in a proportional electoral system in the structure of governance. The national construction of the nation demands a workable social contract whereby the state find easy to reconcile social fissures through peace dividends where Nepali media can assume communication, aggregation and articulation roles to link the state with citizens. Nepali media's role lies in moderating contesting views to a middle path and enables all people to use socialised choice.

The Nepali media have marked a shift from conventional watchdog role to a vibrant dialogue forum between the state and citizens. Only an interacting public sphere can draw citizens' policy attention. They can help to moderate the behaviour of legitimate, dissident and rebellious oppositions engaged in agitation and raise the voice of those exiled into to silence. Nepali media hold the power of public to improve the health of democracy and renew the society and the state to bounce back to a better condition capable of establishing a balance between public order, freedom, justice and peace.

Source: Dev Raj Dahal, Media as Nation Builder, \url{https://risingnepaldaily.com/opinion/media-as-nation-builder}

### Role of media duing crisis time

The COVID-19 pandemic has appeared as an unprecedented global crisis. Economic activities have shut down, social life has come to a standstill. More than the crisis, an innate psychological fear of the devastation that follows is deeply entrenched among public. With the World Health Organization already confirming that COVID-19 has affected 196 countries of the world, the gravity of the situation can be inferred. Various countries of the world have shut down with no signs of the pandemic coming to a complete halt. Although efforts are underway to find a vaccine for the cure of the virus, the real solution is looking unlikely in the near future. In this scenario, it is important that the state and citizens go hand-in-hand to minimize the adverse effect emanating from the COVID-19. The role of various state institutions including media and civil society will be pivotal to alleviate the crisis.
The manner in which the media is carrying the news and information pertaining to COVID-19 needs critical scrutiny. In our context, media seems to be creating deep confusion among the public about the real status of the coronavirus. While this is not to undermine the role of those media that are performing their duties responsibly, the issue is how to bring the entire media fraternity on track in term of abiding by the journalistic values. With an urgency to get themselves heard and seen over the rival media, some media have carried misleading headlines without verifying the source in the past few days. In the drive towards becoming first to give breaking news, some media have compromised the cardinal principles of journalism. One such case appeared this week when some media disseminated the news of a Birgunj resident being infected of the coronavirus which was later disproved by the concerned authority.
Another aspect of dissemination has to do with the choice of information and the manner of presentation. As the public is in a state of anxiety and fear during such difficult circumstances, media needs to provide content that increases optimism and hope among the public. This could in the form of making the headline news of the positive developments towards combating the coronavirus globally. Instead of reporting only the number of deaths as top news stories, successful stories of the virus treatment and the ongoing initiative towards finding a solution to this crisis can be the major headlines. Devising captivating promotional messages related to COVID-19 in a bid to generate mass awareness should continue.
Moreover, media can also carry videos of the successful treatment cases and the encouraging words of medical practitioners involved in curing the disease for public respite. Running interviews of psychotherapists and motivational speakers could alleviate the perturbed public mind. Broadcasting infotainment programmes related to history, litereature, music and sports could be interesting for the public.
Media can also support the state in its intiative towards combating the global crisis. Circulating the relentless efforts being made by the state will also serve the general welfare. Nonetheless, media as a watchdog of the state activities needs to bring into attention the public ethos. Bringing the stories of low wage laborers and other menial workers and calling for the state to address their hand-to-mouth problem could be one constructive way of media reporting during the crisis.
Since people are in self-quarantine at this hour of crisis with the government's decision of total lockdown at least for a week now, contents related to self-introspection, happiness and family relationships among others could appeal to the common people. With the predominnce of news and information pertaining to coronavirus, breaking the monotony also requires providing some refreshing materials to entertain the audience. In doing this, media ought to cater to the interests of segmented audience – children, youths and the aged.
As WHO has rightly pointed out, ‘infodemics'- an overabundance of information which exaggerates the severity of the problem and makes the solution difficult have posed a severe threat in the battle against the deadlly COVID-19. The need of a responsible journalism is all time high at the moment.

Source: Kushal Pokharel, \url{https://risingnepaldaily.com/opinion/role-of-the-media-during-crisis-time}

### Role of ICTs in Economic Growth

Information and Communication Technologies (ICTs), in the simplest way possible, can be defined as all the devices, applications and systems that allow people and organisations to interact in and with the digital world.

It is evidenced by case studies of various nations that ICTs can contribute to the national GDP and help improve market competitiveness of a country's goods and services. ICTs also have a positive impact on a country's governance and promote its international economic integration, improve living standards, narrow inequality and improve the utilisation of natural resources. All these functions of ICTs make it a key player in the 21st century in enhancing the economic growth of developing countries; because ICTs can help them make up for what they lack in industrial resources by catching up to the developed world in terms of information. This importance is also reflected in the fact that most of the countries today have national "e-strategies" and donor agencies routinely invest in them.

Now, in developing countries, there are mainly two ways in which ICTs contribute to economic growth. One is through their manufacturing and another is through their use. As ICTs are a combination of various individual technological entities, they require manufacturing. And most of this manufacturing is outsourced by the developed countries to the developing countries. This point can be illustrated by the examples of China and India. China is the manufacturing hub for Apple and India is the country which handles the software designing and packaging work outsourced by Microsoft. Such process of outsourcing helps provide decent jobs to thousands of people in the developing countries thus, contributing to poverty reduction.

Also, such companies not only bring their jobs but also their knowledge, which they impart on to the workers of the developing countries. This equips the labour force with skills which means that even if the outsourcing companies were to leave, the people would have necessary skills and expertise to get a job somewhere else or even start their own ventures. All of these serve to make the economy more productive and efficient – delivering economic growth.

Furthermore, setting up manufacturing points and industries in the developing countries means paying taxes to these countries which will directly contribute to the GDP and GNP. Also, we know that industries and especially ICT industries are not isolated entities but part of a larger value chain. Thus, the impacts mentioned above do not stay limited to one sector but branch to multiple sectors; all contributing simultaneously to the economic growth of a nation.

Then there is the act of buying and selling. ICTs, regardless of their place of manufacture, often always find their way into the markets of the developing countries where they are bought and sold. And just this simple act of exchange generates millions of dollars in revenue to the governments depending on the size of the market. This revenue is economic growth. This is how the physical aspects of ICTs help deliver economic growth in the developing countries.

But aside from these physical aspects, there is also the economic growth brought on by the use/application of ICTs. This can best be described through the following "five routes to economic growth:"

Economy: ICTs vastly increase the access to data and information crucial to the supply chain, at significantly reduced costs. Such increased data greatly increases the entrepreneurial activities of a country, thus increasing the efficiency and productivity. All of these end up promoting economic growth.

Efficiency: The use of ICTs can make an entire nation more efficient. The production sector becomes efficient as a labour force comprised of human activity complimented by technology becomes faster, longer and much more diligent than a solely human staff. Also, ICTs when adopted at the state level brings about "e-governance" which brings transparency, accountability and greatly streamlines the often-painstaking bureaucracy of the developing countries. This reduces corruption and makes entrepreneurial activities much simpler by removing the middlemen and the time-consuming hassles. Also, the need to make repeated lengthy journeys for activities such as meetings, ordering, delivering etc. is also reduced as ICTs bring about journey substitution. These, in turn, not only energise domestic commercial activity but also attract foreign investment. Thus, enlarging and enhancing the economy.

Profitability: When the cost of input decreases and the process becomes efficient then the output produced is of high quality. This output can then be sold at a high-value market (the information about which is also obtained from ICTs). Add to that, a transparent and corruption-free process, as discussed above, and this greatly increases the profitability of produced goods of a nation. This also helps in delivering economic growth.

Upgrading: Upgrading is changing the production process from a lower value to higher value ones. ICTs also help in this. With the use of ICTs, a business can take itself online where it may be able to expand its coverage area by getting more orders from different places. ICTs can also play a role in delivering these orders with technologies like drones being employed for the purpose. The payment process is also greatly modernised with various e-payment platforms being utilised. Thus, the whole process gets upgraded in value.

Restructuring: Restructuring means a shift of resources from a lower productive sector to a higher productive one. As discussed in the points above, ICT makes many sectors of the economy highly productive while at the same time, it opens up completely new sectors of production. Thus, investment of resources can be concentrated in these sectors which will yield maximum benefits for the economy of developing countries.

Thus, with the cost of inputs significantly decreased, production streamlined, outputs yielding higher profits, previously low-value sectors upgraded and entirely new sectors opened up for investments, this is how ICTs help deliver economic growth in developing countries.

However, this is not an unlimited scope and ICTs do have limitations, especially in the area of information failures. In ICTs, all routes to economic growth pass through the domain of information and unfortunately, this very domain of information is limited in developing countries by five types of information failures, namely absence, poor quality, uncertainty, asymmetry and cost of information.

Absence of information means that the key information that the development actors need such as the population of a place, literacy rate, sex ratio, livelihood data, internet penetration rate etc. are not available or at least the means to obtain such information are not available. Poor quality of information means that even if the information is available, they may not be of the required quality and usually not in an open format. Uncertainty of information suggests that the information may be available and may be of the desired quality but still, the accuracy of it may be questionable in developing countries; as most of the time the methodology will not be adequately given and the data collection and analysis procedure will not be clearly elaborated. Then, there is the problem of asymmetry where some development actors have access to key information that others lack. And due to the lax regulations and implementation in developing countries, such actors who do have the information start acting as middlemen and use that information for power and profit instead of passing it on to others and acting as facilitators for the economic growth.

And even if none of these information failures exist and quality and reliable information is available to all in an open format, even then, access to such information would be hindered by the cost. Many developing countries are still struggling to lift significant portions of their population out of poverty, the slightest bit of cost associated with information, such as the cost of travel, bureaucracy etc. will prevent people from accessing it.

Therefore, with the I (information) component of ICT facing such severe restraints, the role that ICTs can play in delivering economic growth in developing countries becomes limited.

But, all in all, it is of no doubt that ICTs have a significant role to play in delivering and accelerating economic growth. In the developing countries, this role becomes even more vital as they have tried and failed to do so with more traditional means. ICTs can be utilised in a two-pronged approach to bring growth to countries.

Firstly, the setting up of industries for their manufacture and the market activity generated by their consumption generate direct revenue to the government and also generate thousands of direct and indirect jobs.

Secondly, the use of ICTs helps facilitate start-ups and other entrepreneurial activities which have a broad impact on the whole value chain and contribute to poverty alleviation. ICTs reduce the costs of input and make the production process cheaper and more efficient. Thus, more value can be levied on the output which in turn makes the business profitable. Multiply these individual effects by thousands of businesses employing ICTs and then we get a macro-level national economic growth.

Source: \url{https://risingnepaldaily.com/detour/role-of-icts-in-economic-growth}

## Commonly used terminologies in gender and social development

(This section may be outdated. Excepts draw from Page 9, Overview of gender equality and social inclusion in Nepal, ADB)

**Social exclusion**: Describes the experience of groups that are systematically and historically disadvantaged because of discrimination based on gender, caste, ethnicity, or religion. Exclusion occurs in public (formal) institutions such as legal or education system, as well as social (informal) institutions such as communities and households.

**Social inclusion**: The removal of institutional barriers and the enhancement of incentives to increase access by diverse individuals and groups to development opportunities. This requires changes in policies, rules, and social practices and shifts in people's perspectives and behavior toward excluded groups.

**Gender**: Refers to the socially constructed roles and identities of men and women as well as the relationships between them. These roles change over time and vary by culture. In Nepal, women face unequal power relations and gender-based barriers due to a patriarchal society.

**Caste**: Refers to the Hindu hierarchial system, which originated by categorizing people into caste groups according to the division of labor, roles, and functions. In Nepal, the "upper" castes refer to the Brahmans and Chhetris and the "lower" castes refer to the Dalits who suffer from caste- and untouchability-based practice and religious, social, economic, political, and cultural discrimination. The Dalits comprise 13% of Nepal's population and can be classified into 6 subcaste groups from the hills (Hill Dalits) and 10 subcaste groups from the Terai (Madhesi Dalits).

**Adivasi Janajatis**: People or communities having their own mother tongue and traditional customs, distinct cultural identity, social structure, and written or oral history. Interchangeably referred to as "Janajatis", "ethnic groups" and "indigenous nationalities". The government identified 59 groups as indigenous nationalities and these are categorized into 5 groups based on their economic and sociocultural status. These include "endangered", "highly marginalized", "marginalized", "disadvantaged" and "advanced" groups. Newars are Thakalis are the only two groups classified as "advanced" groups.

**Madhesis**: The definition of "Madhesi" is politically contested, but in broad terms it refers to the people who have languages such as Maithili, Bhojpuri, Awadhi, Urdu, and Hindi as their mother tongue and are considered of Madhesi origin. THey include Madhesi Brahman-Chettri (2% of population), Madheshi other caste groups (14% of the population), and Madhesi Dalits. Their exclusion is based primarily on regional identity and language.

**Muslims**: A religious group who comprises 4.3% of Nepal's population.

## Gender and social exclusion in Nepal and its development outcomes

(This section may be outdated. Contains excepts from Page 15, Overview of gender equality and social inclusion in Nepal, ADB)

Improvements in social and economic conditions in recent years include greater access to roads, irrigation, safe drinking water, schooling and health care. The government has also made notable efforts with regard to gender equality and women's empowerment. However, discriminatory institutions and structures, ideology, and social norms continue to limit women's progress. The UNDP Gender Empowerment Measure, which considers whether women are active in public and economic life, indicates that women's participation and representation remain lower than that of men in political, economic, and professional domains. Although there has been an increase in the proportion of economically active women, their earned income is about one-third that of men and women continue to have low access to property ownership, financial credit, and political power. Caste, ethnicity, and regional identity and geographical location have been strong determinants of poverty and unequal development outcomes.

Various sectoral issues have been identified in gender and social exclusion dimension. The issues or more broadly, in some cases, sectors are:

- Citizenship
- Property rights
- Family law
- The police
- Employment and labor migration
- Trafficking
- Conflict, reconciliation and peace
- Gender based violence
- Social security and protection
- Participation in governance
- Health
- Education
- Agriculture and natural resource management
- Water supply and sanitation
- Rural transport infrastructure
- Energy

Among above enlisted, some of the sectoral issues are detailed hereunder.

### Gender based violence


### Participation in governance


### Agriculture and natural resource management

Despite the importance of agriculture and forestry to the livelihoods of poor, these are the neglected sectors for investement by the government and donors. Agriculture contributes the largest share (32\%) of gross domestic product and it is the main source of employment for 78% of the poor. Yet, the contribution of agricultural development of official development assistance (foreign aid) is only 4%, and the sector receives only 6% of pulic spending.

The ownership of land has a strong influence on food security and well-being and is a major factor determining the economic and social position and political power of most of the population. Conversely, economic status and social identity (gender, caste, ethnicity, etc.) also have a large impact on who gets access to-and control of-land. The present land tenure practices are based on the customary forms of land tenure. These are not based on the principle of equity, so huge inequalities exist in the distribution of land, 98 and a disproportionately large number of Dalits, Adivasi Janajatis, and women belong to the landless and near-landless groups of society. Of Dalits living in the Tarai, 95% are landless, and 49% of Dalits in the hills own less than 0.25 hectares.

Past experiences with land reform policies demonstrate that their implementation has not provided access of land for the landless, poor farmers, and smallholders to achieve economic growth and poverty reduction.The fourth amendment to the Land Act 1964 (1997) abolished dual owner-ship of land, but failed to acquire excess lands and redistribute them to the poor and landless due to its phased implementation of the land ceiling in districts. The struggle for tenancy rights supported by civil organizations started in 1995 and has made some progress in addressing the issues of land rights for poverty reduction. However, many tenants and poor people have yet to receive their land rights; therefore the continuation of the land rights movement and effective land reform actions by the government are necessary.

The armed conflict and large-scale out- migration of men from rural areas increased the role of women in agriculture. However, women are still not recognized as independent and autonomous farmers by the social system and legal procedures. Though women have physical access to land as users, they do not have decision-making power regarding use of the land for agriculture and for other means of production.

As land is the most important source of col-lateral, access to formal credit for the rural poor is very limited. About 71.6% of smallholders are dependent on informal sources of credit, such as private money lenders and relatives, for loans. In contrast, about two-thirds of households with large landholdings often borrow money through formal credit services such as the Agricultural Development Bank and cooperatives. Landless persons and smallholders are denied access to basic government and extension services. The extension agents are also more likely to contact men than women to provide them information and skills on technologies since women are not recognized as autonomous farmers due to their lack of legal ownership of land. As a result, agricultural extension and information on new technologies are almost exclusively directed to men, even though women are traditionally responsible for farming.

The national policies for agriculture (2004), irrigation (2003), and forestry (2000) and the Three-Year Interim Plan are the main policy documents that guide the government's strategy for agricultural development and natural resource management. The agriculture policy aims to ben-efit the poor, women, and disadvantaged groups by promoting programs for cooperative-based production, rural agriculture employment, and agricultural credit at concessional interest rates. The policy also promotes proportional representa-tion in farmers' consultative committees and equal numbers of women and men in mixed groups, and establishes gender focal points in govern-ment bodies. The irrigation policy mandates 33% participation of women and disadvantaged social groups in water users associations, and ensures financial concession and technical sup-port to them for irrigation facilities. However, the policy lacks explicit institutional mechanisms for ensuring inclusion from program development to evaluation. Irrigation policy and programming have typically ignored gender, class, and caste-differentiated needs and priorities. It has tended to emphasize the construction and maintenance of systems, efficient distribution of water, and increased agricultural output rather than issues such as the impact of irrigation on labor markets and the coexistence of productive and consumptive water uses for women, the ultra poor, and socially excluded groups. In comparison with agriculture and irrigation, forestry has a stronger approach to inclusion: it has mandated that 35% of the income of community forests be allocated to uplifting the poor. It also promotes forestry-related microenterprises, membership of a male and a female member of each household in forest-related groups, proportional representation in executive committees, and capacity enhancement and positive discrimination for women and other marginalized groups.

All ministries and departments have appointed gender focal points to oversee main-streaming of gender into sectoral program design and strategies. This is a substantial effort. However, the gender focal persons are not sufficiently senior in the bureaucratic hierarchy to have much influence, and gender focal points alone are inadequate to advocate for effective gender main-streaming. The agriculture ministry established a separate gender division led by a committed woman, which significantly enhanced awareness and capacity of the staff to address women's problems in agriculture. In irrigation, major bottlenecks include the lack of appropriate institutional structures and mechanisms, and limited understanding and capacity for mainstreaming gender and social inclusion. The forestry sector has been comparatively successful in changing the attitudes of staff and in building their capacity to make effective institutional arrangements for increasing access by excluded communities to forest resources and development opportunities.The Ministry of Agriculture and Cooperatives started integrating women into its training pro-grams early on and has established institutional structures to support gender mainstreaming in its departments, divisions, policies, and programs. It has better women's representation among staff (6%) than the Ministry of Local Development or the Ministry of Women's Affairs, yet its Gender Equity and Environment Division still faces challenges in implementing its responsibilities due to a lack of gender sensitivity, small budgets, and the lack of a gender monitoring mechanism.103The Ministry plans to set up farmers' consultative committees and village agriculture committees to ensure farmers' participation in agriculture-related activities and decision-making processes. Proportionate representation of women, Dalits, Madhesis, and Adivasi Janajatis will be ensured in these committees.

The Federation of Community Forest Users is an example of a federation that has effectively influenced policy and development processes. It has established rules to include women in the decision-making arena and it supports local groups to include women and disadvantaged groups. By law, one-third of the executive- committee members of community forest user groups must be women, but there are no stipulations for Dalits and Janajatis. Despite its success in holding the government accountable to its citizens, community forestry is not without its challenges. Elite domination of executive commit-tees marginalizes the poor, Dalits, and Janajatis. The National Federation of Irrigation Water Users Association Nepal is quite similar to the Federation of Community Forest Users in its purpose, but it has not yet been as successful in representing the voices of their women and poor members in the policy and development arenas. There is a great potential for developing organizational coalitions and networking activities in the agriculture sec-tor for advocating the rights of women and small farmers and influencing policy.The policy reform process needs to strengthen government capacity and introduce concrete implementation and accountability mechanisms to reinforce the inclusive policy statements. Though the forestry and agriculture sectors have made efforts to mainstream gender, effective institutional frameworks for gender and social inclusion are of utmost importance. The establishment of gender divisions and gender focal points could contribute to positive outcomes if they have adequate institutional authority and budgets. Improved accountability to gender and inclusion mainstreaming from the various department and division heads is also required. Institutional capacity needs to be strengthened in the irrigation sector, in particular, for inclusive policy design and service delivery.Extension systems need to promote strategies, services, and technologies that address the needs of women, the poor, and the socially excluded. Greater efforts are needed to improve poor people's access to microfinance services and to ensure that socially excluded groups have access to project services and are represented on user and decision-making bodies. For this, promotion of linkages between the finance sector, rural development planning, and other relevant agencies for planning and implementation of specific targeted programs from the national to the local levels will be crucial.

## Environment, agriculture and climate

### Relationship between climate change and energy use

- Energy use has close ties with climate change. India and china are among the greatest emitters of greenhouse gases and consumers of fossil fuel, and it is predicted that their consumption of coal as major source of energy will continue to rise for at least a decade (IEA, 2019).
- Into 2016 and we still have 80% of our total energy requirement met from fossil fuels (mostly, oil, coal and natural gases). International energy agency's report says that 30% of all energy-related carbon dioxide emission is related to coal as fuel, making it the biggest single contributor (2019).
- An individual effort to parsimoniously treat energy resources available to us determines individual footprint. We could choose to reuse a battery/cell, with minor power drops, in alternative electronic items compatible with it or just treat at a refuse at our home. The latter activity with unforeseen consequences might lead to the battery being disposed improperly and polluting an ecosystem due the leakage of its electrolyte chemicals.
- While electricity is lighting up most houses, its generation has been a markedly different process worldwide. The process basically depends with the resource endowment of a nation in their approach to choosing ways to explore it. Coal, for example, is used largely in China and the US despite its much tauted big contribution in greenhouse emission.

### Impacts of climate change

What are the impacts of climate change ? Discuss on detail about the initiative taken by Nepal Government in tackling the impacts of climate change.

Climate change is now affecting every country in every continent. It is disrupting national economies and affecting lives, of individuals, communities and countries today and is likely to do so in the ensuing future. Weather pattern are changing, snowline are melting due to global warming and sea level are rising. 

**Negative impacts**

1. Numerous mountains are seeing accelerated the melting of snow due to global warming.
2. Changes in monsoon patterns, such as erratic rainfall with alternate drought periods are the serious impacts of climate change in Nepal which hampers the agricultural production. The changes in monsoon pattern in Nepal greatly exacerbate the situation of poverty and food insecurity in the country.
3. Flood, landslides, forest fires, snow melt are the disasters that occur as a result of climate change without any prewarning and causes heavy loss.
4. High hills and mountains are more vulnerable to climate change compared to terai, thus climate change make large scale economic and ecolgical disruption in upper latitudes.
5. Loss of plant and animal biodiversity.
6. Increase in number of insects, pest and diseases and sporadic outbreaks becoming much frequent.

The positive impact of global warming, a characteristic feature of climate change, is that the crops that could in the past be only growth in certain low altitudes, requiring prolonged exposure to heat can now be growth in higher regions such as Manang and Mustang districts of Nepal. The is evidently due to increase average temperature of the region, thus allowing the crop to perform well. However, as noted earlier, there are more prominent negative impacts than the benifits we can derive from the climate change.

Nepal became signatory of UN Framework Convention on Climate Change (UNFCC) in 1994. Ever since then the issue of climate change has been routinely incorporated into policy and strategic frameworks by Government of Nepal. Following policies and strategies are currently in place to help mitigate the impacts of climate change in Nepal:

1. Constitutional approach

Article 30(1) of the constitution of Nepal guarantees a "clean environment" as fundamental right and elaborates that "every citizen shall have the right to live in a clean and healthy environment." Article 30(2) of the constitution also encourages the state to formulate necessary legal framework to balance environment and development.

2. Approaches in periodic plans
3. Climate change policy, 2067 (2011)
4. National climate change policy, 2076 (2019)
6. National adaptation plan of action (NAPA, 2010)
7. Framework for local adaptation plan for action (LAPA, 2011)

### National Climate Change Policy (NCCP), 2076

Reasons for Nepal's vulnerability to climate change are Topographical fragility, fragile geological structure, sensitive ecosystems and diversity of climate and micro-climate zones prevalence in Nepal. Additionally, poverty, illiteracy, social disparity and high dependence of communities on natural resources for livelihood.

- Nepal National Red Strategy implemented to check greenhouse gases emmission from deforestation and forest destruction.
- Provision of climate change coordination committee in Chairmanship of Prime minister.
- Establishment of Climate change management section under Ministry of Forest and Environment as focal point for implementation of international treaty.
- Provision of Climate budget code by National planning commission.
- Alternative energy promotion center has established climate and carbon unit for executing Clean Development Mechanism (CDM) related activities.

**Goal**

To contribute to socio-economic prosperity of the nation by building a climate resilient society.

**Objectives**

a. To enhance climate change adaptation capacity of persons, families, groups and communities vulnerable to, and at risk of, climate change;
b. To build resilience of ecosystems that are at risk of adverse impacts of climate change;
c. To promote green economy by adopting the concept of low carbon emmission development;
d. To mobilize national and international financial resources for climate change mitigation and adaptation in just manner;
e. To conduct research, make effective technology development and information service delivery related to climate change;
f. To mainstream or integrate climate change issues into policies, strategies, plans and programs at all levels of State and sectoral areas;
g. To mainstream gender equality and social inclusion (GESI) into climate change mitigation and adaptation programs.

**Policies** (Sectoral policy, strategies and working policies)

1. Agriculture and food security
2. Forest, biodiversity and watershed conservation
3. Water resources and energy
4. Rural and urban habitats
5. Industry, transport and physical infrastructure
6. Tourism and natural and cultural heritage
7. Health and drinking water and sanitation
8. Disaster risk reduction and management
9. Gender equality and social inclusion, livelihoods and good governance
10. Awareness raising and capacity development
11. Research, technology development and expansion
12. Climate finance management

Policy number 9-12 are inter-thematic areas.

\begin{questions}

\question Although Nepal is an agricultural country, what are the reasons for decreasing productivity of arable land in recent years.

\begin{solution}

Some of the reasons for decreasing productivity of arable land in recent years in Nepal are:

\begin{itemize}
\item Recent years have seen depletion of soil fertility. Besides leach and runoff of major nutrients, intensification of mono-cropping, mainly that of cereals, has accelerated exhaustion of these essential supplies. Likewise, farmers have not been, since early farming days, supplementing the land with micronutrient fertilizers. It should be noted that micronutrient deficiencies can have serious limitting effects in yield.
\item Haphazard use of chemical fertilizers have resulted in acidity and salinity build-up in soil. The crops exhibit symptoms of toxicity when growth therein. Trace to almost null measures of soil amendment adds to this problematic scenario.
\item Excessive reliance on seasonal rain has turned to become counterproductive. Monsoon streams and water bodies have not been able to fend for agricultural water needs. In some instances they have even dried down in recent years, mainly due to changing seasonal patterns and climate extremes.
\item In recent years, size of land holding have decreased. This means that in average a farmer own less area of land than what he used to crop previously, currently 0.5 ha per household. This is in comparison to more advanced nations, less by ten to hundreds of order magnitude. This has a rippling effect. Today farmers are practicing farming only as a side gig as well as being less willing to invest in technology introduction. This translates into lesser input consumption and ultimately to lower yield. At the same time transition from traditional practices of diverse cropping to mono-cropping leads to a greater loss in diversity and deprivation from essential ecosystem services of natural environment. For example, natural enemies of insects are indiscriminately being eradicated while trying to turn the wheels against insect-pests. 
\item While most development plans give high priority to agriculture - which contributes 30 percent to GDP - government investment in the Ministry of Agricultural Development (MOAD) - has declined from 3.7 percent of all government spending 10 years ago to around 3.0 during recent years. Meanwhile, overall government spending has doubled since 2006.

\end{itemize}
\end{solution}

\question What is climate change ? What are the negative impacts or such impacts possible due climate change in Nepal ? Mention.

\begin{solution}

Climate is usually defined as the "average weather" in a place. It includes patterns of temperature, precipitation (rainfall or snow), humidity, wind and seasons. Climate patterns play fundamental role in shaping natural ecosystems, and the human economies and culture that depend on them.

The planet's climate has been constantly changing over geological time. The global temperature today is about 15 $^\circ C$, though geological evidence suggests it has been much higher and lower in the past. However, in light of the global temperature records, scientists today are concerned that the natural fluctuation, or variability, is being overtaken by a rapid human-induced warming that has serious implications for the stability of the planet's climate. For example, notable events including drought and heat waves in Russia in 2010, drought in China in 2012, and droughts in the US in 2011 and 2012, have all had a major impact on agricultural production in these areas.

Climate change is a change in the state of the climate that can be identified (e.g., by using statistical tests) by changes in the mean or the variability of climate properties and that persists for an extended period, typically decades or longer. Climate change may be due to natural internal processes or external forces or due to persistent anthropogenic changes in the composition of the atmosphere or in land use by factors such as biotic processes, variations in solar radiation received by Earth, plate tectonics, and volcanic eruptions. Certain human activities have been identified as primary causes of ongoing climate changes, often referred to as global warming.

Observations of temperature have shown that 10 of the warmest 11 years have occurred since 2001. Coupled with these changes is the decrease in the number of frost days by 10\% in the eastern half of the US and an increase in the length of the growing season by over 10 days.

Trends in precipitation are more difficult to assess; however, overall precipitation amounts and heavy precipitation events have increased in most regions of the world; while occurances of drought has been increasing, particularly since 1970 (IPCC, 2007). 

Recent analysis of trends from 1971 to 2014 by the Department of Hydrology and Meteorology (DHM) shows that the average annual maximum temperature has been increasing by \SI{0.056}{\degree\celsius} per year (DHM, 2017). Another study found that a small, but statistically significant, increase in the frequency of hot nights has been observed. In contrast, the annual frequency of "cold" days and nights has decreased significantly since 1960 (McSweeney, New, & Lizcano, 2012). The mountain regions are warming more than the plains (ICIMOD, 2018). The mean annual temperature is expected to continue to increase in Nepal over the remainder of the century. Recent projections indicate that mean annual temperatures could increase \SIrange{1.3}{1.8}{\degree\celsius} by the 2050s, with the highest increases in the mountain regions. Along with this, increase in warm days and nights is predicted.

\textbf{Impacts of climate change for human society}

\begin{itemize}
\item Melting glaciers, early snowmelt, and severe droughts will cause dramatic water shortages and increase the risk of wildfires in the American West.
\item Rising seas levels will lead to coastal flooding on the Eastern Seaboard, especially in Florida, and in other areas such as the Gulf of Mexico. 
\item Forests, farms and cities will face troublesome new pests, heat waves, heavy downpours, and increased flooding. All those factors will damage or destroy ecosystems which human excessively rely on -- Agriculture and fisheries.
\item Disruption of habitats such as coral reefs and alpine meadows could drive many plant and animal species to extinction.
\item Allergies, asthma, and infectious disease outbreaks will become more common due to increased growth of pollen-producing ragweed, higher levels of air pollution, and the spread of conditions favorable to pathogens and mosquitoes.
\end{itemize}

Examples of observed climatic changes

\begin{itemize}
\item During the past 50 years there has been an increase in $CO_2$ concentration from 325 to 390 ppm with a projection of further increases to nearly 500 ppm by the middle of the twenty-first century (IPCC, 2007).
\item During the twentieth century, global average air temperatures increased by approximately 0.74 $^\circ C$ (0.56–0.92 $^\circ C$) (IPCC, 2007a) with projections of further increases in surface air temperatures of between 1.1 and 2.9 $^\circ C$ by 2100 under emission scenarios, which have adopted aggressive methods to reduce $CO_2$ emissions, and by up to 2.0-5.4 $^\circ C$ under scenarios with higher emission rates. 
\item Winter temperatures have increased more rapidly than summer temperatures, and night time minimum temperatures have warmed more than daytime maximums. Across the US (and elsewhere), record high temperatures are three times higher than the number of record cold events.
\item Decrease in snow cover and sea ice extent and the retreat of mountain glaciers in the latter half of the 20th century.
\item Rise in global average sea level and the increase in ocean water temperatures. Between 1900 and 2016, the sea level rose by 16-21 cm (6.3-8.3 in). The accelerated decrease in coastal areas is attributed mostly to human induced global warming.
\item Likely increase in average precipitation over the middle and high latitues of the northern hemisphere, and over tropical land areas.
\item Increase in frequency and intensity of extreme precipitation events in some regions of the world.
\end{itemize}

Examples of observed physical and ecological changes

\begin{itemize}
\item Thawing permafrost
\item Lengthening of the growing season in middle and high latitudes
\item Pole-ward and upward shift of plant and animal ranges
\item Decline of some plant and animal species
\item Earlier flowering of trees
\item Earlier and frequent emergence of insects-pests
\item Disruption of seasonal pattern of migratory birds and egg laying animals.
\end{itemize}

Source: Encyclopedia of Agriculture and Food Systems

\end{solution}

\question What is green house effect ? Mention its implications of green house gases in global warming.

\begin{solution}

The earth's climate is warming as a consequence of the accumulation of greenhouse gases in the atmosphere. Warming of the atmosphere is actually happerning because the atmosphere is continuing to trap the heat that radiates from the earth and traps it between the earth and space.

The most important greenhouse gases contributing to this warming are carbon Water vapor, dioxide ($CO_2$), methane ($CH_4$), and nitrous oxide ($N2O$). Although these gases are present in the atmosphere naturally, human activity has been responsible for a rapid increase in their concentration over the past century. Greenhouse gases are released by a variety of processes, the most important of which is fossil fuel consumption, which currently adds more than 9 billion tons of $CO_2-C$ to the atmosphere each year.

Chlorofluorocarbons (CFCs), which are basically synthetic compounds that are created in the industrial setting, also play a part in green house conditioning. They are usually what plays a part in depletion of the ozone layer. The more the ozone layer is depleted, the hotter our earth will get.

Globally, IPCC (2007d) estimates that 69\% of the GHGs originate from energy consumption, whereas 14\% arise from food production and 17\% from deforestation. Meanwhile, energy use, food use, and land use change, and thus emissions generally expand with incomes and population. In fact, historical emission data show that global GHG emissions and concentrations have been increasing at an increasing rate.

Agriculture too is a major source of the greenhouse emissions. Practices such as deforestation, cattle feedlots, and fertilizer used currently account for approximately 25\% of greenhouse gas emissions. When broken down in total, this amounts to 14\% of carbon dioxide emissions, 48\% of methane, and 52\% of nitrous oxide emissions.

\end{solution}

\question What is water-use efficiency? Describe the role of micro-irrigation in increasing the water-use efficiency.

\begin{solution}

Water use efficiency is the ratio of water used for plant metabolism to the water lost by plant through transpiration. It can be understood as a measure to reduce water wastage from plants by providing only the necessary amount.

Role of micro-irrigation in increasing water-use efficiency

Reduces excess water accumulation
    
In conventional irrigation system water is used in bulk without proper understanding of the requirement of the crop. This will result in accumulation of water without proper utilisation leading to wastage. In micro-irrigation, the water needed for the plant to grow is given in right amount so as to reduce wastage.

Recycling of expelled water

In micro-irrigation system such as greenhouse farming, the plant canopy is covered in plastic to prevent transpiration water from escaping. The water is then diverting back to the plant. This will ensure that water wastage from plant will be lower in comparison to the input.

Reduces run-off

Water irrigation in conventional methods like canals and tube well will result in water runoff from the fields without getting utilised. This will contribute towards wastage especially in areas where there is shortage of water. In micro-irrigation techniques, water will be targeted at the root of the crops so that wastage is as low as possible.

Way forward
It is necessary to device methods to make water use efficiency high and address shortage of water across the globe.

Thus, micro-irrigation is a very important idea when it comes to sustainable use of water resources. The initial investment once recovered will make agriculture a profitable venture.

source: \url{https://www.upsciq.com/what-is-water-use-efficiency/}
\end{solution}

\question The global lockdown imposed due to COVID-19 pandemic has turned out to be beneficial for environment on short term. Validate.

\begin{solution}
The major countries of the world, including India have self imposed a lockdown to tackle spread of COVID-19 pandemic. This has impacted economy of the world in an adverse manner causing slowdown. But the silver lining in the situation is improvement in environmental conditions that we have observed.

Environmental benefits due to global lockdown

Reduction in air pollution levels

The major environmental concern in this century is climate change, that has been caused due to air pollution across major human settlements. Due to the lockdown the pollutant level in air such as CO2, NO3, SO4, ozone, PM 10, PM 2.5 have seen a drastic drop. This has made the air cleaner for breathing and reducing health concerns.

Reduction in water pollution levels

Water pollution in developing countries is mainly due to factories dumping their waste in water bodies. The lockdown has forced the factories to shutdown and cut production. This has reduced or completely cut off waste discharge from factories.

Reduction in solid municipal waste

With low outdoor activities and travel, the household waste produced in cities have seen reduction. The reduced level makes it easier to dispose off the waste more effectively. Dumping grounds have a chance to recover if this trend continues.

Increase in biodiversity

Withdrawal of humans from outdoors have opened the spaces for biodiversity to recover their lost territories. Sea mammals like dolphins have returned back to the shores due to lack of disruption from humans in their territories.

Reduction in sound and light pollution

Cities have turned silent due to stoppage of vehicular movement and industrial activities. This has made the environment suitable for calmness. Excessive usage of light has been reduced too due to the same reasons.

Way forward

This restriction has to be converted into a habit for people to follow in future so that environmental pollution is kept in check.

So, the global lockdown has helped the environment to recover upto certain extent. What needs to be seen is the impact that return of normality is expected to bring.

source: \url{https://www.upsciq.com/the-global-lockdown-imposed/}
\end{solution}

\end{questions}
