# Foreign affairs

## Introduction

Foreign policy is the system of activities evolved by communities for changin the behavior of other states and for adjusting their own activities to the international environment -- George Modelski

Foreign policy is the substance of nation's efforts to promote its interest's vis-a-vis other nations -- Normal Hill

Foreign policy is the key element in the process by which a state translates its broadly conceived goals and interests into concrete courses of action and to attain these objectives and preserve its interests -- Padelford and Loncoln.

Foreign policy is based upon general conception of national requirements. A country's foreign policy is a set of goals that seek to outline how that particular country with interact with other countires of world and to a less extent non-state actors.

Forein policies are designed to help and protect a country's national interests, national security, ideological goals and economic prosperity

Foreign policy is an extension of domestic policy so one must recognize the fact that no nation state can preserve its independence, soverignity and territorial integrity without a policy to build its internal strength that comes from peace and prosperity enjoyed by the people.

Foreign policy of state is the ratifed legal policy aimed at establishing good mutual relationship with other states and international organizations.

Foreign policy of each nation contains:

- A set of principles, policies and decisions adopted and followed by the nation in international relations.
- Objectives, goals or aims of national interest which are to be secured.
- Means to be used for achieving the goals of national interest.
- Broad policy principles and decisions for conducting international relations.
- Assessement of the gains and failures of the nation in respect of its goals of national interest.
- Policies, decisions and action-programmes for maintaining continuity or change or both in international relations.

A student of foreign policy analyses the action of a state towards external environment (i.e. other states) and the conditions, usually domestic, under which those actions are formulated. -- Hlstei

The study of foreign policy includes both the study of national objectives to be achived and the means used for securing those. -- Ceeil V. Crabb

## Elements of foreign policy

1. Size of state territory
2. Geographical factors
3. Level and nature of economic development
4. Cultural and historical factors
5. Social structure
6. Governement structure
7. Internal situation
8. Values, talents, experiences and personalities of leaders
9. POlitical accountability
10. Ideology
11. Diplomacy
12. International power structure (Global strategic environment)
13. Public opinion
14. Technology
15. External environment
16. Alliances and international treaties (Bilateral and multilateral)

Domestic factors

1. Size and population composition
2. Geography
3. Culture and history
4. Economic development
5. Technology
6. National capacity
7. Public mood and opinion
8. Political organization
9. Role of press

External determinants

1. International law
2. International organizations

## Some terminologies and stories

Diplomatic immunity

Diplomatic immunity is a kind of legal immunity and a policy held between governments that ensure that diplomats are given safe passage and are considered not susceptible to lawsuit or prosecution under the host country's laws, but they can still be expelled.

Diplomatic Immunity finds its origin from as international law in the Vienna Convention on Diplomatic Relations (1961), though the concept and custom have a much longer history. Diplomatic immunity as an institution developed to allow for

Diplomatic asylum

Diplomatic asylum is not established in any international law. It derives its existence from Article 14 of the Universal Declaration of Human Rights, which states: "Everyone has the right to seek and to enjoy in other countries asylum from persecution."

The European Convention on Human Rights and the International Covenant on Civil and Political Rights also enshrine this law.

The International Court of Justice has emphasised that in the absence of treaty or customary rules to the contrary, a decision by a mission to grant asylum involves a derogation from the soverignty of the receiving state.

The Organization of American States agreed a convention in 1954.

In a broad sense, according to the UN, it is protection which is granted by a country outside its own borders, and particularly through its diplomatic missions.

A case of Julian Assange

Julian Assange, founder of whistleblowing website Wikileaks, is facing extradition from the US to Sweden over rape and sexual assault allegations. Recently he had spent a night in Ecuadorian embassy in London after claiming diplomatic asylum. The Government authorities said that by spending the night at the embassy he has breached his bail conditions and faces arrest, but Ecuadorian authorities said they were "studying and analysing" his request.

As per the customs, local police and security forces are not permitted to enter an embassy unless they have the express permission of the ambassador -- even though the embassy remains the territory of the host nation. This rule was set our in 1961 Vienna Convention on Diplomatic Relations when it codified a custom in place for centuries by establishing the "rule of inviolability". Thus, by being at the embassy, Assange was on diplomatic territory and beyond the reach of teh police. Assange fears if he is sent to Sweden it may then lead to him being sent to the US to face charges over Wikileaks, for which he could face the death penalty.

## India-Nepal relations

The Republic of India and the Federal Democratic Republic of Nepal initiated their relationship with the 1950 Indo-Nepal Treaty of Peace and Friendship and accompanying secret letters that defined security relations between the two countries, and an agreement governing both bilateral trade and trade transiting Indian territory. The 1950 treaty and letters exchanged between the Indian government and Rana rulers of Nepal, stated that "neither government shall tolerate any threat to the security of the other by a foreign aggressor" and obligated both sides "to inform each other of any serious friction or misunderstanding with any neighboring state likely to cause any breach in the friendly relations subsisting between the two governments." These accords cemented a "special relationship" between India and Nepal. The treaty also granted Nepalese, the same economic and educational opportunities as Indian citizens in India, while accounting for preferential treatment to Indian citizens and businesses compared to other nationalities in Nepal. The Indo-Nepal border is open; Nepalese and Indian nationals may move freely across the border without passports or visas and may live and work in either country. However, Indians aren't allowed to own land-properties or work in government institutions in Nepal, while Nepalese nationals in India are allowed to work in Indian government institutions (except in some states and some civil services the IFS, IAS, and IPS). After years of dissatisfaction by the Nepalese government, India in 2014, agreed to revise and adjust the treaty to reflect the current realities. However, the modality of adjustment hasn't been made clear by either side.

Despite the close linguistic, marital, religious, and, cultural ties, at people to people level between Indians and Nepalese, since late 2015, political issues and border disputes have strained relations between the two countries with anti-Indian sentiment growing amongst the government and people of Nepal. Further because of border disputes between the two countries, a boundary agreement hasn't yet been ratified by either government.

Independent political history
1950-1970

This section possibly contains original research. Please improve it by verifying the claims made and adding inline citations. Statements consisting only of original research should be removed. (November 2019) (Learn how and when to remove this template message)
The foundation of relations between India and Nepal was laid with Indo-Nepalese friendship Treaty in 1950. In the 1950s, the Rana rulers of Nepal welcomed close relations with India, fearing a China-backed communist overthrow of their (Rana) autocratic regime.[citation needed] Rana rule in Nepal however collapsed within 3 months of signing the 1950 Indo-Nepal Treaty of Peace and Friendship, only to be replaced by the only pro-Indian party of the time - Nepali Congress. As the number of Indians living and working in Nepal's Terai region increased and the involvement of India in Nepal's politics deepened in the 1960s and after, so too did Nepal's discomfort with the special relationship.[citation needed] India's influence over Nepal increased throughout the 1950s. The Nepalese Citizenship Act of 1952 allowed Indians to immigrate to Nepal and acquire Nepalese citizenship with ease-a source of huge resentment in Nepal (This policy was not changed until 1962 when several restrictive clauses were added to the Nepalese constitution). Also in 1952, an Indian military mission was established in Nepal, which consisted of a Major General and 20 other Indian army personnel (later extended to 197 in total). At the same time, Nepal's Royal family's dissatisfaction with India's growing influence began to emerge, and overtures to China were initiated by Nepal as a counterweight to India. Further the Nepalese government, as a deliberate attempt to show pro-USA tilt in Nepalese foreign policy, established diplomatic ties with the state of Israel in June 1, 1960, while the Indian government supported Palestine and remained pro-USSR throughout the cold war.

Following the 1962 Sino-Indian border war, the relationship between Kathmandu and New Delhi thawed significantly. India suspended its support to India-based Nepalese opposition forces (opposing the dissolution of democratic government by King Mahendra). The defeat of Indian forces in 1962 provided Nepal with the breathing space and Nepal extracted several concessions in trade. In exchange, through a secret accord concluded in 1965, similar to an arrangement that had been suspended in 1963, India won a monopoly on arms sales to Nepal.

In 1969 relations again became stressful as Nepal challenged the existing mutual security arrangement and asked that the Indian security checkposts and liaison group be withdrawn. Resentment also was expressed against the 1950s TPF. India withdrew its military check-posts and liaison group consisting of 23 military personnel in 1970 from Nepal, although the treaty was not abrogated.

Tensions came to a head in the mid-1970s, when Nepal pressed for substantial changes in the trade and transit treaty and openly criticised Sikkim's 1975 annexation by India. In 1975 King Birendra Bir Bikram Shah Dev against the backdrop of Indian annexation of Nepal's close neighbor 'The Kingdom of Sikkim' proposed Nepal to be recognized internationally as a 'Zone of Peace' where military competition would be off limits. Nepal's proposal immediately received support from Pakistan and China, but not from India. In New Delhi's view, if the king's proposal did not contradict the 1950 treaty that the-then Indian government had signed with the Rana rulers of Nepal, it was unnecessary; if it was a repudiation of the special relationship, it represented a possible threat to India's security and could not be endorsed. In 1984 Nepal repeated the proposal, but there was no reaction from India. Nepal continually promoted the proposal in international forums and by 1990 it had won the support of 112 countries including the US, the UK, and France.

1970-1980
In 1978 India agreed to separate trade and transit treaties, satisfying a long-term Nepalese demand. However, much to the annoyance of Nepalese Royal Palace and in continued violation of the 1950s PFT, India consistently allowed the opposition parties of Nepal to use Indian soil to launch agitation against the Nepalese government and refused to endorse Nepal as a Zone of Peace. In 1988, when the two treaties were up for renewal, Nepal refused to accommodate India's wishes for a single trade and transit treaty stating that 'it violates the principle of freedom to trade'. Thereafter, both India and Nepal took a hard-line position that led to a serious crisis in India-Nepal relations. Nepalese leaders asserted the position that as per the UN charter, transit privileges were "a fundamental and a permanent right of a land-locked country" and thus India's demand for a single treaty was unacceptable. So, after two extensions, the two treaties expired on 23 March 1989, resulting in a virtual Indian economic blockade of Nepal that lasted until late April 1990. As time passed Indian economic sanctions over Nepal steadily widened. For example, preferential customs and transit duties on Nepalese goods entering or passing through India (whether imports or exports) were discontinued. Thereafter India let agreements relating to oil processing and warehouse space in Calcutta for goods destined to Nepal expire. Aside from these sanctions, India cancelled all trade credits it had previously extended to Nepal on a routine basis.

To withstand the renewed Indian pressure, Nepal undertook a major diplomatic initiative to present its case on trade and transit matters to the world community. The relationship with India was further strained in 1989 when Nepal decoupled its rupee from the Indian rupee which previously had circulated freely in Nepal. India retaliated by denying port facilities in Calcutta to Nepal, thereby preventing delivery of oil supplies from Singapore and other sources. In historian Enayetur Rahim's view, "the economic consequences of the dispute... were enormous. Nepal's GDP growth rate plummeted from 9.7% in 1988 to 1.5% in 1989. This had a lot to do with the decreased availability of goods. Shortly after the imposition of sanctions, Nepal experienced serious deficiencies of important goods such as coal, fuel, oil, medicine and spare parts. Nepal also suffered economically from higher tariffs, the closure of border points and the tense political atmosphere. From one of the most thriving economies in Asia, Nepal was now quickly finding itself in the league of World's poorest nation." Although economic issues were a major factor in the two countries' confrontation, Indian dissatisfaction with Nepal's decision to impose work permits over Indians living in Nepal and Nepal government's attempt to acquire Chinese weaponry in 1988 played an important role. India linked security with economic relations and insisted on reviewing India-Nepal relations as a whole. After failing to receive support from wider international community, Nepalese government backed down from its position to avoid the worsening economic conditions. Indian government, with the help of Nepalese opposition parties operating from India, managed to bring a change in Nepal's political system, in which the king was forced to institute a parliamentary democracy. The new government, led by pro-India parties, sought quick restoration of amicable relations with India.

1990s
The special security relationship between New Delhi and Kathmandu was re-established during the June 1990 New Delhi meeting of Nepal's prime minister Krishna Prasad Bhatarai and Indian prime minister V.P. Singh, after India ended its 13-month-long economic blockade of Nepal. During the December 1991 visit to India by Nepalese prime minister Girija Prasad Koirala, the two countries signed new, separate trade and transit treaties and other economic agreements designed to accord Nepal additional economic benefits.

Indian-Nepali relations appeared to be undergoing still more reassessment when Nepal's prime minister Man Mohan Adhikary visited New Delhi in April 1995 and insisted on a major review of the 1950 peace and friendship treaty which Nepal believed was enabling an ongoing demographic shift in Nepal's Terai region. In the face of benign statements by his Indian hosts relating to the treaty, Adhikary sought greater economic independence for his landlocked nation while simultaneously striving to improve ties with China.

In June 1990, a joint Kathmandu-New Delhi communique was issued pending the finalisation of a comprehensive arrangement covering all aspects of bilateral relations, restoring trade relations, reopening transit routes for Nepal's imports, and formalising respect of each other's security concerns. Essentially, the communiqu? announced the restoration of the status quo ante and the reopening of all border points, and Nepal agreed to various concessions regarding India's commercial privileges. Kathmandu also announced that lower cost was the decisive factor in its purchasing arms and personnel carriers from China and that Nepal was advising China to withhold delivery of the last shipment.

2000s
In 2005, after King Gyanendra took over, Nepalese relations with India soured. However, even after the restoration of democracy, in 2008, Prachanda, the Prime Minister of Nepal, visited India, in September 2008 only after visiting China, breaking the long-held tradition of Nepalese PM making India as their first port-of-call. When in India, he spoke about a new dawn, in the bilateral relations, between the two countries. He said, "I am going back to Nepal as a satisfied person. I will tell Nepali citizens back home that a new era has dawned. Time has come to effect a revolutionary change in bilateral relations. On behalf of the new government, I assure you that we are committed to make a fresh start."

In 2006, the newly formed democratic parliament of Nepal passed the controversial citizenship bill that led to distribution of Nepalese citizenship to nearly 4 million stateless immigrants in Nepal's Terai by virtue of naturalisation. While the Indian government welcomed the reformed citizenship law, certain section of Nepalese people expressed deep concerns regarding the new citizenship act and feared that the new citizenship law might be a threat to Nepalese sovereignty. The citizenship bill passed by the Nepalese parliament in 2006 was the same bill that was rejected by Late King Birendra in 2000 before he along with his entire family was massacred. Indian government formally expressed sorrow at the death of Late King Birendra of Nepal.

In 2008, Indo-Nepal ties got a further boost with an agreement to resume water talks after a 4-year hiatus. The Nepalese Water Resources Secretary Shanker Prasad Koirala said the Nepal-India Joint Committee on Water Resources meet decided to start the reconstruction of the breached Koshi embankment after the water level went down. During the Nepal PM's visit to New Delhi in September the two Prime Ministers expressed satisfaction at the age-old close, cordial and extensive relationships between their states and expressed their support and co-operation to further consolidate the relationship.

The two issued a 22-point statement highlighting the need to review, adjust and update the 1950 Treaty of Peace and Friendship, amongst other agreements. India would also provide a credit line of up to \$15 million to Nepal to ensure uninterrupted supplies of petroleum products, as well as lift bans on the export of rice, wheat, maize, sugar and sucrose for quantities agreed to with Nepal. India would also provide \$2 million as immediate flood relief.
In return, Nepal will take measures for the "promotion of investor friendly, enabling business environment to encourage Indian investments in Nepal."

2010s
In 2010 India extended a Line of credit worth US\$50 million & 80,000 tonnes of foodgrains. Furthermore, a three-tier mechanism at the level of ministerial, secretary and technical levels will be built to push forward discussions on the development of water resources between the two sides. Politically, India acknowledged a willingness to promote efforts towards peace in Nepal. Indian External affairs minister Pranab Mukherjee promised the Nepali Prime Minister Prachanda that he would "extend all possible help for peace and development."

However, in recent years, the increasing dominance of Maoism in Nepal's domestic politics, along with the strengthening economic and political influence of the People's Republic of China has caused the Nepalese government to gradually distance its ties with India, though Nepal still does support India at the UN. Prime Minister of India Narendra Modi visited Nepal in August 2014, marking the first official visit by an Indian prime minister in 17 years. During his visit, Indian government agreed to provide Nepal with US\$1 billion as concessional line of credit for various development purposes and a HIT formula, but he insisted that Indian immigrants in Nepal don't pose a threat to Nepal's sovereignty and therefore open border between Nepal and India should be a bridge and not a barrier. Nepal and India signed an important deal on 25 November 2014 as per which India will build a 900 MW hydropower plant at a cost of another US\$1 billion. An amount of US\$250 million has been granted to Nepal as a part of the agreements signed on 22 February 2016 for post-earthquake reconstruction.

A perpetual issue for many people of Nepali origin; the birthplace of Gautama Buddha has long been a cultural and social issue devoid from the political landscape of both Nepal and India. However, since the souring of relations between the two countries, the issue has been used to undermine relations between the two countries both politically and socially. The two-day-long International Buddhist conference in Kathmandu which ran from May 19-20, 2016 marked Vesak and the 2,560th birthday of the Buddha was also used to promote the Buddha's birthplace which lies in modern-day Nepal. The decision of the Nepal Culture Ministry to change the theme, "Preservation and Development of Buddhist Heritage of Nepal" with the sub-theme "Lumbini - Birthplace of Buddha" under the name "Lumbini - Fountainhead of Buddhism" was met with criticism from India which subsequently boycotted the conference due to this and on the back of China's supposed monetary involvement in the conference. Nepali Prime Minister, K.P. Oli told the media that the conference, "should help us make clear to the world that Buddha was born in Nepal and that Buddhist philosophy is the product of Nepal".

In early March 2017, the fatal shooting of a Nepali man who was protesting Indian-occupation on disputed territory between India and Nepal sparked protests in the capital Kathmandu. Indian troops had previously prevented a group of Nepalese farmers living along the border from completing a culvert in the disputed area which ultimately led to protests. It was considered rare for India to retaliate with gunfire.


Border disputes
Main article: Territorial disputes of India and Nepal
The Territorial disputes of India and Nepal include Kalapani 400 km2 at India-Nepal-China tri-junction in Western Nepal and Susta 140 km2 in Southern Nepal. Nepal claims that the river to the west of Kalapani is the main Kali river hence the area should belong to Nepal. But India claims that the river to the west of Kalapani is not the main Kali river, and, therefore the border there should be based on the ridge lines of the mountains Om Parvat to the east of the river. The river borders the Nepalese province of Sudurpashchim and the Indian state of Uttarakhand. The Sugauli Treaty signed by Nepal and British India on 4 March 1816 locates the Kali River as Nepal's western boundary with India. Subsequent maps drawn by British surveyors show the source of the boundary river at different places. This discrepancy in locating the source of the river led to boundary disputes between India and Nepal, with each country producing maps supporting their own claims. Indian government, however, from 1962 onward, forwarded the argument that border should be based on the ridge lines of the mountain Om Parvat. The Kali River runs through an area that includes a disputed area of about 400 km? around the source of the river although the exact size of the disputed area varies from source to source. The dispute intensified in 1997 as the Nepali parliament considered a treaty on hydro-electric development of the river. India and Nepal differ as to which stream constitutes the source of the river. Nepal has reportedly tabled an 1856 map from the British India Office to support its position. Kalapani has been controlled by India's Indo-Tibetan border security forces since the Sino-Indian War with China in 1962. In 2015, the Nepalese parliament objected an agreement between India and China to trade through Lipulekh Pass, a mountainous pass in the disputed Kalapani area, stating that the agreement between India and China to trade through Kalapani violates Nepal's sovereign rights over the territory. Nepal has called for the withdrawal of the Indian border forces from Kalapani area.

As the first step for demarcating Indo-Nepal border, survey teams from both countries located and identified missing pillars along the border, and, an agreement was reached to construct new pillars in some places. According to the Nepalese government estimates, of the 8000 boundary pillars along the border, 1,240 pillars are missing, 2,500 require restoration, and, 400 more need to be constructed. The survey teams conducted survey of the border pillars based on the strip maps prepared by the Joint Technical Level Nepal-India Boundary Committee (JTLNIBC). The JTLNIBC was set up in 1981 to demarcate the India-Nepal border and after years of surveying, deliberations and extensions, the Committee had delineated 98 per cent of the India-Nepal boundary, excluding Kalapani and Susta, on 182 strip maps which was finally submitted in 2007 for ratification by both the countries. Unfortunately neither country ratified the maps. Nepal maintained that it cannot ratify the maps without the resolution of outstanding boundary disputes, i.e. Kalapani and Susta. India, on the other hand, awaited Nepal's ratification while at the same time urging it to endorse the maps as a confidence building measure for solving the Kalapani and Susta disputes. In absence of a ratification, the process of completely demarcating the India-Nepal boundary could not be undertaken.

Border crossings
Main articles: Designated border crossings of India and Borders of India
Integrated check posts with immigration and customs facilities are:

Jogbani, Bihar
Sunauli, Uttar Pradesh
Rupaidiha, Uttar Pradesh
Taulihawa-Siddharthnagar (only for India and Nepalese citizens)
Jathi, Bihar

Since 2014 to enhance the collaborative relations between the two nations, Nepal and India started Trans-border bus services from New Delhi to Kathmandu connecting the nation's capital of both countries. The service is in operation by Delhi Bus Corporation (DTC) India and several other private Travel companies. At present(2019), Kathmandu to Delhi bus service, Kathmandu to Siliguri Bus service, Kathmandu to Varanasi, Delhi to Janakpur bus service are in operation.

Trade
India is Nepal's largest trade partner and the largest source of foreign investments, besides providing transit for almost entire third country trade of Nepal. India accounts for over two-third of Nepal's merchandise trade, about one-third of trade in services, one-third of foreign direct investments, almost 100% of petroleum supplies, and a significant share of inward remittances on account of pensioners, professionals and workers working in India In the year 2017-2018, Nepal's total trade with India was about US\$8.2 billion; Nepal's exports to India were about US\$446.5 million; and imports from India were about US\$7.7 billion.

Nepal's main imports from India are petroleum products (28.6%), motor vehicles and spare parts (7.8%), M. S. billet (7%), medicines (3.7%), other machinery and spares (3.4%), coldrolled sheet in coil (3.1%), electrical equipment (2.7%), hotrolled sheet in coil (2%), M. S. wires, roads, coils and bars (1.9%), cement (1.5%), agriculture equipment and parts (1.2%), chemical fertilizer (1.1%), chemicals (1.1%) and thread (1%). Nepal's export basket to India mainly comprises jute goods (9.2%), zinc sheet (8.9%), textiles (8.6%), threads (7.7%), polyester yarn (6%), juice (5.4%), catechue (4.4%), Cardamom (4.4%), wire (3.7%), tooth paste (2.2%) and M. S. Pipe (2.1%).

Human trafficking
Human trafficking in Nepal is a serious concern. An estimated 100,000-200,000 Nepalese in India are believed to have been trafficked. Sex trafficking is particularly rampant within Nepal and to India, with as many as 5,000-10,000 women and girls trafficked to India alone each year. The seriousness of trafficking of Nepalese girls to India was highlighted by CNN Freedom Project's documentary: Nepal's Stolen Children. Maiti Nepal has rescued more than 12,000 stolen Nepalese children from sex trafficking since 1993.

2015 Madhesi crisis and Nepal
Main article: 2015 Nepal fuel crisis

## History and Evolution of Non-Aligned Movement

August 22, 2012

History

The Non-Aligned Movement (NAM) was created and founded during the collapse of the colonial system and the independence struggles of the peoples of Africa, Asia, Latin America and other regions of the world and at the height of the Cold War. During the early days of the Movement, its actions were a key factor in the decolonization process, which led later to the attainment of freedom and independence by many countries and peoples and to the founding of tens of new sovereign States. Throughout its history, the Movement of Non-Aligned Countries has played a fundamental role in the preservation of world peace and security.

While some meetings with a third-world perspective were held before 1955, historians consider that the Bandung Asian-African Conference is the most immediate antecedent to the creation of the Non-Aligned Movement. This Conference was held in Bandung on April 18-24, 1955 and gathered 29 Heads of States belonging to the first post-colonial generation of leaders from the two continents with the aim of identifying and assessing world issues at the time and pursuing out joint policies in international relations.

The principles that would govern relations among large and small nations, known as the "Ten Principles of Bandung", were proclaimed at that Conference. Such principles were adopted later as the main goals and objectives of the policy of non-alignment. The fulfillment of those principles became the essential criterion for Non-Aligned Movement membership; it is what was known as the "quintessence of the Movement" until the early 1990s.

In 1960, in the light of the results achieved in Bandung, the creation of the Movement of Non-Aligned Countries was given a decisive boost during the Fifteenth Ordinary Session of the United Nations General Assembly, during which 17 new African and Asian countries were admitted. A key role was played in this process by the then Heads of State and Government Gamal Abdel Nasser of Egypt, Kwame Nkrumah of Ghana, Shri Jawaharlal Nehru of India, Ahmed Sukarno of Indonesia and Josip Broz Tito of Yugoslavia, who later became the founding fathers of the movement and its emblematic leaders.

Six years after Bandung, the Movement of Non-Aligned Countries was founded on a wider geographical basis at the First Summit Conference of Belgrade, which was held on September 1-6, 1961. The Conference was attended by 25 countries: Afghanistan, Algeria, Yemen, Myanmar, Cambodia, Srilanka, Congo, Cuba, Cyprus, Egypt, Ethiopia, Ghana, Guinea, India, Indonesia, Iraq, Lebanon, Mali, Morocco, Nepal, Saudi Arabia, Somalia, Sudan, Syria, Tunisia, Yugoslavia.

The Founders of NAM have preferred to declare it as a movement but not an organization in order to avoid bureaucratic implications of the latter.

The membership criteria formulated during the Preparatory Conference to the Belgrade Summit (Cairo, 1961) show that the Movement was not conceived to play a passive role in international politics but to formulate its own positions in an independent manner so as to reflect the interests of its members.

Thus, the primary of objectives of the non-aligned countries focused on the support of self-determination, national independence and the sovereignty and territorial integrity of States; opposition to apartheid; non-adherence to multilateral military pacts and the independence of non-aligned countries from great power or block influences and rivalries; the struggle against imperialism in all its forms and manifestations; the struggle against colonialism, neocolonialism, racism, foreign occupation and domination; disarmament; non-interference into the internal affairs of States and peaceful coexistence among all nations; rejection of the use or threat of use of force in international relations; the strengthening of the United Nations; the democratization of international relations; socioeconomic development and the restructuring of the international economic system; as well as international cooperation on an equal footing.

Since its inception, the Movement of Non-Aligned Countries has waged a ceaseless battle to ensure that peoples being oppressed by foreign occupation and domination can exercise their inalienable right to self-determination and independence.

During the 1970s and 1980s, the Movement of Non-Aligned Countries played a key role in the struggle for the establishment of a new international economic order that allowed all the peoples of the world to make use of their wealth and natural resources and provided a wide platform for a fundamental change in international economic relations and the economic emancipation of the countries of the South.

During its nearly 50 years of existence, the Movement of Non-Aligned Countries has gathered a growing number of States and liberation movements which, in spite of their ideological, political, economic, social and cultural diversity, have accepted its founding principles and primary objectives and shown their readiness to realize them. Historically, the non-aligned countries have shown their ability to overcome their differences and found a common ground for action that leads to mutual cooperation and the upholding of their shared values.

The ten principles of Bandung

Respect of fundamental human rights and of the objectives and principles of the Charter of the United Nations.
Respect of the sovereignty and territorial integrity of all nations.
Recognition of the equality among all races and of the equality among all nations, both large and small.
Non-intervention or non-interference into the internal affairs of another -country.
Respect of the right of every nation to defend itself, either individually or collectively, in conformity with the Charter of the United Nations.
A. Non-use of collective defense pacts to benefit the specific interests of any of the great powers.

B. Non-use of pressures by any country against other countries.
Refraining from carrying out or threatening to carry out aggression, or from using force against the territorial integrity or political independence of any country.
Peaceful solution of all international conflicts in conformity with the Charter of the United Nations.
Promotion of mutual interests and of cooperation.
Respect of justice and of international obligations.
Evolution

The creation and strengthening of the socialist block after the defeat of fascism in World War II, the collapse of colonial empires, the emergence of a bipolar world and the formation of two military blocks (NATO and the Warsaw Pact) brought about a new international context that led to the necessity of multilateral coordination fora between the countries of the South .

In this context, the underdeveloped countries, most of them in Asia and Africa, felt the need to join efforts for the common defense of their interests, the strengthening of their independence and sovereignty and the cultural and economic revival or salvation of their peoples, and also to express a strong commitment with peace by declaring themselves as "non-aligned" from either of the two nascent military blocks.

In order to fulfill the aims of debating on and advancing a strategy designed to achieve such objectives, the Bandung Asian-African Conference was held in Indonesia in April 1955. It was attended by 29 Heads of State and Government of the first postcolonial generation of leaders and its expressed goal was to identify and assess world issues at the time and coordinate policies to deal with them.

Although the Asian and African leaders who gathered in Bandung might have had differing political and ideological views or different approaches toward the societies they aspired to build or rebuild, there was a common project that united them and gave sense to a closer coordination of positions. Their shared program included the political decolonization of Asia and Africa. Moreover, they all agreed that the recently attained political independence was just a means to attain the goal of economic, social and cultural independence.

The Bandung meeting has been considered as the most immediate antecedent of the founding of the Movement of Non-Aligned Countries, which finally came into being six years later on a wider geographical basis when the First Summit Conference was held in Belgrade on September 1-6, 1961. This gathering was attended by the Heads of State and Government of 25 countries and observers from another three nations.

This First Summit of the Movement of Non-Aligned Countries was convened by the leaders of India, Indonesia, Egypt, Syria and Yugoslavia. On April 26, 1961, the Presidents of the Arab Republic of Egypt (Nasser) and Yugoslavia (Tito) addressed the Heads of State and Government of 21 "non-Aligned" countries and suggested that, taking recent world events and the rise of international tensions into account, a Conference should be held to promote an improvement in international relations, a resistance to policies of force and a constructive settlement of conflicts and other issues of concern in the world.

The Movement played an important role in the support of nations which were struggling then for their independence in the Third World and showed great solidarity with the most just aspirations of humanity. It contributed indisputably to the triumph in the struggle for national independence and decolonization, thus gaining considerable diplomatic prestige.

As one Summit after another was held in the 1960s and 1970s, "non alignment", turned already into the "Movement of Non-Aligned Countries" that included nearly all Asian and African countries, was becoming a forum of coordination to struggle for the respect of the economic and political rights of the developing world. After the attainment of independence, the Conferences expressed a growing concern over economic and social issues as well as over strictly political matters.

Something that attested to that was the launching at the Algiers Conference in 1973 of the concept of a "new international economic order."

By the end of the 1980s, the Movement was facing the great challenge brought about by the collapse of the socialist block. The end of the clash between the two antagonistic blocks that was the reason for its existence, name and essence was seen by some as the beginning of the end for the Movement of Non-Aligned Countries.

The Movement of Non-Aligned Countries could not spare itself difficulties to act effectively in an adverse international political situation marked by hegemonic positions and unipolarity as well as by internal difficulties and conflicts given the heterogeneity of its membership and, thus, its diverse interests.

Nevertheless, and in spite of such setbacks,the principles and objectives of non-alignment retain their full validity and force at the present international juncture. The primary condition that led to the emergence of the Movement of Non-Aligned Countries, that is, non-alignment from antagonistic blocks, has not lost its validity with the end of the Cold War. The demise of one of the blocks has not done away with the pressing problems of the world. On the contrary, renewed strategic interests bent on domination grow stronger and, even, acquire new and more dangerous dimensions for underdeveloped countries.

During the 14th Summit of the Non-Aligned Movement in Havana, Cuba in September 2006, the Heads of States and Governments of the member countries reaffirmed their commitment to the ideals, principles and purposes upon which the movement was founded and with the principles and purposes enshrined in the United Nations Charter.

The Heads of States and Governments stated their firm belief that the absence of two conflicting blocs in no way reduces the need to strengthen the movement as a mechanism for the political coordination of developing countries. In this regard they acknowledged that it remains imperative to strengthen and revitalize the movement. To do so, they agreed to strengthen concrete action, unity and solidarity between all its members, based on respect for diversity, factors which are essential for the reaffirmation of the identity and capacity of the movement to influence International relations.

They also stressed the need to promote actively a leading role for the movement in the coordination of efforts among member states in tackling global threats.

Inspired by the principles and purposes which were brought to the Non-Aligned Movement by the Bandung principles and during the First NAM Summit in Belgrade in 1961, the Heads of States and Governments of the member countries of the Non-Aligned Movement adopted in their 14th Summit in Havana the following purposes and principles of the movement in the present International juncture:

I. Purposes:

a. To promote and reinforce multilateralism and, in this regard, strengthen the central role that the United Nations must play.

b. To serve as a forum of political coordination of the developing countries to promote and defend their common interests in the system of international relations

c. To promote unity, solidarity and cooperation between developing countries based on shared values and priorities agreed upon by consensus.

d. To defend international peace and security and settle all international disputes by peaceful means in accordance with the principles and the purposes of the UN Charter and International Law.

e. To encourage relations of friendship and cooperation between all nations based on the principles of International Law, particularly those enshrined in the Charter of the United Nations.

f. To promote and encourage sustainable development through international cooperation and, to that end, jointly coordinate the implementation of political strategies which strengthen and ensure the full participation of all countries, rich and poor, in the international economic relations, under equal conditions and opportunities but with differentiated responsibilities.

g. To encourage the respect, enjoyment and protection of all human rights and fundamental freedoms for all, on the basis of the principles of universality, objectivity, impartiality and non-selectivity, avoiding politicization of human rights issues, thus ensuring that all human rights of individuals and peoples, including the right to development, are promoted and protected in a balanced manner.

h. To promote peaceful coexistence between nations, regardless of their political, social or economic systems.

i. To condemn all manifestations of unilateralism and attempts to exercise hegemonic domination in international relations.

j. To coordinate actions and strategies in order to confront jointly the threats to international peace and security, including the threats of use of force and the acts of aggression, colonialism and foreign occupation, and other breaches of peace caused by any country or group of countries.

k. To promote the strengthening and democratization of the UN, giving the General Assembly the role granted to it in accordance with the functions and powers outlined in the Charter and to promote the comprehensive reform of the United Nations Security Council so that it may fulfill the role granted to it by the Charter, in a transparent and equitable manner, as the body primarily responsible for maintaining international peace and security.

l. To continue pursuing universal and non-discriminatory nuclear disarmament, as well as a general and complete disarmament under strict and effective international control and in this context, to work towards the objective of arriving at an agreement on a phased program for the complete elimination of nuclear weapons within a specified framework of time to eliminate nuclear weapons, to prohibit their development, production, acquisition, testing, stockpiling, transfer, use or threat of use and to provide for their destruction.

m. To oppose and condemn the categorization of countries as good or evil based on unilateral and unjustified criteria, and the adoption of a doctrine of pre-emptive attack, including attack by nuclear weapons, which is inconsistent with international law, in particular, the international legally-binding instruments concerning nuclear disarmament and to further condemn and oppose unilateral military actions, or use of force or threat of use of force against the sovereignty, territorial integrity and independence of Non-Aligned countries.

n. To encourage States to conclude agreements freely arrived at, among the States of the regions concerned, to establish new Nuclear Weapons-Free Zones in regions where these do not exist, in accordance with the provisions of the Final Document of the First Special Session of the General Assembly devoted to disarmament (SSOD.1) and the principles adopted by the 1999 UN Disarmament Commission, including the establishment of a Nuclear Weapons Free Zone in the Middle East. The establishment of Nuclear Weapons-Free Zones is a positive step and important measure towards strengthening global nuclear disarmament and non-proliferation.

o. To promote international cooperation in the peaceful uses of nuclear energy and to facilitate access to nuclear technology, equipment and material for peaceful purposes required by developing countries.

p. To promote concrete initiatives of South-South cooperation and strengthen the role of NAM, in coordination with G.77, in the re-launching of North-South cooperation, ensuring the fulfillment of the right to development of our peoples, through the enhancement of international solidarity.

q. To respond to the challenges and to take advantage of the opportunities arising from globalization and interdependence with creativity and a sense of identity in order to ensure its benefits to all countries, particularly those most affected by underdevelopment and poverty, with a view to gradually reducing the abysmal gap between the developed and developing countries.

r. To enhance the role that civil society, including NGO´s, can play at the regional and international levels in order to promote the purposes, principles and objectives of the Movement.

II. Principles:

a. Respect for the principles enshrined in the Charter of the United Nations and International Law.

b. Respect for sovereignty, sovereign equality and territorial integrity of all States.

c. Recognition of the equality of all races, religions, cultures and all nations, both big and small.

d. Promotion of a dialogue among peoples, civilizations, cultures and religions based on the respect of religions, their symbols and values, the promotion and the consolidation of tolerance and freedom of belief.

e. Respect for and promotion of all human rights and fundamental freedoms for all, including the effective implementation of the right of peoples to peace and development.

f. Respect for the equality of rights of States, including the inalienable right of each State to determine freely its political, social, economic and cultural system, without any kind of interference whatsoever from any other State.

g. Reaffirmation of the validity and relevance of the Movement's principled positions concerning the right to self-determination of peoples under foreign occupation and colonial or alien domination.

h. Non-interference in the internal affairs of States. No State or group of States has the right to intervene either directly or indirectly, whatever the motive, in the internal affairs of any other State.

i. Rejection of unconstitutional change of Governments.

j. Rejection of attempts at regime change

k. Condemnation of the use of mercenaries in all situations, especially in conflict situations.

l. Refraining by all countries from exerting pressure or coercion on other countries, including resorting to aggression or other acts involving the use of direct or indirect force, and the application and/or promotion of any coercive unilateral measure that goes against International Law or is in any way incompatible with it, for the purpose of coercing any other State to subordinate its sovereign rights, or to gain any benefit whatsoever.

m. Total rejection of aggression as a dangerous and serious breach of International Law, which entails international responsibility for the aggressor.

n. Respect for the inherent right of individual or collective self-defense, in accordance with the Charter of the United Nations.

o. Condemnation of genocide, war crimes, crimes against humanity and systematic and gross violations of human rights, in accordance with the UN Charter and International Law.

p. Rejection of and opposition to terrorism in all its forms and manifestations, committed by whomever, wherever and for whatever purposes, as it constitutes one of the most serious threats to international peace and security. In this context, terrorism should not be equated with the legitimate struggle of peoples under colonial or alien domination and foreign occupation for self-determination and national liberation.

q. Promotion of pacific settlement of disputes and abjuring, under any circumstances, from taking part in coalitions, agreements or any other kind of unilateral coercive initiative in violation of the principles of International Law and the Charter of the United Nations.

r. Defense and consolidation of democracy, reaffirming that democracy is a universal value based on the freely expressed will of people to determine their own political, economic, social, and cultural systems and their full participation in all aspects of their life.

s. Promotion and defense of multilateralism and multilateral organizations as the appropriate frameworks to resolve, through dialogue and cooperation, the problems affecting humankind.

t. Support to efforts by countries suffering internal conflicts to achieve peace, justice, equality and development.

u. The duty of each State to fully and in good faith comply with the international treaties to which it is a party, as well as to honor the commitments made in the framework of international organizations, and to live in peace with other States. v. Peaceful settlement of all international conflicts in accordance with the Charter of the United Nations.

w. Defense and promotion of shared interests, justice and cooperation, regardless of the differences existing in the political, economic and social systems of the States, on the basis of mutual respect and the equality of rights.

x. Solidarity as a fundamental component of relations among nations in all circumstances.

y. Respect for the political, economic, social and cultural diversity of countries and peoples.

The movement has succeeded to create a strong front on the International level, representing countries of the third world in the International organizations on top of which the United Nations.

Current Challenges facing the NAM include the necessity of protecting the principles of International law, eliminating weapons of mass destruction , combating terrorism, defending human rights, working toward making the United Nations more effective in meeting the needs of all its member states in order to preserve International Peace , Security and Stability, as well as realizing justice in the international economic system.

On the other hand, the long-standing goals of the Movement remain to be realized. Peace, development, economic cooperation and the democratization of international relations, to mention just a few, are old goals of the non-aligned countries.

In conclusion, The Non-Aligned Movement, faced with the goals yet to be reached and the many new challenges that are arising, is called upon to maintain a prominent and leading role in the current International relations in defense of the interests and priorities of its member states and for achievement of peace and security for mankind.

source: https://mea.gov.in/in-focus-article.htm?20349/History+and+Evolution+of+NonAligned+Movement

## Non aligned movement

Yuba Nath Lamsal

As the 17th summit of the Non-Aligned Movement (NAM) was underway in Margarita Island of Venezuela on September 13-18, a real debate started outside on the role and relevance of the NAM in the changed global scenario. The NAM was created 55 years ago at the height of the Cold War marked by a stiff superpower rivalry and division of the world into two rival camps each led by a super power. The NAM was necessary at that time as many countries of the 'Third World' could not afford to side with any of the two rival blocs but chose to remain neutral. The NAM, therefore, became an appropriate forum for the countries wishing to have equal partnership and friendship with all countries irrespective of their ideological orientation and strategic alignment. But the international situation and scenario are markedly different at present. Now a question has arisen in the international forums and debates:  Is the NAM necessary in the present situation or is it just a waste of resources, energy and time?

 

Common platform

The founding principles of the NAM were anti-colonialism and anti-imperialism, which appealed to many countries in the world that had either recently been liberated or were still waging national liberation movements to free themselves from the yoke of colonialism and imperialism. The NAM, thus, became a common platform for them to push forward their common agendas as specter of imperialism, colonialism and neo-colonialism continued to hang around and afflict the countries around the world, more particularly the developing nations.

Immediately after the World War II, the global power scenario changed. Until the World War II, the United Kingdom was the center of international power as it used to boast that the sun never set in its empire. The fundamental bases of British power and wealth were its colonies. But after the war, the national liberation movement across the globe intensified so rapidly that the erstwhile colonies were liberated one after another, heavily weakening British power. As British power diminished, the United States emerged to fill the vacuum in the international power politics and became the dominant global power, while Soviet Union suddenly came into the international scene as a rival power challenging the domination of the Western powers.

In the juggling for influence and power in the international arena, two distinct rival camps emerged with the capitalist United States leading the North Atlantic Treaty Organisation (NATO) and the communist Soviet Union commanding another rival block called the Warsaw Pact. The rivalry between these two blocs was so intense that the proxy wars between the two rival blocs were more dangerous than the traditional wars fought ever in the history of mankind. This was a period called as the 'Cold War' during which many inter-state and intra-state wars were fought killing more people than the number of people killed in  five years during the World War II.

This new scenario caused dilemma to many developing countries. It was more dangerous situation than that of the past. Against this background, the non-aligned movement came into existence. An international conference of 25 developing countries in Belgrade of erstwhile Yugoslavia in 1961 formally gave birth to the NAM, and this gathering was dubbed as the first summit of the NAM. But the NAM did not come so easily and overnight.

There had been quite a lot hidden and otherwise exercises before than that. The Bandung Conference of Indonesia in 1955 was, in fact, a beginning of the NAM as 19 participating countries felt the necessity of an organisation of the neutral countries.  Gamal Abdel Nasser of Egypt, Kwame Nkrumah of Ghana, Jawaharlal Nehru of India, Sukarno of Indonesia and Josip Broz Tito of Yugoslavia were the mastermind behind this movement in which Nepal later joined as one of the founding members.

The Bandung Conference not only drew an outline of the NAM but also set some fundamental principles governing the new international organisation, which were later called as the "Ten Principles of Bandung". However, the 'Ten Bandung Principles' were later modified in the first NAM Summit in Belgrade and shortened to five points, which are famously known as the 'Five Principles of Peaceful Co-existence' or ' Panchasheel' as the fundamental basis of international relations.

The non-aligned movement was initiated at a time when the colonial system was in decline and independence struggles raged across Africa, Asia, Latin America and other regions of the world, which provided a hope of a better international world order for hitherto oppressed and exploited countries. Started humbly with 25 countries, NAM has now 120 members, although the organisation appears to be more in name rather than in action especially after the end of the Cold War.

Nepal is a founder member of the NAM. It participated in several rounds of formal and informal discussions on the need and modality of the NAM and its formal announcement in the Belgrade summit in 1961. The participating countries in the first NAM Summit were: Nepal, Afghanistan, Algeria, Yemen, Myanmar, Cambodia, Sri Lanka, Congo, Cuba, Cyprus, Egypt, Ethiopia, Ghana, Guinea, India, Indonesia, Iraq, Lebanon, Mali, Morocco, Saudi Arabia, Somalia, Sudan, Syria, Tunisia and Yugoslavia.

Nepal strictly adheres to the principles of the non-aligned movement in the conduct of its foreign policy, international relations and diplomacy. The Constitution of the Federal Democratic Republic of Nepal has incorporated these principles as the basic guiding principles of Nepal's foreign policy. This, in itself, is the testament of Nepal's unflinching faith and commitment to the NAM and its principles. Moreover, the fundamental principles of NAM or 'Panchaseela' are more important for Nepal as these principles have their original roots in Nepal. Lord Buddha, who was born in Nepal, propounded the 'Panchasheela' consisting of five codes of human conduct and international relations some 2500 year ago.

Lost charm

The NAM is, perhaps, the first international organisation that advocated the rights and interests of the oppressed and exploited countries of the South and raised voice against the countries of the north. After the collapse of the Soviet bloc and the end of the Cold War, there is no dearth of analysts both in the developed and developing countries alike who raise the question on the role and relevance of the non-aligned movement. The NAM has, of course, lost its original charm and but not its relevance.

The world and international balance of power definitely changed over the years and decades. The world is no longer bipolar nor will the present state of unipolarity stay forever. The world scenario has changed and is bound to keep on changing, continuously and steadily, in future, too, which is the law of nature.  Several poles are slowly emerging challenging the US-led unipolar state, thus, requiring even stronger international movements to bring the developing countries together into a common forum for collectively safeguarding their common and shared interests refraining from siding with any of the poles, groups and blocs.

The NAM may appear irrelevant at present given the state of global order, but situation will not always remain as it is now and different world order is sure to emerge in which the NAM may be more relevant. But Non-Aligned Movement (NAM) requires reforms in itself with newer strategies and concepts to work better in coping with the newly emerged international situation and in achieving the shared objectives of the member countries.

source: http://therisingnepal.org.np/news/14500
