\begin{questions}

\question What are the prospects of Foreign Investment in Nepal ?

\begin{solution}
Nepal has been pursuing a liberal foreign investment policy and been striving to create an investment- friendly environment to attract FDIs into the country. Our tax slabs one of the lowest and our position is fairly good in ease of doing business. Profitable areas of investment include hydropower, industrial manufacturing, services, tourism, construction, agriculture, minerals and energy.

Nepal encourages foreign investment both as joint venture operations with Nepalese investors or as 100 per cent foreign-owned enterprises. The few sectors that are not open to foreign investment are either reserved for national entrepreneurs in order to promote small local enterprises and protect indigenous skills and expertise or are restricted for national security reasons. Approval of the GoN is required for foreign investment in all sectors. No foreign investment is allowed in cottage industries. However, no restriction is placed on transfer of technology in cottage industries.

Most investment gurus believe that agriculture and mining will produce the best returns around the world in the next 20-30 years. Food prices are expected to go up because the growing middle class population in emerging markets will demand more expensive food including meat and more jewelry. Worldwide inflation will be higher than expected; so holding precious metals will be better than holding cash.

Nepal is close to India and China which will have the largest surge in the middle class population in the history of the world. As families become smaller and wealthier, they will start eating well. Meat consumption will rise. It will take more agricultural resources to produce more meat.

These families will also be more interested in traveling. Due to proximity, Nepal is a prime destination for both Chinese and Indian tourists.

Investment opportunities in Nepal

Land, Land and More Fertile Land

Although land prices in the Terai and rural areas in Nepal are starting to go up, they are still cheap. Land can provide dividends in terms of crops while waiting for the value to go up in a couple of decades.

Jeremy Grantham, a famous investor who predicted the 2007 financial meltdown, predicts that state-of-the-art organic farming is the best investment in the world now. In Nepal, we can combine both traditional and modern organic farming techniques to grow food in anticipation of the rapid food price increase.

Tourism Investments

Nepal is the country in the world which is sandwiched between two fastest growing large economies. India and China will have a huge growth in middle class population eager to travel. Nepal can tap the growing tourism market by anticipating where Chinese and Indian tourists may want to spend.

Buying shares in tourism-related stocks such as hotels, airlines or restaurants is a passive way to tap this potential. You can also open a resort or travel agency in anticipation of the boom. If you open up your own venture, the key to success is to be appealing and different from others.

Hydropower

Potential of hydropower in Nepal is huge. While investing in large-scale hydropower plants may need huge sum, it is possible to buy shares in related companies when they go public.

Several hydropower projects are underway in Nepal. In the next 10 years, several of them will become public. This will provide a good opportunity for an ordinary investor without millions of rupees to invest. For large scale investors, projects await in number. Nepal concluded a much awaited Power Trade Agreement with India in 2014 paving the way for trade of electric power just like other marketable commodities. This now ensures predictability of market once electricity is produced.

Outsourcing from US, Europe and Australia

Most foreign companies are looking to outsource programming, research or labor-intensive work to developing countries. These companies will save a substantial amount of money by doing so. Such outsourcing opportunities exist especially in web programming because of a large number of students interested in computer engineering in Nepal.

Medical Tourism

Nepal has produced some of the best doctors around the world. Surgeons from Nepali hospitals also do surgeries in Singapore, UK and USA. It is true that Nepali hospitals lack the infrastructure and equipment found in developed countries, but the quality of doctors is high.

So a good opportunity to invest is in medical tourism in Nepal. Healthcare services in the developed world is expensive. A simple bypass surgery costs around a hundred thousand dollars there, while the same surgery can be done in Nepal at a fraction of the price.

Since Nepal is a country endowed with natural beauty, visiting Nepal for pleasure as well as medical reasons should be an attraction.

Investment Board

With the view to attracting foreign as well as domestic Investment to boost the economy, the Government of Nepal has constituted a high level Investment Board, chaired by the Prime Minister of Nepal. The main objective of this board is to facilitate investors in investing in the potential sectors in Nepal. It provides one window facilities to the investors.

These are a number of investment ideas that can generate significant returns over the years. There will be even more opportunities in Nepal as the middle class population grow in Nepal. Rate of returns on investment in Nepal is high.

source: \url{https://mofa.gov.np/about-nepal/investment-in-nepal/}
\end{solution}

\question What is foreign policy ? Write about foreign policy of Nepal.

\begin{solution}

A country's foreign policy, also called foreign relations or foreign affairs policy, consists of self-interest strategies chosen by the state to safeguard its national interests and to achieve goals within its international relations milieu. The approaches are strategically employed to interact with other countries. In recent decades, due to the deepening level of globalization and transnational activities, states also must interact with non-state actors. These interactions are evaluated and monitored in seeking the benefits of bilateral and multilateral international cooperation. 

Foreign policies of countries have varying rates of change and scopes of intent, which can be affected by factors that change the perceived national interests or even affect the stability of the country itself. The foreign policy of a country can have a profound and lasting impact on other countries and on the course of international relations as a whole, such as the Monroe Doctrine, which began in December 1823, conflicting with the mercantilism policies of 19th-century European countries and the goals of independence of newly formed Central American and South American countries.

The fundamental objective of Nepal's foreign policy is to enhance the dignity of the nation by safeguarding sovereignty, territorial integrity, independence, and promoting economic wellbeing and prosperity of Nepal. It is also aimed at contributing to global peace, harmony and security.

Nepal's foreign policy is guided by the following basic principles:

\begin{enumerate}
\item Mutual respect for each other’s territorial integrity and sovereignty;
\item Non-interference in each other’s internal affairs;
\item Respect for mutual equality;
\item Non-aggression and the peaceful settlement of disputes;
\item Cooperation for mutual benefit;
\item Abiding faith in the Charter of the United Nations;
\item Value of world peace.
\end{enumerate}

Provisions of the Constitution of Nepal on National Interest and Foreign Policy

National Interest (Article 5.1)

Safeguarding of the freedom, sovereignty, territorial integrity, nationality, independence and dignity of Nepal, the rights of the Nepalese people, border security, economic wellbeing and prosperity shall be the basic elements of the national interest of Nepal.

Directive Principles (Article 50.4)

The State shall direct its international relations towards enhancing the dignity of the nation in the world community by maintaining international relations on the basis of sovereign equality, while safeguarding the freedom, sovereignty, territorial integrity and independence and national interest of Nepal.

State Policy (Article 51)

\begin{enumerate}
\item To conduct an independent foreign policy based on the Charter of the United Nations, non-alignment, principles of Panchasheel, international law and the norms of world peace, taking into consideration of the overall interest of the nation, while remaining active in safeguarding the sovereignty, territorial integrity, independence and national interest of Nepal,
\item To review treaties concluded in the past, and make treaties, agreements based on equality and mutual interest.
\end{enumerate}

Put simply, foreign policy is an activity whereby state actors act, react and interact in their bilateral and multilateral dealings with external actors. Its architects straddle two separate environments-internal or domestic environment and external or global environment. Internal political dynamics forms the background context against which a policy is crafted. Factors such as the state's resource base, its geographical position in relation to others, the level of development of its economy, its demographic structure and the political ideology it pursues form the domestic milieu. The international environment is where a nation's foreign policy is actually implemented. Regional perspectives, too, play an equally vital role in approaching the international environment because geopolitics sets the parameters in all aspects of foreign policy. 

Another important consideration is that political regimes may change at regular intervals, but a country’s independence, sovereignty and territorial integrity cannot be compromised at any cost. Nepal needs to maintain a judicious balance in its foreign policy posture vis-à-vis the neighbours and donor countries who practically wield a vital key to Nepal’s economic reconstruction and infrastructural development.

source: \url{https://mofa.gov.np/foreign-policy/}; \url{https://kathmandupost.com/opinion/2019/03/26/foreign-policy-dilemma}
\end{solution}

\question Terrorism is emerging as a competitive industry over the last few decades.”  Analyse the above statement.

\begin{solution}
The turn of the century has provided a new form of industry in form of terrorism. Various violent and religious groups have emerged and declared themselves as extremists. Considering the various perks of being a terrorist group has indeed made themcompetitive.

Reasons for terrorism emerging as competitive industry

Fear of losing financial benefits

Terrorism is associated with lots of money and financial resources in form of illegal taxes and profits from clandestine activities. These provide the required motivation for terrorism to thrive and evolve continuously over a period of time.

Fear of losing power

Terrorism provides individuals and groups to gather power and influence and rule over territories like legitimate government. They develop ability to control activities in a region, which will act as motivator for getting competitive. If they fail to evolve competitively, they fear of losing their territory and power.

Emergence of new groups

The initial terror groups were free from competition due to lack of opposition. But in recent times terrorism has become popular and large number of splinter groups have emerged out that threaten to occupy the void created due to failure of existing terror groups. This competition has kept the existing terror groups to keep evolving.

Increasing threat from security agencies

Earlier only a small number of resources were allocated for fighting terror groups, which allowed them to operate freely. But in recent times security forces have used newer techniques such as satellite tracking and drone attacks to eliminate these groups. In order to avoid getting destroyed, terror groups have turned competitive.

Thus, terrorism has indeed turned into a business venture with the illegitimate finances and power, that threaten to create problems for governments. Security forces have stepped up their presence in order to destroy their operation and maintain control.

source: \url{https://www.upsciq.com/terrorism-emerging-competitive-industry/}
\end{solution}
\end{questions}

## International relations

1. Nepal and United Kingdom have celebrated 200 years of their relationship. How do you view this relationship and what recommendations, if you have, you wish to offer to take the subsisting relationship to the next level ?

\begin{solution}

Nepal established diplomatic relations with the United Kingdom in 1816. Treaty of Friendship between Great Britain and Nepal was signed in 1923 which further formalized relations between the two countries. Ever since the establishment of their diplomatic relations, friendship, mutual understanding, cordiality, cooperation and respect for each other's national interests and aspirations have characterized relationship between the two countries. The UK is also the first country in the world with which Nepal had established diplomatic relations and also the first to have established its Embassy in Kathmandu, the capital of Nepal. This is the country where Nepal had established its first diplomatic mission (Legation) back in 1934. It was elevated to the Ambassador level in 1947 AD.

The UK remained one of the top development partners of Nepal with the annual British aid on an increasing trend. Tourism, trade, education, and British Gurkha connection remained the key dimensions of the bilateral relations.

Since then, relations between the two countries have continued to grow, with a new Treay of Perpetual Peace and Friendship signed in 1950 which expanded areas of cooperation and an exchange of State Visits. Amicable relations continue today; Nepal continues to be the source of recruitment of Gurkha soldiers into the British army -- a tradition dating back to the nineteeth century but still an essential part of Britain's modern army -- and the UK remains one of the most significant providers of development assistance to Nepal.

As one of Great Britain's allies during the two world wars, Nepalese soldiers in hundreds of thousands fought and sacrificed their lives in many battlefields of the world, thus leaving a heritage of deep and sincere friendship in the history of two countries. The Gurkha soldiers are the most visible bridge between Nepal and the United Kingdom. It is to state that the Gurkha's service in the British army started on April 24, 1815, which is continuing till the date spanning over more than two hundred years. The solid foundation of the relation is built on the history of service, sacrifice and bravery of these Gurkha soldiers.

Nepal and United Kingdom are celebrating the bicentenary of bilateral relations between two countries. To mark the 200th year of the beginning of official contacts between the two countries in 1816, a number of programs and events from both sides have been organized in 2016-2017. There have been intermittent to and fro high level visits between Nepal and United Kindom since as early as 1960.

\textbf{Treaties/Memorandum of Understandings/Agreements between the UK and Nepal}

Bilateral consultation mechanism

With a view to enhancing the friendly cooperation and further promoting the bilateral relations Nepal and the United Kingdom have signed a MoU on 7th January, 2014. On behalf of Nepal and UK, Foreign secretary Mr. Arjun Bahadur Thapa and UK's Permanent Under Secretary Sir Simon Frazer signed the MoU for establishing the Consultation Mechanism at the Foreign and Commonwealth Office, London respectively. As per the MoU, both the parties will hold consultations at jointly decided intervals alternately in the capital of either country at an appropriate level as may be decided upon and hold discussion on all aspects of bilateral relations as well as on international or regional issues of mutual interest.

Finalized Agreements/MoU

- TIFA Agreement signed in 2011.
- An agreement on promotion and protection of investment between Nepal and UK signed on March 2, 1993
- Development Partnership Agreement between Nepal and UK, signed on December 2013. It supersedes the Technical cooperation agreement desiring to strengthen the traditional cooperation and cordial relation between Nepal and the UK signed on 31 May 1994.
- Trade Agreement signed in 1965.

Agreements/MoU in Progress

- Bilateral Agreement on Avoidance of Double Taxation

\textbf{Economic and Technical Cooperation (Development Cooperation)}

The UK aid to Nepal in various fields of activities started in 1961. The United Kingdom has been offering fellowships to the Government of Nepal since 1950s. British volunteers are engaged in Nepal since 1964. These programmes have contributed to Nepal's need for specialised and trained manpower and also have developed important links between the people of the two countries. In order to better understand and address the issues of poverty in Nepal, in April 1999 Department for International Development (DFID) established an in-country office staffed by a multi-disciplinary team of both UK nationals and staff appointed in country. DFID presence in Nepal has greatly assisted in working with Government of Nepal in the development of understanding and establishment of networks that will promote opportunities for change.

Recently Development Partnership Arrangement to provide a transparent and mutual accountability framework between Nepal and the United Kingdom on development assistance was signed on December 2013. The assistance of British Government generally comes through the Umbrella Agreement. The first such agreement of Pound Sterling 12 million was signed on 23 September 1979 for the implementation of various projects. The UK Government’s Department for International Development (DFID) prepared an Operational Plan for Nepal during 2011-2016. This plan commits up to Pound Sterling 413 million of UK official development assistance during the period 2011-2016. All bilateral aid with Nepal is on a grant basis.

As per Development Cooperation Report 2014-2015 by Ministry of Finance, UK remained the top ODA provider (based on disbursement) with a total assistance of US dollars 168.07 million in the Fiscal Year 2014/2015.

DFID Technical Support has been instrumental in promoting foreign direct investment especially in large hydropower project through Investment Board Nepal for the last few years. This very programme has provisioned of supporting IBN to promote private investment in the country. Likewise there are provisions of continuing support to the second and third phases of Financial Sector Reform Programme of the Government initiated few years back. The program will last for six years from 2015 to 2020.

The DFID Nepal's operational Plan is divided into four main areas: governance and security, inclusive wealth creation, human development (basic services including education and health), and climate change/disaster management. The UK has assisted Nepal in the areas of livelihoods, e.g. agriculture, forestry, transport and communications, local development; basic services, e.g. education, health, water supply and sanitation; good governance, human rights and peace building efforts.

\textbf{Earthquake, 2015}

Nepal received generous support and assistance from the Government of the United Kingdom in the aftermath of the earthquake of 25 April 2015. It responded to the Nepal earthquakes immediately with the deployment of Eight Disaster Response Specialists under Rapid Response Facility and with the release of GBP 5 million. The United Kingdom Government pledged USD 110 million for the reconstruction and rebuilding of Nepal. 

\textbf{Trade}

Nepal and UK signed trade agreement in 1965. Despite our extensive engagements and linkages, both at the level of government and, people in the backdrop of our long-standing friendly and cooperative relations, trade and investment relations between the two countries have largely remained way below its actual potential.

With high imbalance and elements of unpredictability, this is, of course, a typical feature of a trade relation between a developed and least developed country. Nepal faced a trade deficit of 142,182,856 Rupees in the first eight month of 2016. The total export to UK stands at 1,256,018,669 Rupees while the total import stands at 1,398,201,525. It is for this reason that Nepal places high importance to directing foreign development cooperation in areas which help enhancing our productive capacity. Aid for trade is, therefore, another preferred area for us in our development cooperation. 

The major items of import from UK are: Motor car, vehicle, parts of aeroplane and helicopter, Whiskies, Malt not roasted, Sweets biscuits, Chocolate in blocks, slab or bar etc. Major Nepalese exports to UK are Pashmina shawls, goatskin, leather goods, Nepalese paper and paper products, woollen carpets, handicrafts, ready-made garments, silverware and jewellery. Likewise, major imports from UK are copper scrap, hard drinks, cosmetics, medicine and medical equipment, textiles, copper wire rod, machinery and parts, aircraft and spare parts, scientific research equipment, office equipment and stationery.

Exchange of visits by trade delegations from Nepal and Britain has added a new dimension to the commercial relations between Nepal and Britain. Nepal-Britain Chamber of Commerce and Industry is active in promoting trade and investment between Nepal and UK.

\textbf{Tourism}

A sizeable number of British tourists come to Nepal every year for trekking and mountaineering and other leisurely activities. Given our historical linkages and increasing people-to-people contacts, the prospects for increasing the tourist arrival from UK in Nepal are quite promising.

UK's support and cooperation in line with our broader policy priorities will be much appreciated, especially in construction and upgradation of tourism infrastructure with focus on tourist safety. DIFID’s recent involvement and interest in tourist security, trekkers tracking, and maintenance of damaged trekking trails, including the Great Himalayan Trail, is most welcome.

Embassy of Nepal in London is planning to organize the many tourism promotional programme to increase the number of tourists from UK.

\textbf{Consular activities}

Embassy of Nepal in London involves in various consular service ranging from passports, visas, Travel Document, NRN Card, Verification, Attestation and Power of Attorney. During Fiscal Year 2075/76, Embassy of Nepal in London generated GBP 542048.72 (NRS 7,73,71,510.41) revenue.

\textbf{Investment}

Foreign investment commitment from UK stands at 1663 million rupees till 2013/14. The major investment is in the areas of banking, tourism, education, technology. An agreement for the promotion and protection of investment between Nepal and UK was signed on March 2, 1993.

There are some British joint ventures in the areas of hotel, travel and trekking, tea production, education, garment, bio-technology and consultancy. These are significant figures, but do not reflect the true potential. There are many British and Non Resident Nepalese (NRN) entrepreneurs who are still making trade and investment successes in Nepal. Standard Chartered Bank and Unilever are two major British companies who have made a huge return from their investment in Nepal in the last 20 years.

An agreement on promotion and protection of investment between Nepal and UK signed on 02 March 1993 provides a framework to further expand cooperation in this field. In this context, the proposal for signing another agreement on avoidance of double taxation will further help boost the flow of FDI between the two countries.

\textbf{Foreign employment and British Gurkha}

Thousands of Nepalese are working at service sectors like hospitals, university, hotels and restaurants in UK. About 200 Nepalese are recruited as Maritime Security Guards in UK. About 150,000 Nepalese are living in UK. Many Nepalese belong to Ex-Gurkha Servicemen and their families.

British Gurkhas is a fully integrated part of the British Armed Forces. It constitutes an important element in Nepal-Britain relations.  Over 160,000 Gurkhas were enlisted in the Gurkha Brigade and other units of the Indian Army during the First and Second World Wars. In recognition of their distinguished service, the British Gorkhas servicemen from Nepal have won 13 Victoria Crosses (VC), the highest British gallantry honour.

\textbf{Cultural Cooperation}

British Council in Nepal is working to extend cultural relations between UK and Nepal. Similarly, Nepalese diaspora and Gurkha soldiers are visible bond who have interlinked the Nepalese culture and traditions in UK.

\textbf{Education cooperation}

UK is supporting US dollars 260,012 for the education of marginalised girl in Kailali district of Nepal. DFID was the core education funding agency in Nepal, supporting the foundations of education values. Active as a School Sector Reform Plan (SSRP) pooling Development Partner. With Education for All overall goals, the SSRP objectives were to 
\begin{enumerate}
\item ensure access and equity in primary education; 
\item improve the efficiency and institutional capacity of primary education; and 
\item enhance the quality and relevance of basic primary education for children and illiterate adults.
\end{enumerate}

In 2013, DFID committed around GBP 2 million to establish 810 additional girls' toilet and water supplies/WASH facilities across 18 districts selected based on low indicators in hygiene and sanitation with an implementation date which was extended to July 2015.

The British Government has been regularly providing scholarships in different areas for the development of human resource in Nepal since 1950s. Britain is offering Chevening Award to Nepalese from many years. A lot of Nepalese students are pursuing higher level studies in the UK. 

\textbf{Security cooperation}

UK has provided support for upgrading of Nepal Army Birendra Peace Operations Training Centre (BPOTC) located at Panchkhal (45 km East of Kathmandu). It has also provided Explosive Ordinance Device (EOD) related Improvised Explosive Device Disposal (IEDD) related Special Training to Nepal Army. UK is continually providing the special training courses to Nepal Army officials.

High level visit from Nepal Army and British Army are regularly taking place in UK and Nepal respectively.

\textbf{Nepalese students in UK}

\end{solution}

2. Discuss about the bilateral US relations with Nepal

**Solution:**

The United States recognized the Kingdom of Nepal on April 27, 1947, when Joseph C. Satterthwaite presented a letter from President Harry S. Truman to then king Tribhubana of Nepal. Satterthwaite was on a special diplomatic mission to Nepal as personal representative of the President. The two countries established diplomatic relations in 1948. Bilateral relations are friendly, and U.S. policy objectives toward Nepal center on helping it build a peaceful, prosperous, resilient and democratic society. Primary U.S. objectives in Nepal include supporting a stable, democratic Nepal that respects the rule of law; promoting investor-friendly economic development; and improving disaster risk management systems.

The United States enjoys a strong and positive relationship with Nepal. Years of diplomatic, development, and military engagement have advanced U.S. interests in transitioning Nepal into a more peaceful, stable democracy with significant economic potential. Since the end of its 10-year civil war in 2006 and the devastating earthquakes of 2015, Nepal has successfully transitioned into a full-fledged constitutional federal republic grounded in a constitution promulgated in 2015. With the recent formation of a new government, Nepal may now be on the cusp of a period of much-needed political stability.

Nepal has sought a bilateral consultation mechanism with the United States and has signed similar agreements with other countries like Australia in summer 2017. Such a forum might include as topics: Millenium Challenge Cooperation (MCC) coordination and implementation; trade (TPS, technical assistance, etc.); security and defense cooperation; and humanitarian assistance and disaster response.

To improve Nepal's economic situation, the MCC signed, in 2017, a \$500 million Compact with Nepal to expand Nepal’s electricity transmission infrastructure and improve its road maintenance regime. The Nepali government has committed another \$130 million for a program total of \$630 million. The Compact will build 300 kilometers (km) of high-voltage electric transmission lines, three substations, perform enhanced road maintenance on 305 km of strategic highways, and provide technical assistance to the national electric utility, the new electricity regulator, and the Department of Roads. The Compact is entered into force after the end of FY 2019.

U.S. assistance has been critical to helping Nepal rebuild after the devastating 2015 earthquake and remains committed to building Nepal's resilience in the event of any future disaster. The United States has provided over \$190 million for earthquake relief, recovery, and reconstruction. While these commitments have exceeded our initial pledge of \$130 million made at the International Conference on Nepal's Reconstruction in June 2015, significant recovery needs remain. To date, the United States has built 36 schools and hospitals; has directly helped rebuild over 16,000 homes; trained 260,000 people in safer construction; and developed policies, systems, and controls to ensure that $8.6 billion in reconstruction results in safer structures for all. In addition to rebuilding a safer Nepal, we are working to help Nepal institutionalize all lessons learned from the 2015 earthquake. We are also helping Nepal to implement its new disaster management law and stand up a new National Disaster Management Authority. We are further supporting Nepal as it introduces federalism by working with newly elected local governments to implement their own disaster management plans—thus helping local authorities meet commitments made to their constituencies. These efforts will help Nepal on its journey to self-reliance.

The United States has also committed security assistance to Nepal, working with the Nepali Army to strengthen their peacekeeping and disaster response capabilities.

The United States and Nepal have signed a trade and investment framework agreement, providing a forum for bilateral talks to enhance trade and investment, discuss specific trade issues, and promote more comprehensive trade agreements between the two countries. In 2016, Nepal became one of few countries in the world with a single-country trade preference program with the United States. Principal U.S. exports to Nepal include agricultural products, aircraft parts, optic and medical instruments and machinery. U.S. imports from Nepal include carpets, apparel and jewelry.

### Terrorism

Terrorism in its broadest sense, describes the use of intentionally indiscriminate violence as a means to create terror, or fear, to achieve political, religious or ideological aim. It is used in this regard primarily to refer to violence against peacetime targets or in war against non-combatants.

Terrorism has been practiced by political organizations with both rightist and leftist objectives, by nationalistic and religious groups, by revolutionarie, and even by state institutions such as armies, intelligence services, and police.

Terrorism is not legally defined in all jurisdictions; the statutes that do exist, however, generally share some common elements. Terrorism involves the use of threat of violence and seeks to create fear, not just within the direct victims but among a wide audience. The degree to which it relies on fear distinguishes terrorism from both conventional and guerilla warfare. Although conventional militiary foreces invariably engage in psychological warfare against the enemy, their principal means of victory is strength of arms. Similarly, guerrilla forces, which often rely on acts of terror and other forms of propaganda, aim at military victory and occassionally succeed (e.g. the Viet Cong in Vietnam and the Khmer Rouge in Cambodia). Terrorism proper is thus the systematic use of violence to generate fear, and thereby to achieve political goals, when direct military victory is not possible. This has led to some social scientists to refer to guerrilla warfare as the "weapon of the weak" and terrorism as the "weapon of the weakest".

Terrorism has been described variously as both a tactic and strategy; a crime and a holy duty; a justified reaction to oppression and an inexcusable abomination. Obviously, a lot depends on whose point of view is being represented. Terrorism has often been an effective tactic for the weaker side in a conflict. As an asymmetric form of conflict, it confers coercive power with many of the advantages of military force at a fraction of the cost. Due to secretive nature and small size of terrorist organizations, they often offer opponents no clear organization to defend against or to deter.

This is why pre-emption is being considered to be so important. In some cases, terrorism has been a means to carry out a conflict without the adversary realizing the nature of the threat, mistaking terrorism for criminal activity. Because of these characteristics, terrorism has become increasingly common among those pursuing extreme goals throughout the world. But despite its popularity, terrorism can be a nebulous concept.

The US Department of Defense defines terrorism as "the calculated use of unlawful violence or threat of unlawful violence to inculcate fear; intended to coerce or to intimidate governments or societies in pursuit of goals that are generally political, religious, or ideological."

The UN produced the following definition of terrorism in 1992; "An anxiety inspiring method of repeated violent action, employed by semi-clandestine individual, group or state actors, for idiosyncratic, criminal or political reasons, whereby -- in contrast to assassination -- the direct targets of violence are not the main targets."

The strategy of terrorists is to commit acts of violence that draws the attention of the local populace, the government, and the world to their cause. The terrorists plan their attack to obtain the greatest publicity, choosing targets that symbolize what they oppose.

The effectiveness of the terrorist act lies not in the act itself, but in the public's or governments reaction to the act. For example, in 1972 at the Munich Olympics, the Black September organization killed 11 Israelis. The Israelis were the immediate victims but the true target was the estimated 1 billion people watching the televised event. Those billion people watching were to be introduced to fear -- which is terrorism's ultimate goal. The introduction of this fear can be from the threat of physical harm/a grizzly death, financial terrorism from the fear of losing money or negative effects on the economy, cyber terrorism harming the critical technological infrastructures of society and psychological terrorism designed to influence people's behavior.

There are three perspectives of terrorism: the terrorist's, the victim's, and the general public's. The phrase "one man's terrorist is another man's freedom fighter" is a view terrorists themselves would gladly accept. Terrorists do not see themseleves as evil. They believe they are legitimate combatants, fighting for what they believe in, by whatever means possible to attain their goals. A victim of a terrorist act sees the terrorist as a criminal with no regard for human life. The general public's view though can be the most unstable. the terrorists tke great pains to foster a Robin Hood image in hope of swaying the general public's point of view towards their cause. This sympathetic view of terrorism has become an integral part of their psychological warfare and has been countered vigourously by governments, the media and other organizations.

Technolgical advances, such as automatic weapons and compact electrically detonated explosives, gave terrorists a new mobility and lethality, and the growth of air travel provided new methods and opportunities. Terrorism was virtually an official policy in totalitarian states such as those of Nazi Germany under Adolf Hitler and the Soviet Union under Stalin. In these states arrest, imprisonment, tourture, and execution were carried out without legal guidance or restraints to create a climate of fear and to encourage adherece to the national ideology and the declared economic, social, and political goals of the state.

One of the deadliest terrorist strikes to date were the September 11 attacks of 2001, in which suicide terrorists associated with al-Qaeda hijacked four commercial airplanes, crashing two of them into the twin towers of the World Trade Center complex in the New York city and the third into the Pentagon building near Washington D.C.; the fourth plane crashed near Pittsburgh, Pennsylvania. The crashes destroyed much of the World Trade Center complex and a large portion of one side of the Pentagon and killed more than 3000 people.

Terrorism appears to be an enduring feature of political life. Even prior to the September 11 attacks, there was widespread concern that terrorist might escalate their destructive power to vastly greater proportions by using weapons of mass destruction -- including nuclear, biological, or chemical weapons -- as was done by the Japanese doomsday cult AUM Shirnrikyo, which released nerve gas into a Tokyo subway in 1995.

Factors conducive to terrorism

1. Poverty
2. Globalization
3. Legitimate grievances and failure of governments.
4. Humiliation
5. Lack of democracy, and widespread and systematic violation of human rights
6. Lopsided foreign policy
7. Failed state governance and authority

Goals, strategies, adn weapons of terrorism

1. Social and political justice
2. Self determination
3. Racial superiority
4. Foreign policy
5. Publicty
6. Demoralized governments

Costs associated with terrorism are so widespread, complex, and intangible that they are virtually impossible to measure. Individuals, families, governments, companies and non-state actors bear the time, money and resource costs of terrorism to varying degrees. Migration, trade, travel and interpersonal relations are affected. It is generally believed that the financial crisis and the global recesssion were caused in by policies adopted by the Bush administration to fight global terrorism, including wars in Afganistan and Iraq.

Kinds of terrorism

Although the types of terrorism tend to overlap, they vary in their implications and affect us in different ways. For example, the indiscriminate nature of global terrorism contrasts sharply with domestic terrorism aimed at specific groups or governments.

1. Domestic terrorism occurs within the borders of a particular country and is associated with extremist groups.
2. Nationalist terrorism is closely associated with struggles for political autonomy and independence.
3. Religious terrorism grows out of extreme fundamentalist religous groups that believe that God is on their side and that their violence is divinely justified and inspired.
4. State terrorism is a cold, calculated, efficient and extremely destructive form of terrorism, partly because of the overwhelming power at the disposal of governments.

Leading terrorist organizations

- ISIS (part of northern Iraq and parts of Western Syria)
- Al-Qaeda (Afganistan)
- Taliban
- Boko Haram (now sworn to ISIS; Nigeria)
- Lashkar-e-toa (Pakstan)
- Hezbollah (Lebanon)
- Al-Shabaab
- Hamas (Palestine)
- Naxal/Naxalites (India)
- Irish Republican Army

No cause justified terrorism. The world must repond and fight vigillantly with this evil that is intent on threatening and destroying our basic feedoms and way of life. The complexity of terrorists requires employing a wide variety of instruments to combat it. It addition to military, traditional law enforcement, intelligent responses, and global cooperation has become obvious to counter terrorist attacks.

The most prevalent response to terrorism is the use of force, both domestically and internationally. Besides, reduction in the production of weapons of mass destruction and control over media and technology can be effective.

We must retaliate forcefully and successfully in order to reassure the world of our confidence as a great power, and our ability to retain that status. Lastly, and practically, we must explore the possibilities of terrorism that exist and attempt to grasp the actual threat that these possibilities realistically pose for us.

### Globalization

Globalisation is the process of interaction and integration among people, companies, and governments worldwide. As a complex and multifaceted phenomenon, globalization is considered by some as a form of capitalist expansion which entails the integration of local and national economies into a global, unregulated market economy. Globalization has grown due to advances in transportation and communication technology. With the increased global interactions comes the growth of international trade, ideas, and culture. Globalization is primarily an economic process of interaction and integration that's associated with social and cultural aspects. However, conflicts and diplomacy are also large parts of the history of globalization, and modern globalization.

Economically, globalization involves goods, services, the economic resources of capital, technology, and data. Also, the expansions of global markets liberalize the economic activities of the exchange of goods and funds. Removal of cross-border trade barriers has made formation of global markets more feasible.[citation needed] The steam locomotive, steamship, jet engine, and container ships are some of the advances in the means of transport while the rise of the telegraph and its modern offspring, the Internet and mobile phones show development in telecommunications infrastructure. All of these improvements have been major factors in globalization and have generated further interdependence of economic and cultural activities around the globe.

Though many scholars place the origins of globalization in modern times, others trace its history long before the European Age of Discovery and voyages to the New World, some even to the third millennium BC. Large-scale globalization began in the 1820s. In the late 19th century and early 20th century, the connectivity of the world's economies and cultures grew very quickly. The term globalization is recent, only establishing its current meaning in the 1970s.

Three major dimensions of globalization can be differentiated. They are:

Economic globalization

It is the increasing economic interdependence of national economies across the world through a rapid increase in cross-border movement of goods, services, technology, and capital. Whereas the globalization of business is centered around the diminution of international trade regulations as well as tariffs, taxes, and other impediments that suppresses global trade, economic globalization is the process of increasing economic integration between countries, leading to the emergence of a global marketplace or a single world market. Depending on the paradigm, economic globalization can be viewed as either a positive or a negative phenomenon. Economic globalization broadly comprises: globalization of production and market but also includes competition, technology, and corporations and industries.

Cultural globalization

Cultural globalization refers to the transmission of ideas, meanings, and values around the world in such a way as to extend and intensify social relations. This process is marked by the common consumption of cultures that have been diffused by the Internet, popular culture media, and international travel. This has added to processes of commodity exchange and colonization which have a longer history of carrying cultural meaning around the globe. The circulation of cultures enables individuals to partake in extended social relations that cross national and regional borders. The creation and expansion of such social relations is not merely observed on a material level. Cultural globalization involves the formation of shared norms and knowledge with which people associate their individual and collective cultural identities. It brings increasing interconnectedness among different populations and cultures. Cross-cultural communication, cultural diffusion and religious thought-schools are the major aspects of cultural globalization. Sports too bear the spirit of globalization; for eg., the FIFA World Cup is the most widely viewed and followed sporting event in the world, exceeding even the Olympic Games; a ninth of the entire population of the planet watched the 2006 FIFA World Cup Final.

Political globalization

Political globalization refers to the growth of the worldwide political system, both in size and complexity. That system includes national governments, their governmental and intergovernmental organizations as well as government-independent elements of global civil society such as international non-governmental organizations and social movement organizations. One of the key aspects of the political globalization is the declining importance of the nation-state and the rise of other actors on the political scene. Adherence to or practice of intergovernmentalism, multi-level governance and multiple citizenship reflect today's globalized politics, although it should also be noted that some countries, like North Korea, have embraced isolationist policies.

Aside from the the above mentioned aspects, globalization touches upon a wide range of issues including population migration, information exchange, environmental protection.

Although globalization, according to many political scientists, is not a new phenomenon and that countries pursued it in various ways since the birth of the nation state, nobody denies the fact that the current phase of globalization is different-- different in the sense that it unleashed three major trends. The first is denationalization of the state involving major changes in the power of the legislature, the executive and the judiciary and shifts in the relative weight of financial, technological, environmental, security and other organs. The second is the de-statization of politics making the state's involvement in society less hierarchical, decentralized, poly-centric and multi-tiered involving both territorial and functional units. And, finally, the internationalization of the policy regime increasing the strategic significance of the international context of domestic state action and blurring the distinction between domestic and foreign policy regimes. The main issue of "governance in a global economy is the loss of monetary and fiscal options for the nation state and subservience to rules sometimes made by the international trade and financial interests". Argentina presents an extreme case of the loss of monetary sovereignty. To participate in the global economy, it surrendered its economic policy prerogative to the US. The communications revolution has truly made it possible for different global power centers to execute their agendas almost immediately. If this has opened new unforeseen opportunities for global peace and prosperity, at the same time, risks have also multiplied by as many times.
