## Press release publications

### The Right Honourable President Participates in 'Women in Power'

Mardi, 12 Mars 2019
Presenter: Lok B. Chhetri
Lieu: New York

The Right Honourable President Mrs. Bidya Devi Bhandari participated this morning in the High-Level event on 'Women in Power' organized by the President of General Assembly (PGA) during the 63rd session of the Commission of the Status of Women (CSW-63). Speaking in the first among three high-level round tables entitled 'How Women Leaders Change the World', the Rt. Hon. President shared with the General Assembly Nepal's initiatives, achievements and lessons learned in the field of gender equality. 

The President highlighted that the constitutional and legal arrangements have increased participation of women in leadership positions in Nepal. She also shared the inspiring experience of her journey from a grass-root woman activist in a remote village to the first President of Nepal after the promulgation of the new Constitution.

In the global context, the President stressed that 'discrimination against women is a social construct, not a natural condition'. She underscored the need to guarantee women's rights in constitutions and laws, adding that participation on governance structures is essential to bring impact on socio-economic sectors.

Other speakers sharing their perspectives at the roundtable together with the Rt. Hon. President were the Presidents of Lithuania and Trinidad and Tobago; Vice-President of Colombia; and High Representative of the Union for Foreign Affairs and Security Policy of the European Union. 

Also in the morning, the President held a meeting with H.E. António Guterres, the Secretary-General of the United Nations at his office. During the meeting, the two sides exchanged views on various issues, including multilateralism, Climate Change, SDGs, peacekeeping, and post-earthquake reconstruction. The President appreciated the Secretary-General for his reform agenda across all three pillars of UN in general and for maintaining gender parity in all UN bodies, in particular. The Secretary-General recalled his first visit to Nepal in 1978, and appreciated Nepal for playing an active role at the UN, including through contributions in peacekeeping. 

In the afternoon, the President met with H.E. María Fernanda Espinosa Garcés, the PGA, and appreciated her for taking leadership on important issues, including through organizing the event, 'Women in Power'. The PGA thanked the President for her presence and for sharing enlightening experience.

Later in the afternoon, the President held separate bilateral meetings with the President of Estonia H.E. Kersti Kaljulaid and the President of Croatia H.E. Kolinda Grabar-Kitarović. During the meeting with the Estonian counterpart, the two sides discussed pressing global issues such as Climate Change, sustainable development, multilateralism, among others. Similarly, during her meeting with the President of Croatia, matters of mutual interests, including women in political leadership, were discussed. In both the meetings, the leaders expressed satisfaction over the warm bilateral relations while exchanging views on ways to enhance them.

The Rt. Hon. President also met with H.E. Mary Robinson, the president of The Elders and the former President of Ireland. During the meeting, the two leaders shared their views on climate justice, women empowerment and leadership, among others. 

The Rt. Hon. President attended a dinner hosted in her honour by Ambassador Amrit Bahadur Rai, Permanent Representative of Nepal to the United Nations at his official residence. Earlier today, the Rt. Hon. President attended a high-level luncheon with 'Young Women Leaders' jointly hosted by the PGA and the Permanent Mission of Qatar to the United Nations. 

### State visit of the President of People's Republic of China to Nepal

At the friendly invitation of President of Nepal, Right Honourable Mrs. Bidya Devi Bhandari, the President of the People's Republic of China His Excellency Mr. Xi Jinping is paying a state visit to Nepal on 12 and 13 October 2019.

During the visit, President H.E. Mr. Xi Jinping will meet with President Rt.Hon. Mrs. Bidya Devi Bhandari. The Right Honourable President of Nepal will host a Banquet in honour of President H.E. Xi Jinping and the Chinese delegation.

President H.E. Mr. Xi Jinping will hold delegation level official talks with Right Honourable Prime Minister Mr. K P Sharma Oli. Following the talks, both leaders will witness the signing of bilateral agreements and memoranda of understanding.

Senior leaders of Nepal will call on President H.E. Xi Jinping during his sojourn in Kathmandu.

Ministry of Foreign Affairs
Singhadurbar
Kathmandu, Nepal
09 October 2019

### Rt. Hon. President's visit to Japan

The Rt. Hon. President had a meeting with the President of India H.E. Shri Ram Nath Kovind in a warm and cordial environment in Tokyo this morning. The two Presidents expressed satisfaction over the excellent state of age-old, multifaceted bilateral relations.

The two Presidents appreciated the timely completion of the cross-border petroleum pipeline and expressed hope that other projects would also be implemented in an expeditious manner.

The Presidents underlined the importance of high-level exchanges on a regular basis in order to further advance bilateral relations. In this context, Rt. Hon. President Mrs. Bidya Devi Bhandari renewed her invitation to the President of India H.E. Shri Ram Nath Kovind to visit Nepal. Expressing his sincere thanks for the invitation, President H.E. Kovind expressed his willingness to visit Nepal and said that he would pay the visit at a convenient time to both sides.

Minister for Home Affairs Hon. Mr. Ram Bahadur Thapa 'Badal', Foreign Secretary Mr. Shanker Das Bairagi, Ambassador of Nepal to Japan H.E. Mrs. Prativa Rana, Secretary at the Office of the President Dr. Hari Paudel, Principal Private Secretary to the Rt. Hon. President Dr. Bhesh Raj Adhikari and other high-ranking officials of the Government of Nepal participated in the meeting. From Indian side, H.E. Shri Sanjay Kothari, Secretary to the President, H.E. Shri Vijay Gokhale, Foreign Secretary, H.E. Shri Sanjay Kumar Verma, Ambassador of India to Japan and other high ranking officials of the Government of India were present during the meeting.

Embassy of Nepal
Tokyo
22 October 2019

### Address by Rt. Hon. PM at the SDG Moment

Date: (Vendredi) 18 Septembre 2020

Press Release

Prime Minister Rt. Hon. Mr. K P Sharma Oli addressed this morning the SDG Moment 2020, a high-level event convened by UN Secretary-General on the margins of the 75th session of the UN General Assembly.

In his address, the Prime Minister expressed concerns that the pandemic threatened the hard-earned development gains particularly in the countries such as LDCs, LLDCs and SIDs. The freezing economy, shrinking revenue, increasing public expenditure, rising poverty and unemployment have severe impact on these countries' efforts to realize the SDGs, he added.

He stated that it was not a moment to shift the goalposts further and that the SDGs must continue to serve as the compass of clarity for global action.

The Prime Minister further said that the sustainable development was at the center of Nepal's development vision and it underpinned the national aspiration of 'Prosperous Nepal, Happy Nepali'. He also touched upon Nepal's achievements in key areas including poverty reduction, food security, education, gender equality, basic sanitation, and energy access. 

He underlined the need to move beyond rhetoric and accelerate action at all levels in order to recover and rebuild better, and to ensure that no one is left behind.

Nepal was one of the five countries from the Asia Pacific region to be featured in the SDG Moment 2020. There were 22 Heads of State/Government from around the world representing different regional groups, a number of SDG advocates and partners, and senior UN officials, among others.

Permanent Mission of Nepal to the United Nations 

New York

18 September 2020

### 75th session of the United Nations General Assembly (UNGA)

Prime Minister Rt. Hon. Mr. K P Sharma Oli is leading Nepali delegation to the 75th session of the United Nations General Assembly (UNGA) being held in New York.

The Prime Minister is scheduled to address the General Debate of the UNGA virtually on 25 September 2020.

The theme of the general debate of the UNGA this year has been set as "The Future We Want, the United Nations We Need: Reaffirming Our Collective Commitment to Multilateralism – Confronting COVID-19 through Effective Multilateral Action".

High-level week of the UNGA is beginning from 17 September 2020.

The Prime Minister will also address the high-level meeting to commemorate the 75th anniversary of the United Nations on 21 September 2020. He will also address the 2020 SDG Moment being held on 18 September 2020; and the Biodiversity Summit on 30 September 2020.

Similarly, Minister for Foreign Affairs, Hon. Mr. Pradeep Kumar Gyawali will address virtually the high-level meeting to commemorate and promote the International Day for the Total Elimination of Nuclear Weapons on 2 October 2020. He will also address the Ministerial Meetings of LDCs and LLDCs, among others.

On 24 September, Nepal will host the virtual meeting of the SAARC Council of Ministers traditionally held coinciding with the UNGA.

Other members of the delegation include Minister for Foreign Affairs Hon. Pradeep Kumar Gyawali and senior officials of the Government of Nepal from Kathmandu. Ambassador of Nepal to the United States of America H.E. Mr. Arjun Kumar Karki, Permanent Representative of Nepal to the United Nations in New York H.E. Mr. Amrit Bahadur Rai and other officials at the Permanent Mission of Nepal will participate at the UNGA virtually/physically as appropriate.

Ministry of Foreign Affairs
Singh Durbar
Kathmandu

17 September 2020

### President of the Republic of Serbia Aleksandar Vučić conveyed today a Letter of Congratulations to the President of the United States of America Donald Trump for the Independence Day

Your Excellency, Dear President,
 
Please accept my sincere congratulations for the Independence Day - national holiday of the United States of America, as well as my best wishes for further progress of your country and wellbeing of all its citizens. 
 
Every fourth of July citizens of the USA celebrate universal values, written in the Declaration of Independence, adopted 243 years ago. Those are, like you said, key values that make the American nation and whose strength inspires and gives hope, but they are likewise important for all those striving to liberty, equality and prosperity. 
 
In previous period we celebrated important anniversaries from our common history, remembering bright examples of our alliance in great historical moments. At the end of the World War I, the American President Woodrow Wilson said that "the principles Serbia had heroically fought for and due to which it had suffered in that war are identical to those the USA advocate."
 
I am convinced that now we also have the opportunity to bring back the relations of our countries, through the development of political dialogue and strengthening of economic and every other cooperation, to the level of true partnership, the way they used to be and the way they should be. I hope that a desire for richer and better Serbian-American bonds is mutual and that we will remind ourselves more in the future of what connects us. 
 
I avail myself of this opportunity to thank you for the support that the United States of America provide us on our European path, and particularly for supporting the efforts Serbia has been making in promoting the politics of peace and cooperation in the Western Balkans, as well as in finding compromise solution within the dialogue with Priština. 
 
With a hope that you will visit us soon, please accept Your Excellency my cordial regards and the assurances of my highest consideration", states the congratulations letter of President Vučić.
 
Belgrade,
4 July 2019

### Working Visit of the President of Benin, His Excellency Dr. Boni Yayi to the Internatioal Court of Justice.

The HAGUE, 
21 January, 2009

His Excellency Dr. Boni Yayi, President of the Republic of Benin, paid a working visit today to the seat of the International Court of Justice, the principal judicial organ of the United Nations, at the Peace Palace in The Hague.

President Boni Yayi was greeted upon his arrival by the President of the Court, Judge Rosalyn Higgins, and by the Registrar, Mr Philippe Couvreur. President Higgins introduced him to Judges Raymond Ranjeva, Ronny Abraham and Mohamed Bennouna, who sat in the Chamber which dealt with the case concerning the Frontier Dispute (Benin/Niger). The Registrar then introduced him to senior officials of the Registry and to two Beninese nationals working for the Court.

His Excellency Dr. Boni Yayi then participated in a meeting with the Members of the Court present on the activities of the ICJ. At the end of this meeting, the President of Benin signed the visitors' book and exchanged gifts with President Higgins, before finishing his visit in the Great Hall of Justice.

The President of Benin was accompanied by a delegation consisting of several Beninese Government Ministers, a number of counsellors, the Ambassador of Benin to the Netherlands, the Ambassador of the Netherlads to Benin, and other Beninese diplomats.

Information Department

### President Golitsyn paying courtesy call on secretary-general Ban Ki-Moon

International Tribunal for the Law of the Sea (ITLOS)
18 December, 2014

Judge Vladimir Golitsyn, President of the Tribunal, paid a courtesy call on the Secretary-General of the United Nations, Mr Ban Ki-Moon, at his office in New York on 17 December, 2014. He was accompanied by the Registrar of the Tribunal, Mr Philippe Gautier.

President Golitsyn briefed the Secretary-General on the Judicial work of the Tribunal and highlighted the special role played by the Tribunal in the dispute settelement system establihsed under the United Nations Convention on the Law of the Sea. He also underlined the importance of providing states with information on the mechanisms for the settlement of disputes under the convention and referred in this respect to the regional workshops organized by the Tribunal.

The President extended an invitation to the Secretary-General to visit the Tribunal at a time convenient for him.

### UN Security Council mission visit to Burundi

11 March 2015

A United Nations Security Council mission is expected to visit Burundi on 13 March 2015 to hold discussions with the country’s Head of State and key stakeholders on peace and stability issues, including the ongoing electoral process. The visit to Burundi is part of a regional trip by the UN Security Council which also includes stops in the Central African Republic (CAR) and in Addis Ababa, Ethiopia, to meet with the African Union.

Council members will meet with Burundian President Pierre Nkurunziza as well as with other members of the Government, officials of the National Electoral commission’s (CENI), representatives of political parties and politically affiliated youth groups as well as diplomats, representatives of the UN Electoral Observation Mission in Burundi (MENUB) and the UN country team. The delegation is also expected to speak to the press at the end of its one-day visit.

The visit to Burundi occurs as the country is preparing to hold five elections: legislatives and communal (26 May); presidential (first round on 23 June and possible run-off on 27 July); senatorial (17 July); and local elections (hills and districts councils - 24 August).

Following a request by the Government of Burundi to the Secretary-General, the United Nations established an electoral observation mission in Burundi headed by his Special Envoy to Burundi, M. Cassam Uteem, to follow and report on the electoral process the country. The United Nations Electoral Observation Mission in Burundi (MENUB) officially started its operations in the country on 1 January 2015, as stated in SC resolution 2137 (2014). France - who holds the rotating presidency of the Security Council for the month of March and the United States are co-leading the visit to Burundi.

### Credential Presentation

H.E. Prof Dr. Chop Lal Bhusal Ambassador of Nepal to the People's Republic of Bangladesh has presented his letter of credence to Honourable Abdul Hamid, President of the People's Republic of Bangladesh at a ceremony organized today at Bangabandhu Bhabhawan on Tuesday, 18 July 2017 today. Mrs. Puspha Bhusal, spouse of the Ambassador was accompanied during the occassion.

National Anthem of both the nations were played during the occassion. After presentation of the credentials, Ambassador Prof. Dr Bhusal had a courtesy meeting with Honourable President of Bangladesh at his office. During the meeting, matters related to bilateral relations including connectivity, trade and transit between the two countries were discussed. At the meeting Honourable President expressed his willingness to visit Nepal during his tenure.

Foreign Secretary, Military Secretary to the Preseident, Secretary to the President, Chief of Protocol, high dignitaries and officials from the President's Office and from the Ministry of Foreign Affairs including media persons were present during the occassion. Mr. Dhan Bahadur Oli, Deputy Chief of Mission and Minister Counsellor and Brig. Gen Sagar K.C., Military Attache of the Embassy were also present on the occasion.

18 July, 2017
Embassy of Nepal, Dhaka
