## United Nations

- World Population Day is observed on 11 July (since established by UNDP in 1989)
- Day of Five Billion was observed on 11 July, 1987.
- UN observes following International Years: https://www.un.org/en/sections/observances/international-years/
- A developing (of a low and middle income country; LMIC/LEDC) is a country with a less developed industrial base and low HDI relative to other countries.
- In the 2016 edition of its World Development Indicators, the World Bank made a decision to no longer distinguish between "developed" and "developing" countries in the presentation of its data, considering the two-category distinction outdated. Instead, the World Bank classifies countries into four groups, based on Gross National Income per capita, re-set each year on July 1. In 2016, the four categories in US dollars were:
  - Low income countries: $995 or less
  - Lower middle income countries: $996 to $3,895
  - Upper middle income countries: $3,895 to $12,055
  - High income countries: $12,056 and above
- Third world:
	Over the past few decades since the fall of the Soviet Union and the end of the Cold War, the term Third World has been used interchangeably with developing countries, but the concept has become outdated in recent years as it no longer represents the current political or economic state of the world. The three-world model arose during the Cold War to define countries aligned with NATO (the First World), the Communist Bloc (the Second World, although this term was less used), or neither (the Third World). Strictly speaking, "Third World" was a political, rather than an economic, grouping. 
- MoFA, Nepal has following Divisions/Sections (as of Sept, 2019):
  1. General Administration Division
  2. Regional Organization Division
  3. South Asia Division
  4. North East Asia
  5. South East Asia and the Pacific Division
  6. Europe America Division
  7. Central Asia, West Asia & Africa Division
  8. UN, Int'l Organizations & Int'l Law Division
  9. Protocol Division
  10. Policy Planning, Development Diplomacy and Overseas Nepali Affairs Division.
- UNDP defines HDI as a measure of country's development (http://hdr.undp.org/en/content/human-development-index-hdi). Technical notes for HDI calculation is available herewith (hdr2018_technical_notes.pdf). Human development index data is available at: (http://hdr.undp.org/en/data).
-  Greenwich is an area of South East London, England, located 8.9 km east-southeast of Charing Cross. Greenwich is notable for its maritime history and for giving its name to the Greenwich Meridian (0° longitude) and Greenwich Mean Time.
- Volcanoes: https://en.wikipedia.org/wiki/Volcano
- UN Secretariat cannot participate in ICJ.
- Nepal became member of Universal Postal Union in 2013 BS.
- UN flag came into use since 20 October, 1947. ?
- UN's Economic and Social Council (ECOSOC) has 5 regional offices. ?
- UN's budget allottment is done by General Assembly. ?
- UNESCO has contributed the most to Nepal's culture and art conservation. ?
- Nepal became member of UN Security council during 1969-70 and again during 1988-89. ?
- An extensive list of World Heritage can be found at: http://whc.unesco.org/en/list/
- The United Nations has an Office of the High Representative for the Least Developed Countries, Landlocked Developing Countries and Small Island Developing States (UN-OHRLLS)
- Current list of LLDCs: Africa: 16 (Botswana, Burkina Faso, Burundi, Central African Republic, Chad, Eswatini, Ethiopia, Lesotho, Malawi, Mali, Niger, Rwanda, South Sudan, Uganda, Zambia, Zimbabwe), Asia: 10 (Afghanistan, Bhutan, Kazakhstan, Laos, Mongolia, Nepal, Tajikistan, Uzbekistan), Europe: 4 (Armenia, Azerbaijan, Moldova, North Macedonia), Latin America: 2 (Bolivia, Paraguay)
- An extensive listing of Landlocked countries is available at: https://en.wikipedia.org/wiki/Landlocked_country
- Bangladesh acquired membership of UN in Jan 17, 1974
- ILO is the earliest specialized organization of the UN
- Poland is the 51st founder/original signatories of the UN declaration (October 15, 1945).
- English and French are the official languages of the UN
- The Treaty of Versailles established the UN.
- The Economic and Social Council (ECOSOC) assists the General Assembly in promoting international economic and social co-operation and development. ECOSOC has 54 members, which are elected by the General Assembly for a three-year term. The president is elected for a one-year term and chosen amongst the small or middle powers represented on ECOSOC. The council has one annual meeting in July, held in either New York or Geneva. Viewed as separate from the specialized bodies it co-ordinates, ECOSOC's functions include information gathering, advising member nations, and making recommendations.
- Refer to UN's page on Wikipedia for extensive listing of organizations and specialized agencies of UN: https://en.wikipedia.org/wiki/United_Nations
- Boutros Boutros-Ghali (6th UN General Secretary, 1 January 1992 – 31 December 1996) presented the "An Agenda for Peace" report in the UN in 1992.
- The Treaty of Versailles was signed in 28 June, 1919 and was effective since 10 January, 1920.
- Currently functionless organ of UN is the Trusteeship Council.
- For a detailed listing of UN organs: https://www.un.org/en/sections/about-un/main-organs/
- In order to establish UN, 8 meetings were held orignially ?
- Switzerland became member of the UN in 2002 AD
- In UN Security Council there are 5 nations from African-Asian region.
- United Nations Literacy Decade (UNLD) was launched under the slogan of "Literacy as Freedom" and is led by UNESCO. The program was launched at UN headquarters in 2003 and aims to increase literacy levels and to empower all people everywhere.
- Nepalese representative chosen in high level UN panel for monitoring of Sudan's referendum were Mr. Bhojraj Pokharel
- UN has set objective to reduce poverty by half by 2015 AD ?
- International Civil Aviation Organization was eastablished in 1944 in Montreal, Canada. It is specialized in codifying the principles and techniques of international air navigation and fostering the planning and development of international air transport to ensure safe and orderly growth.
- Universal Postal Union is a specialized agency of the UN that coordinates postal policies among member nations, in addition to the worldwide postal system. It was established by the Treaty of Bern of 1874. The World Post Day happens each year on October 9.
- Indonesia is the first nation to cancel UN membership
- According to International Telecommunication Union Nepal ranks ? In information technology development index.
- Word Bank was established in December 27, 1945.
- UN declaration of human rights is a historic document that was adopted by the UN General Assembly at its third session on 10 December 1948 as the Resolution 217 at the Palais de Chaillot in Paris, France. Declaration consists of 30 articles affirming an individual's rights. The Declaration was the first step in the process of formulating the International Bill of Human Rights, which was completed in 1966, and came into force in 1976, after a sufficient number of countries had ratified them.
- December 10 is commemorated as the Human Rights Day.
- Economic and social council of the UN prepared the Human Rights Declaration.
- COP 19 of UN (related to climate change) was conducted in Warsaw of Poland on Nov 11-22, 2013
- Nepal selected Mr. Durga Bhattarai as representative of COP21
- UN's constitutional paper has been amended 5 times.
- Human right's declation was approved as 217th decision of the UN.
- UN declared 2005-2014 as the international decade of water.
- Nepal first observed UN day on October 24, 1956.
- International Maritime Organization has its headquarters in London.
- First round of talks on establishment of WTO was carried out on 1948 at Geneva, Switzerland.
- During establishment of UN, Harry S Trumer was the president of the USA.
- UN declared Nelson Mandela day as July 18.
- UN population fund was founded on 1969.
- Prime minister B.P. Koirala first addressed the UN from the Nepal side.
- Asia and Pacific countries population convention organized by UNESCO every 10 years was last hosted in Bankok, Thailand on 2013 A.D.
- Indonesia is a nation to have dropped and readopted UN membership.
- Non alliance movement was first initiated in Belgrades in 1961 AD
- High commission for human rights was established in UN on 1981.
- UNICEF was established in 1946 AD.
- Women's Development Fund under UN was established in 1976 AD
- First international document expliciting equality of rights among men and women was "Human Rights Declaration"
- Nepal became member of ILO on 30th August, 1966 AD
- Nepal became member of WB/IBRD on 6th September, 1961 AD
- International Fund for Agriculture Development has its headquarters in Rome, Italy.
- IFAD was established on 1977 AD.
- ILO was established on 1919 AD.
- ILO has its headquarters at Geneva, Switzerland.
- FAO has its headquarters at Rome, Italy and was established on 1945 AD.
- In the request of former Maoists (Revolutionary) and government, UNMIN was established in 2063-10-9.
- WB first offered its technical support to Nepal on 1964 AD.
- WB first had its financial (loan) assistance to Nepal on 1968 AD
- WB first offered financial aid to Nepal for a telecommunication project.
- WB assisted in implementing 2nd five year plan of Nepal and has since then involved in development sector.
- Nepal obtained International Maritime Organization's membership oin January, 31, 1979.
- Nepal obtained IFAD membership on May 5, 1978.
- Nepal obtained World Meteorological Organization's (WMO) membership on August 12, 1966.
- Nepal became member of UPU on July 11, 1956.
- Nepal became member of International Telecommunication Union on December 5, 1957.
- Nepal became member of International Monetary Fund on September 6, 1961.
- Nepal became member of WHO on May 10, 1954.
- Nepal became member of FAO on November 27, 1951.
- International treaty against corruption was held on 31st October, 2003. Nepal ratified the treaty on Feb 23, 2011. The treaty came into force since December 14, 2005.
- Nepal ratified treaty for disability on 2006 AD.
- International year of family planning: 2014 AD
- UN started its environment programs on 1972 AD
- Nepal obtained membership of World Custom Organization on 22 July, 1985.
- Under organization of ILO, International convention of indigeneous and tribal communities was conducted on 1956 AD.
- UN declared 1993 AD as International Year of Indigeneous Tribes.
- UN declared 1995-2004 decade as international decade of indigeneous tribes.
- There is provision of specialized organization under UN in article 57.
- International treaty on child rights was agreed on 1989 AD
- Nepal first sent its soldiers under UN peace corps to Lebanon.
- UN first sent women only team of peace corps to Liberiya.
- The person to deliver the longest speech in UN general assembly was president Fidel Castro of Cuba, while Dawa Tshring (Bhutan) was the one to deliver the shortest (30 seconds).
- Nepal became member of FAO amongst specialized agencies of the UN, on earliest.
- South sudan, the youngest UN member nation obtained membership in July 14, 2011
- World Bank was established in Nov 14, 1947. 
- IAEA was established in 1957.
- Which among the given nations isn't the least developed country ? Srilanka, Bhutan, Afganistan, Bangladesh
- How many countries are there in UN's LDCs list ? 49
- UN initiated LDC categorization in 1971 AD.
- A minimum of 1990 USD has to be the GNI per capita in order for a country to ascend to developing country from LDC.
- James Eric Drummond was the first general secretariat of the League of Nations.
- SAARC and associated international organizations (Alliances) are established under Article 52 of the UN.
- ICAO (International Civil Aviation Organization) has its headquarters in Montreal, Canada.
- American president (Woodrow wilson) founded The League of the Nations.
- There are 9 members in the International Court of Justice.
- UN's declaration paper ("Badapatra") was signed in July 26, 1945. Exactly 51 member nations signed the document including Poland.
- UN was named as is by Franklin Rosevelt.
- There are 6 official languages in the UN.
- Arabian language was recognized by General Assembly as official language in 1973 and by security council in 1982.
- France was the first member nation to issue Veto. It was issued of withdrawl of Anglo-french millitants from Egypt.
- Advisory body of UN is General Assembly that provides guidelines.
- Language and nations:
  - Cambodia $\longrightarrow$ Khamer
  - Brunei $\longrightarrow$ Malay
- General assembly can take decisions based on Majority in general subject matters.
- There are 15 members in the security council.
- UN's security council's temporary membership status is granted for 2 years.
- In UN security council, election of members are from:
  - Eastern europe: 1
  - Western europe: 2
- In economic and social council, there are 54 member nations. These have a term of 3 years.
- In Economic and social council, following membership scheme is followed:
  - Asia: 11 countries
  - Latin america: 10 countries
  - East europe: 6 countries
  - Africa: 14 countries
  - Western europe: 13 countries
- Term of the International court of justice judges is 9 years.
- The term of Chief justice of ICJ is 3 years.
- UN's administrative body is the secretariat.
- UN's general secretary and judicial council (judges) is elected by the recommendation of security council and endorsed by 2/3rd majority of the General assembly.
- Trigbely (from Norway) was the first general secretary of the UN.
- Since the inception of UN, there have been 8 appointments of the general secretary.
- Nepal obtained the UN membership on Dec 14, 1955.
- 16 nations, including Nepal obtained the membership on the same day. The activity is known as package deal.
- Austria, Italy, Portugal, Cambodia along with only south asian nation to be alongside Nepal in becoming the member of the UN was Srilanka.
- UN flag came to practice since Oct 20, 1947.
- The largest budget contributors to the UN are known as the Big seven.
- Britain was the first country to execute veto in the Security council.
- USSR is the country to excise its veto the highest number of times in the Security council.
- UN observed 1967 as Tourism year.
- UN observed 1968 as Human rights year.
- UN observed 1975 as Women's year.
- UN observed 1985 as Youth's year.
- UN observed 1990 as International literacy year.
- UN observed 2002 as Mountainous year.
- Mr. Rishikesh Shah is the first permanent representative for Nepal to UN.
- "An agenda for peace, an agenda for development" reports was evaluatively implemented by Butroes Butroes Gholi.
- "Quiet revolution" working paper was presented by Kolfi Annan.
- There are 10000 words in the UN declaration and 111 articles and 19 chapters (?)
- Mr. Padam Bahadur Kshetri first brought forward the proposal to the UN for Nepal's accession.
- Nepal obtained confirmation of (endorsement) 57 nations while in the referendum for accession to the UN.
- Nepal deposited the letter for UN membership officially on 13th October 1949.
- Nepal selected Newari language in the script for the letter of membership.
- Mr. Tankaprasad Acharya was the Nepalses PM when Nepal obtained the membership.
- Nepal had been participating in the UN general assembly since 1956 AD
- While representing Nepal to UN for first time, Mr. Chuda Prasad Sharma led a 6 person team.
- Nepal army has been participating in UN peace force since 1958.
- Nepal has been nominated in Security council's temporary membership position two times.
- Nepal became first elected for temporary member of security council on 1969-70 AD.
- Nepal became elected as vice chair in General assembly in 1956 AD.
- First general assembly meeting was held in Jan 10, 1946 at London.
- World's "Nagarbhasa" (Also called UN charter) was prepared by Archibald Maclibs.
- UN peace corps are called blue helmets.
- "Utthanta" was the general secretariat who proposed that general secretaries should be allowed much previlage.
- Till now 3 women have chaired UN general assembly. The first of them is Bijay Laxmi Pandit (from India).
- UN's declaration of article 61 has been changed twice.
- UN university is situated at Tokyo, Japan.
- UN's secretary Wan Ki Moon has handled his position since Jan 1, 2007.
- UN's first vice General secretary was Louis Fracet.
- Trigbeli and Butroes Butroes Gholi are the only general secretaries to have chaired the office once.
- Nepal is UN's 72nd member nation.
- UN's general secretary to have died in air crash was Drag Hammer Sold.
- UNICEF received Nobel prize in 1965 while ILO received it in 1969.
- UNHCR Nansen Refugee Award is awarded annually by the UNHCR to an individual, group, or organization in recognition of outstanding service to the cause of refugees, displaced or stateless people. It was established in 1954.
- World Human Rights declaration was approved by UN's general assembly in 10 Dec, 1948.
- If a member nation does not pay membership fees for 2 years, it cannot participate in the election.
- In UN's declaration, article 1 describes about its objectives/goals.
- UN conducted at 18th yearly session of the Conference of Parties (COP) to the 1992 UNFCCC and the 8th session of the Meeting of the Parties (CMP) to the 1997 Kyoto protocol. The conference took place from monday 26 November to Saturday 8 December 2012, at the Quatar National Convention Centre in Doha.
- There were 27 nations (founder) in the League of Nations.
- India was the first among SAARC countries to obtain UN membership. Bangladesh was the last.
- South sudan is the 193rd nation to become UN member.
- UN recognized the Arabian language (most recently) as official language.
- Year 2011 AD was declared as International Year of Forest by UN.
- UNMIN was officially dismantled from Nepal in Magh 1, 2067.
- UN has 3 major organs.
- According to UN's official site, there are 15 specialized UN agencies.
- Member nations (temporary) of UN security council are elected based on geographical region and finally with support of the 2/3rd majority.
- In UN, there are 6 major committees at General Assembly.
- UN's general assembly meeting starts every year at 3rd Tuesday of October.
- Only permanent nations can veto in UN security council.
- Every member nation can select 5 candidate for general assembly election but only one can participate in election.
- Every decision of UN for important matters should be endored by 2/3rd majority.
- The security council of UN can issue veto.
- UNHCR is the organization which has been awarded the Nobel prize the highest number of times.
- UN's general secretary Ban Ki Moon held office for the second time during Jan, 2012-Dec, 2016.
- UN was established in October 24, 1945.
- According to UN's list of landlocked countries, there are 31 landlocked countries in total.
- Structural adjustment programs (SAPs) (a.k.a. structural reform) consists of loasns provided by the International Monetary Fund (IMF) and the World Bank (WB) to countries that experienced economic crises.
- SAPs are created with the goal of reducing the borrowing country's fiscal imbalances in the short and medium term or in order to adjust the economy to long-term growth.
- The World Bank and International Monetary Fund (IMF) are collectively called Bretton Woods institutions because they were created at Bretton Woods New Hampshire in 1944.
- Indian foreign service (IFS) currently conducts more than 162 Indian Diplomatic Missions. (Sept, 2019)
- IFS was created by the Government of India in October 1946 through a cabinet note.
- Career and rank structure of at IFS (in ascending order of rank):
  - At an embassy: Third Secretary (entry level), Second Secretary (promotion upon being confirmed in service), First Secretary, Counsellor, Minister, Deputy Chief of Mission/Deputy High Commissioner/ Deputy Permanent Representative, Ambassador/High Commissioner/Permanant Representative
  - At the Ministry of External affaris: Assistant Secretary/Under Secretary, Deputy Secretary, Director, Joint Secretary, Additional Secretary, Secretary, Foreign Secretary of India (India's Top Diplomat, Administrative Head of the Indian Foreign Service & Foreign Service Board)
- Satya Mohan Joshi turned 100 on 2019, May. To his honor, Lalitpur Metropolitan city unveiled the three coins of denominations Rs 100, Rs 1,000 and Rs 2,500. Banknotes will also feature his portray.
- UN celebrated 1974 as Word Population Year.
- International Court of Justice (ICJ; a.k.a World Courd) headquarters is at Peace Palance, The Hague, Netherlands.
- ICJ is the only principal UN organ not located in NYC, USA.
- Official languages of ICJ are English and French.
- President of ICJ, since 6 Feb, 2018 is Abdulqawi Yusuf (Somali national). He will lead the office till 5 Feb, 2021.
- Current vice president of ICJ is Xue Hanqin (Chinese national). 
- Former president of ICJ (before 6 Feb, 2018) was Ronny Abraham.
- ICJ is the successor of the Parliament Court of International Justice (PCIJ), which was established by the League of Nations in 1920. PCIJ began its first session in 1922.
- ICJ comprises a panel of 15 judges elected by the General Assembly and Security Council for nine-year terms.
- As of  September 15, 2019, Mr. Pradeep Kumar Gyawali is the Minister for Foreign Affairs.
- As of September 15, 2019, Mr. Shanker Das Bairagi is the Foreign Secretary of Nepal
- As of September 15, 2019, Mr. Lok Darsan Regmi is the Chief Secretary of Nepal
- There are 47 nations in UN's list of  Least Developed Countries (LDCs), as of September 15, 2019.
- The listing of LDCs is reviewed every three years by the Committee for Development (CDP).
- The listing of LDCs is available at:
  https://www.un.org/development/desa/dpad/wp-content/uploads/sites/45/publication/ldc_list.pdf

## Abbreviations and acronyms

- CDMA- Code Division Multiple Access
- CIMMYT- International Wheat and Maize Improvement Centre, Mexico
- IRRI- International Rice Research Institute, Los Bonus, Philippines (in some literature Manila)
- CIAT- International Center for Tropical Agriculture, Columbia
- CIP- International Potato Centre, Lima, Peru
- ILCA- International Livestock Centre of Africa, Ethiopia
- AVRDC- Asian Vegetable Research and Development Centre, Taiwan
- IUCN- International Union for Conservation of Nature and Natural resources
- ADB- Asian Development Bank
- DOTS- Directly Observed Treatment Shot Course
- FIFA- Federation of International Football Association
- ISBN- International Standard Book Number
- TOEFL- Test of English as a Foreign Language
- SIM- Subscriber Identification Module
- IPM- Integrated Pest Management
- INM- Integrated Nutrient Management
- ICIMOD- International Center for Integrated Mountain Development, Ktm, Nepal
- ICARDA- International Centre for Agriculture Research in Dry Area, Lebanon
- ICRISAT- International Crop Research Institute for Semi and Arid Tropics, Hyderabad, India
- IITA- International Institute of Tropical Agriculture, Nigeria
- SAARC- South Asian Association for Regional Co-operation
- SRI- System of Rice Intensification

## Famous books and authors

- Stolen Images: Lain Singh Wangdel
- Akash Bivajit Cha: book written by 10 authors of Nepal
- Palpasa Cafe/ Mayur Times: Narayan Wagle
- Seto Dharti/ Karodau Kasturi: Amar Neupane (2069 Madan Prize winner)
- Radha/ Jhola/ Adhabato: Krishna Dharabashi
- Jail Journal/ Babu Ama ra Chora/ Hitler ra Yahudi/ Doshi Chasma: B.P.Koirala
- Jiwan Kanda Ki Full: Jhamak Ghimire (2068 Madan Prize winner)
- Karnali Blues/ Phirpire: Buddi Sagar
- Damini Veer: Rajan Mukarung (2070 Madan Prize winner)
- Summer Love/ Saya: Subin Bhattarai
- Khalanga Ma Hamala: Radha Poudel (2071 Madan Prize winner)
- Zoya: Daniel Steel
- The Alchemist: Paulo Coelho
- War and Peace: Leo Tolstoy
- Mother: Maxim Gorkey
- Long Walk to Freedom: Nelson Mandela
- Paradise Lost: John Milton
- Harry Potter: J.K. Rowling
- Maile Dekheko Nepal: Dr. Harka Gurung
- The Three Mistakes of My Life: Chetan Bhagat
- Das Capital: Karl Marx
- My Experiment with Truth: Mahatma Gandhi

## Miscellaneous

- 1st Miss Nepal : Rakshya Rana [1994]
- Miss Nepal 2016: Ashmi Shrestha            
- Miss Nepal Earth: Roshani Khatri
- Miss Nepal International: Barsha Lekhi
- Miss World 2015: Mireia Lalaguna (Spain)
- Miss World 2016 is going to be held in Washington D.C., USA
- Miss Universe 2015: Pia Urtzbech (Philippines)
- Miss Universe 2016 is going to be held in Philippines.

- Kathmandu University was established in 2048 B.S.
- Province 2 has the highest population density.
- "Time zero" (Sunnya samaya) was written by Yubraj Ghimire.
- According to 2068 survey, there are 64.63% mobile phone users.
- Padmashree literature accolade of 2075 was handed to Ramesh Sayaan's "Chutteka Anuhar"
- Padmashree sadhana accolade of 2075 was handed to historian Maheshraj Panta.
- Minestrial cabinet first held their meeting with video conference in 2076, Bhadra 9.
- The hurricane that struck Bara-Parsa in Bhadra 8 was named Dhumrapat.
- Mr. Surendra Prasad Yadav was appointed chairman of Civil Service Commission of Province 2 on Bhadra 5.
- "Yuva Moti Puraskar" of 2075 was given to Shankar Chapagain (Dhankute Kancha) and Fulman Bal.
- Nepal Government's legal advisor is Chief Justice ("Mahanyadibakta")
- Gautam Buddha communicated his learnings for 45 years.
- Brazil is the country where sour honey can be found. ?
- In San Marino, there are two presidents.
- Moroccoo is the country where Red Salt is found.
- In the Shree-Swasthani Puran (a branch of Skanda puran), there are 8110 slokas.
- Full name of "Ohm" is George Simon Ohm.
- Nepals goals (by):
  - Ending child marriage: 2020 AD
  - Filariasis parasite eradication: 2020 AD
  - Transition to developing country status: 2022 AD
  - Birth rate substitution: 2022 AD
  - Doubling tiger's population: 2022 AD
  - Eradication of hunger: 2025 AD
  - Malaria eradication: 2025 AD
  - Hydroelectricity independence: 2027 AD
  - Ending of poverty: 2030 AD
  - Middle income status achievement: 2030 AD
- Which was the disease to be completely eradicated from the world: Measles.
- During Rana regime, transaction of gold, silver and valuables was done by "Bintipatra Niksari Adda".
- Ancientmost religion of Nepal is the "Saiba"
- Annual population growth rate was highest in 2038 BS.
- Article 242 of Nepal's constitution has provision for civil serivce commission.
- "Urab" is the caste that is recognized by its occupation of farming.
- India launched the Chandrayan-2 rocket on July 22, 2019.
- Madan puraskar, 2075 was awarded to Yogesh Raj's "Ranahar".
- Jagadamba shree prize, 2075 was awarded to Bairagi kaila (Til Bikram Nembang).
- Ministry of Civil Aviation and Tourism was chaired by Yogesh Bhattarai in Shrawan 15, 2076.
- International Youth Year, 2019 had slogan: "Transforming education"
- Shuvadra Adhikari (Actress) died in Shrawan 32, 2076.
- Indian foreign minister Shusma Shwaraj died on August 6, 2019.
- Province number 5 was the earliest among provinces to appoint Civil Service Commission chairman (Dr. Dilaram Bhattarai).
- Senior literary figure Madanmani Dixit died on Shrawan 30, 2076.
- 4th national forest day's slogan was "Samudayik Ban ma Nabintam Soch, Utpadan, Uddhyam ra Samriddhi ma Jodd"
- Indian government withdrew the special previlage it had been granting Kashmir based on constitutional article 370 on August 5, 2019.
- Indian national to be awarded Roman Magases prize in 2019 was Journalist Ravish Kumar.
- ICC world test championship started on Aug 1, 2019.
- Nepal first took map of the country via its satellite "Nepal Sat-1" on August 3, 2019.
- Gyanchandra Acharya was elected vice secretary of alliance of least developed and land locked countries of UN in August 14, 2012.
- According to UN report, 1/3 rd of the total food goes waste.
- Since 2008 AD, WHO started observing World Malaria day every 25th of April.
- The first female chief of the IMF was Christina Glagards (France).
- Country to first grow seedling in the outer space was China.
- Ramjanaki temple is in the Dhanusha district.
- Goitre is caused by the deficiency of iodine.
- Ten writers jointly wrote the publication: "Aakash bivajit chha"
- Simikot is the headquarters of Humla district, which also happens to be the headquarters at the highest altitude.
- Youngest mountaineer to have climbed the Mount Everest is Dorje Sherpa.
- Currently, local development minister is Lal Babu Pandit.
- Bamboo is the quickest growing plant.
- Madan Ashrit highway is 36.16 km in length.
- The inventor of parachute was Joe Blanchard.
- Water is heaviest at 40 degree F.
- Human blood is 6 times more viscous than water.
- A cat sleeps 16 hours in a day.
- Nepal's constitution day is celebrated on Ashoj 3.
- "Dying is begin born again": Shukraraj Shastri
- A person who transcribes others' writing word by word is called a ghost writer.
- Amar Singh Thapa died in the battle of Palanchowk.
- Mendel's pea had 7 pairs of contrasting characters.
- Nepal government initiated the cancer protocol on 25th Baisakh, 2074.
- Britain's first woman PM is Margaret Thatcher.
- An instrument for lie detection is called Polygraph.
- Amar Neupane wrote "Karodau Kasturi".
- Satya Mohan Joshi is a Nepali writer and scholar.
  -	He is famous for his research on history and culture of Nepal. 
  -	He is working now as the chancellor for Nepal Basa Academy
  -	He was born in 1920 in Lalitpur
  -	He has following publications: Haamro lok sanskriti, Kalakar Arniko, Sunkhesari, Majipa Lakhe.
- China and Nepal recently agreed upon opening up following borders for ? when ?:
  - Tinker: Darchula
  - Kimathanka: Sankhuwasabha
  - Yari: Humla
  - Kodari tatopani: Sindhupalchowk
  - Olangchungola: Taplejung
  - Rasuwagadhi: Rasuwa
- National innovation center was established in Nov 9, 2012
- National Academy of Science and Technology was established in 1982
- Bonn challenge: https://en.wikipedia.org/wiki/Bonn_Challenge
- Ministry of forests and environment reports: https://mofe.gov.np/downloadsdetail/3/2018/98853603/
- Department of wildlife conservation: http://www.dnpwc.gov.np/en/project/

**Nobel Prize-2016**

- Nobel Prize in Physics 2016 David J. Thouless, F. Duncan M. Haldane and J. Michael Kosterlitz "for theoretical discoveries of topological phase transitions and topological phases of matter"
- Nobel Prize in Chemistry 2016 Jean-Pierre Sauvage, Sir J. Fraser Stoddart and Bernard L. Feringa "for the design and synthesis of molecular machines"
- Nobel Prize in Physiology or Medicine 2016 Yoshinori Ohsumi "for his discoveries of mechanisms for autophagy"
- Nobel Prize in Literature 2016 Bob Dylan "for having created new poetic expressions within the great American song tradition"
- Nobel Peace Prize 2016 Juan Manuel Santos "for his resolute efforts to bring the country's more than 50-year-long civil war to an end"
- Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel 2016 Oliver Hart and Bengt Holmström "for their contributions to contract theory"

**Important metric conversions**

- 1 hectare = 10000m2 = 30 katha = 20 ropani = 2.47 acre = 1.5 bigha
- 1 bigha = 20 katha = 13.31 ropani
- 1 ropani = 16 anna = 508.5m2
- 1 katha = 20 dhur = 338.6m2
- 1 pathi = 8 mana
- 1 mana = 568 ml
- 1 muri = 20 pathi
- 1 ton = 1000 kg
- 1 kg = 2.2 pound
- 1 pound = 16 ounce
- 1 inch = 2.54 cm
- 1 gallon = 4.5 ltr

**Some Revolutions**

- Black Revolution: Petroleum Production
- Green Revolution: (1965/66) in Agriculture
- White Revolution: Related to milk production or operation
- Blue Revolution: Fisheries production
- Brown Revolution: Leather/Cocoa production
- Golden Revolution: horticulture production/ honey production
- Golden Fiber Revolution: Jute production
- Gray Revolution: Fertilizer production
- Pink Revolution: Onion/ Prawn production
- Red Revolution: Meat/tomato production
- Silver Revolution: Egg/ Poultry production
- Yellow Revolution: production of oilseeds
- Round Revolution: Potato production
- Fibre Revolution: Cotton production
- Rainbow Revolution: Agriculture

- 1st Myagassae Prize Winner: Tulshi Mehar Shrestha
- Most comedy picture in Facebook: Chinese Basketball player Yaw Ming
- Director of movie Slumdog Millionaire: Dany Boyle
- Director of movie Titanic and Avatar: James Cameroon
- Number of national parks in the World is about 7000.
- Baburam Acharya coined the name Sagarmatha for Mt.Everest
- Number of pointed sides in the sun of national flag of Nepal is 12 and in the moon is 8.
- Bird found only in Nepal: Kande Bhyakur (Spiny babbler)
- Founder of Google: Larry Page and Sargey Brin (meaning of Google is 1000 zeros after one)
- Founder of Facebook: Mark Zuckerberg
- Founder of Yahoo: Jerry Yang and David Fillo
- First test tube baby: Louis Brown

